///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace project1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The calculator recording.
    /// </summary>
    [TestModule("c381cab8-7c10-4fef-9209-c04580742bcc", ModuleType.Recording, 1)]
    public partial class calculator : ITestModule
    {
        /// <summary>
        /// Holds an instance of the project1Repository repository.
        /// </summary>
        public static project1Repository repo = project1Repository.Instance;

        static calculator instance = new calculator();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public calculator()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static calculator Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run application 'C:\\Windows\\System32\\calc.exe' with arguments '' in normal mode.", new RecordItemIndex(0));
            Host.Local.RunApplication("C:\\Windows\\System32\\calc.exe", "", "C:\\Windows\\System32", false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.Calc.Button' at 19;17.", repo.Calculator.Calc.ButtonInfo, new RecordItemIndex(1));
            repo.Calculator.Calc.Button.Click("19;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.Calc.Button1' at 25;14.", repo.Calculator.Calc.Button1Info, new RecordItemIndex(2));
            repo.Calculator.Calc.Button1.Click("25;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.Calc.Button2' at 12;15.", repo.Calculator.Calc.Button2Info, new RecordItemIndex(3));
            repo.Calculator.Calc.Button2.Click("12;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.Calc.Button3' at 11;16.", repo.Calculator.Calc.Button3Info, new RecordItemIndex(4));
            repo.Calculator.Calc.Button3.Click("11;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.Calc.Button4' at 17;14.", repo.Calculator.Calc.Button4Info, new RecordItemIndex(5));
            repo.Calculator.Calc.Button4.Click("17;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.Calc.Button5' at 23;10.", repo.Calculator.Calc.Button5Info, new RecordItemIndex(6));
            repo.Calculator.Calc.Button5.Click("23;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.Calc.Button6' at 8;12.", repo.Calculator.Calc.Button6Info, new RecordItemIndex(7));
            repo.Calculator.Calc.Button6.Click("8;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.Calc.Button7' at 21;11.", repo.Calculator.Calc.Button7Info, new RecordItemIndex(8));
            repo.Calculator.Calc.Button7.Click("21;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.Calc.Button8' at 21;15.", repo.Calculator.Calc.Button8Info, new RecordItemIndex(9));
            repo.Calculator.Calc.Button8.Click("21;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.Calc.Button9' at 3;15.", repo.Calculator.Calc.Button9Info, new RecordItemIndex(10));
            repo.Calculator.Calc.Button9.Click("3;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.Calc.Button10' at 19;12.", repo.Calculator.Calc.Button10Info, new RecordItemIndex(11));
            repo.Calculator.Calc.Button10.Click("19;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.Calc.Button11' at 17;12.", repo.Calculator.Calc.Button11Info, new RecordItemIndex(12));
            repo.Calculator.Calc.Button11.Click("17;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.Calc.Button12' at 4;16.", repo.Calculator.Calc.Button12Info, new RecordItemIndex(13));
            repo.Calculator.Calc.Button12.Click("4;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.Calc.Button13' at 9;16.", repo.Calculator.Calc.Button13Info, new RecordItemIndex(14));
            repo.Calculator.Calc.Button13.Click("9;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.Calc.ContainerHash32770' at 154;80.", repo.Calculator.Calc.ContainerHash32770Info, new RecordItemIndex(15));
            repo.Calculator.Calc.ContainerHash32770.Click("154;80");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.Calc.Button14' at 7;16.", repo.Calculator.Calc.Button14Info, new RecordItemIndex(16));
            repo.Calculator.Calc.Button14.Click("7;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.Calc.Button15' at 19;11.", repo.Calculator.Calc.Button15Info, new RecordItemIndex(17));
            repo.Calculator.Calc.Button15.Click("19;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.Calc.Button16' at 13;13.", repo.Calculator.Calc.Button16Info, new RecordItemIndex(18));
            repo.Calculator.Calc.Button16.Click("13;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.Calc.Button17' at 13;13.", repo.Calculator.Calc.Button17Info, new RecordItemIndex(19));
            repo.Calculator.Calc.Button17.Click("13;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.Calc.Button18' at 14;13.", repo.Calculator.Calc.Button18Info, new RecordItemIndex(20));
            repo.Calculator.Calc.Button18.Click("14;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.Calc.Button19' at 27;16.", repo.Calculator.Calc.Button19Info, new RecordItemIndex(21));
            repo.Calculator.Calc.Button19.Click("27;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.Calc.Button20' at 19;9.", repo.Calculator.Calc.Button20Info, new RecordItemIndex(22));
            repo.Calculator.Calc.Button20.Click("19;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.Calc.Button21' at 16;11.", repo.Calculator.Calc.Button21Info, new RecordItemIndex(23));
            repo.Calculator.Calc.Button21.Click("16;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.Calc.Button22' at 13;11.", repo.Calculator.Calc.Button22Info, new RecordItemIndex(24));
            repo.Calculator.Calc.Button22.Click("13;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.Calc.Button23' at 7;14.", repo.Calculator.Calc.Button23Info, new RecordItemIndex(25));
            repo.Calculator.Calc.Button23.Click("7;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.Calc.Button24' at 9;14.", repo.Calculator.Calc.Button24Info, new RecordItemIndex(26));
            repo.Calculator.Calc.Button24.Click("9;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.Calc.Button25' at 49;4.", repo.Calculator.Calc.Button25Info, new RecordItemIndex(27));
            repo.Calculator.Calc.Button25.Click("49;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.Calc.Button26' at 30;6.", repo.Calculator.Calc.Button26Info, new RecordItemIndex(28));
            repo.Calculator.Calc.Button26.Click("30;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.Calc.Button27' at 8;7.", repo.Calculator.Calc.Button27Info, new RecordItemIndex(29));
            repo.Calculator.Calc.Button27.Click("8;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.Calc.Button18' at 14;16.", repo.Calculator.Calc.Button18Info, new RecordItemIndex(30));
            repo.Calculator.Calc.Button18.Click("14;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.Calc.Button19' at 21;18.", repo.Calculator.Calc.Button19Info, new RecordItemIndex(31));
            repo.Calculator.Calc.Button19.Click("21;18");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.Close' at 18;11.", repo.Calculator.CloseInfo, new RecordItemIndex(32));
            repo.Calculator.Close.Click("18;11");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
