///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace project1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The calctest recording.
    /// </summary>
    [TestModule("db1eca65-4d79-449f-b6e2-14e0e39e4c2e", ModuleType.Recording, 1)]
    public partial class calctest : ITestModule
    {
        /// <summary>
        /// Holds an instance of the project1Repository repository.
        /// </summary>
        public static project1Repository repo = project1Repository.Instance;

        static calctest instance = new calctest();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public calctest()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static calctest Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run application 'C:\\Windows\\System32\\calc.exe' with arguments '' in normal mode.", new RecordItemIndex(0));
            Host.Local.RunApplication("C:\\Windows\\System32\\calc.exe", "", "C:\\Windows\\System32", false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.Calc.Button11' at 18;13.", repo.Calculator.Calc.Button11Info, new RecordItemIndex(1));
            repo.Calculator.Calc.Button11.Click("18;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.Calc.Button18' at 25;10.", repo.Calculator.Calc.Button18Info, new RecordItemIndex(2));
            repo.Calculator.Calc.Button18.Click("25;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.Calc.Button11' at 18;16.", repo.Calculator.Calc.Button11Info, new RecordItemIndex(3));
            repo.Calculator.Calc.Button11.Click("18;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.Calc.Button6' at 17;13.", repo.Calculator.Calc.Button6Info, new RecordItemIndex(4));
            repo.Calculator.Calc.Button6.Click("17;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.Calc.Button20' at Center.", repo.Calculator.Calc.Button20Info, new RecordItemIndex(5));
            repo.Calculator.Calc.Button20.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.Calc.Button27' at Center.", repo.Calculator.Calc.Button27Info, new RecordItemIndex(6));
            repo.Calculator.Calc.Button27.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.Calc.Button15' at Center.", repo.Calculator.Calc.Button15Info, new RecordItemIndex(7));
            repo.Calculator.Calc.Button15.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.Calc.Button24' at 19;46.", repo.Calculator.Calc.Button24Info, new RecordItemIndex(8));
            repo.Calculator.Calc.Button24.Click("19;46");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.Close' at 23;13.", repo.Calculator.CloseInfo, new RecordItemIndex(9));
            repo.Calculator.Close.Click("23;13");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
