///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace project1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The exceltest recording.
    /// </summary>
    [TestModule("a873889c-c1fe-48a3-a8a1-5cbaed1bc214", ModuleType.Recording, 1)]
    public partial class exceltest : ITestModule
    {
        /// <summary>
        /// Holds an instance of the project1Repository repository.
        /// </summary>
        public static project1Repository repo = project1Repository.Instance;

        static exceltest instance = new exceltest();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public exceltest()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static exceltest Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run application 'C:\\Windows\\System32\\calc.exe' with arguments '' in normal mode.", new RecordItemIndex(0));
            Host.Local.RunApplication("C:\\Windows\\System32\\calc.exe", "", "C:\\Windows\\System32", false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'Explorer.Accountdata' at 47;43.", repo.Explorer.AccountdataInfo, new RecordItemIndex(1));
            repo.Explorer.Accountdata.DoubleClick("47;43");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Explorer.Accountdata' at 68;10.", repo.Explorer.AccountdataInfo, new RecordItemIndex(2));
            repo.Explorer.Accountdata.Click("68;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}{Back}{Back}' with focus on 'MicrosoftExcelAccountdataCompatib.EXCEL'.", repo.MicrosoftExcelAccountdataCompatib.EXCELInfo, new RecordItemIndex(3));
            repo.MicrosoftExcelAccountdataCompatib.EXCEL.PressKeys("{Back}{Back}{Back}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'hhhhhhhhhh' with focus on 'MicrosoftExcelAccountdataCompatib.EXCEL'.", repo.MicrosoftExcelAccountdataCompatib.EXCELInfo, new RecordItemIndex(4));
            repo.MicrosoftExcelAccountdataCompatib.EXCEL.PressKeys("hhhhhhhhhh");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'MicrosoftExcelAccountdataCompatib.EXCEL'.", repo.MicrosoftExcelAccountdataCompatib.EXCELInfo, new RecordItemIndex(5));
            repo.MicrosoftExcelAccountdataCompatib.EXCEL.PressKeys("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MicrosoftExcelAccountdataCompatib.Insert' at 35;11.", repo.MicrosoftExcelAccountdataCompatib.InsertInfo, new RecordItemIndex(6));
            repo.MicrosoftExcelAccountdataCompatib.Insert.Click("35;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MicrosoftExcelAccountdataCompatib.PageLayout' at 41;13.", repo.MicrosoftExcelAccountdataCompatib.PageLayoutInfo, new RecordItemIndex(7));
            repo.MicrosoftExcelAccountdataCompatib.PageLayout.Click("41;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MicrosoftExcelAccountdataCompatib.Ribbon' at 968;2.", repo.MicrosoftExcelAccountdataCompatib.RibbonInfo, new RecordItemIndex(8));
            repo.MicrosoftExcelAccountdataCompatib.Ribbon.Click("968;2");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MicrosoftExcelAccountdataCompatib.Save' at 55;11.", repo.MicrosoftExcelAccountdataCompatib.SaveInfo, new RecordItemIndex(9));
            repo.MicrosoftExcelAccountdataCompatib.Save.Click("55;11");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
