///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace project1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Repository1 element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    [RepositoryFolder("4ad8ce1f-e9fd-4bc1-9e08-44a24bd02189")]
    public partial class Repository1 : RepoGenBaseFolder
    {
        static Repository1 instance = new Repository1();
        Repository1Folders.CalculatorAppFolder _calculator;

        /// <summary>
        /// Gets the singleton class instance representing the Repository1 element repository.
        /// </summary>
        [RepositoryFolder("4ad8ce1f-e9fd-4bc1-9e08-44a24bd02189")]
        public static Repository1 Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Repository1() 
            : base("Repository1", "/", null, 0, false, "4ad8ce1f-e9fd-4bc1-9e08-44a24bd02189", ".\\RepositoryImages\\Repository14ad8ce1f.rximgres")
        {
            _calculator = new Repository1Folders.CalculatorAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("4ad8ce1f-e9fd-4bc1-9e08-44a24bd02189")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Calculator folder.
        /// </summary>
        [RepositoryFolder("9e839a28-966f-49b0-9218-97d7d3ac4df2")]
        public virtual Repository1Folders.CalculatorAppFolder Calculator
        {
            get { return _calculator; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    public partial class Repository1Folders
    {
        /// <summary>
        /// The CalculatorAppFolder folder.
        /// </summary>
        [RepositoryFolder("9e839a28-966f-49b0-9218-97d7d3ac4df2")]
        public partial class CalculatorAppFolder : RepoGenBaseFolder
        {
            Repository1Folders.CalcFolder _calc;
            RepoItemInfo _closeInfo;

            /// <summary>
            /// Creates a new Calculator  folder.
            /// </summary>
            public CalculatorAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Calculator", "/form[@title='Calculator']", parentFolder, 30000, null, true, "9e839a28-966f-49b0-9218-97d7d3ac4df2", "")
            {
                _calc = new Repository1Folders.CalcFolder(this);
                _closeInfo = new RepoItemInfo(this, "Close", "?/?/button[@accessiblename='Close']", 30000, null, "0e3fb469-3b3c-45c8-8dcf-98e1f85b81e1");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9e839a28-966f-49b0-9218-97d7d3ac4df2")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9e839a28-966f-49b0-9218-97d7d3ac4df2")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("0e3fb469-3b3c-45c8-8dcf-98e1f85b81e1")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("0e3fb469-3b3c-45c8-8dcf-98e1f85b81e1")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }

            /// <summary>
            /// The Calc folder.
            /// </summary>
            [RepositoryFolder("d0d9a3bc-9367-4a98-968f-2a16dfc5586d")]
            public virtual Repository1Folders.CalcFolder Calc
            {
                get { return _calc; }
            }
        }

        /// <summary>
        /// The CalcFolder folder.
        /// </summary>
        [RepositoryFolder("d0d9a3bc-9367-4a98-968f-2a16dfc5586d")]
        public partial class CalcFolder : RepoGenBaseFolder
        {
            RepoItemInfo _containerhash32770Info;
            RepoItemInfo _button9Info;
            RepoItemInfo _button19Info;
            RepoItemInfo _button14Info;
            RepoItemInfo _button24Info;
            RepoItemInfo _button1Info;
            RepoItemInfo _buttonInfo;
            RepoItemInfo _button2Info;
            RepoItemInfo _button3Info;
            RepoItemInfo _button4Info;
            RepoItemInfo _button20Info;
            RepoItemInfo _button21Info;
            RepoItemInfo _button22Info;
            RepoItemInfo _button15Info;
            RepoItemInfo _button16Info;
            RepoItemInfo _button17Info;
            RepoItemInfo _button10Info;
            RepoItemInfo _button11Info;
            RepoItemInfo _button12Info;
            RepoItemInfo _button8Info;
            RepoItemInfo _button7Info;
            RepoItemInfo _button6Info;
            RepoItemInfo _button5Info;
            RepoItemInfo _button26Info;
            RepoItemInfo _button13Info;
            RepoItemInfo _button18Info;
            RepoItemInfo _button27Info;
            RepoItemInfo _button23Info;

            /// <summary>
            /// Creates a new Calc  folder.
            /// </summary>
            public CalcFolder(RepoGenBaseFolder parentFolder) :
                    base("Calc", "?/?/container[@instance='1']", parentFolder, 30000, null, false, "d0d9a3bc-9367-4a98-968f-2a16dfc5586d", "")
            {
                _containerhash32770Info = new RepoItemInfo(this, "ContainerHash32770", "", 30000, null, "43ff849d-9add-455c-81f4-02dc72e9d511");
                _button9Info = new RepoItemInfo(this, "Button9", "button[@controlid='110']", 30000, null, "f316b4a4-688c-498a-86cc-ebcd34d3e042");
                _button19Info = new RepoItemInfo(this, "Button19", "button[@controlid='114']", 30000, null, "cf4aa2f9-fcde-45f2-9810-03e21e6e34be");
                _button14Info = new RepoItemInfo(this, "Button14", "button[@controlid='118']", 30000, null, "f6fd56c8-41c4-400c-b0e3-ac072ff26271");
                _button24Info = new RepoItemInfo(this, "Button24", "button[@controlid='121']", 30000, null, "c5762a71-20c2-4281-9d0d-46d11e5ffbfc");
                _button1Info = new RepoItemInfo(this, "Button1", "button[@controlid='123']", 30000, null, "6febac9f-4d34-49ec-8727-33326f734323");
                _buttonInfo = new RepoItemInfo(this, "Button", "button[@controlid='122']", 30000, null, "6304ec8b-3f79-46f7-b4c1-48eb419aa8ea");
                _button2Info = new RepoItemInfo(this, "Button2", "button[@controlid='124']", 30000, null, "4fadc255-42ea-40ae-819b-1d3d1087a3e7");
                _button3Info = new RepoItemInfo(this, "Button3", "button[@controlid='125']", 30000, null, "5e937874-3836-4865-a269-3ad3ec507440");
                _button4Info = new RepoItemInfo(this, "Button4", "button[@controlid='126']", 30000, null, "3aa107c4-141c-4664-96b0-5772c34b35d5");
                _button20Info = new RepoItemInfo(this, "Button20", "button[@controlid='131']", 30000, null, "890cfac9-911b-47bc-84ec-f8ea1e64ad39");
                _button21Info = new RepoItemInfo(this, "Button21", "button[@controlid='132']", 30000, null, "6b6ce2cf-0cf2-4d5c-898f-4879ed877881");
                _button22Info = new RepoItemInfo(this, "Button22", "button[@controlid='133']", 30000, null, "25697f02-520c-4522-a51c-41379440970b");
                _button15Info = new RepoItemInfo(this, "Button15", "button[@controlid='134']", 30000, null, "631289d4-c066-4e4d-a65c-a7d5516e8218");
                _button16Info = new RepoItemInfo(this, "Button16", "button[@controlid='135']", 30000, null, "61867b6d-8abc-44ba-908a-163bcb39828f");
                _button17Info = new RepoItemInfo(this, "Button17", "button[@controlid='136']", 30000, null, "e65f7f1c-839d-417c-a252-9357fd6bb43d");
                _button10Info = new RepoItemInfo(this, "Button10", "button[@controlid='137']", 30000, null, "73c30c9f-db70-435f-ac96-6bde3a108f51");
                _button11Info = new RepoItemInfo(this, "Button11", "button[@controlid='138']", 30000, null, "e40e36de-5984-46b0-b6e2-06e6a8bd7431");
                _button12Info = new RepoItemInfo(this, "Button12", "button[@controlid='139']", 30000, null, "e6f94270-8127-4d9c-a6a6-85d8c5677087");
                _button8Info = new RepoItemInfo(this, "Button8", "button[@controlid='80']", 30000, null, "78b8cbdd-7c5a-4b48-8869-d7791b0c54a3");
                _button7Info = new RepoItemInfo(this, "Button7", "button[@controlid='81']", 30000, null, "66610eb6-4df1-4920-ad91-fe9018c531f0");
                _button6Info = new RepoItemInfo(this, "Button6", "button[@controlid='82']", 30000, null, "b8972015-19de-4077-b45b-d2a217c58665");
                _button5Info = new RepoItemInfo(this, "Button5", "button[@controlid='83']", 30000, null, "b51e7166-a7da-4bfe-8113-3925104e9f14");
                _button26Info = new RepoItemInfo(this, "Button26", "button[@controlid='84']", 30000, null, "ca0505c8-914b-4540-9f9f-67dd584a15b2");
                _button13Info = new RepoItemInfo(this, "Button13", "button[@controlid='91']", 30000, null, "b846f02e-bddd-408e-8dc4-e0d77683e5c9");
                _button18Info = new RepoItemInfo(this, "Button18", "button[@controlid='92']", 30000, null, "9ff8f4d5-4e26-45b3-94e5-0def007918fb");
                _button27Info = new RepoItemInfo(this, "Button27", "button[@controlid='93']", 30000, null, "804fc7f5-d4f6-4877-bb6d-7862dc8f42f0");
                _button23Info = new RepoItemInfo(this, "Button23", "button[@controlid='94']", 30000, null, "5bc3a93c-81c0-40d8-9db7-0aaa2485c60d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d0d9a3bc-9367-4a98-968f-2a16dfc5586d")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d0d9a3bc-9367-4a98-968f-2a16dfc5586d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ContainerHash32770 item.
            /// </summary>
            [RepositoryItem("43ff849d-9add-455c-81f4-02dc72e9d511")]
            public virtual Ranorex.Container ContainerHash32770
            {
                get
                {
                    return _containerhash32770Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The ContainerHash32770 item info.
            /// </summary>
            [RepositoryItemInfo("43ff849d-9add-455c-81f4-02dc72e9d511")]
            public virtual RepoItemInfo ContainerHash32770Info
            {
                get
                {
                    return _containerhash32770Info;
                }
            }

            /// <summary>
            /// The Button9 item.
            /// </summary>
            [RepositoryItem("f316b4a4-688c-498a-86cc-ebcd34d3e042")]
            public virtual Ranorex.Button Button9
            {
                get
                {
                    return _button9Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button9 item info.
            /// </summary>
            [RepositoryItemInfo("f316b4a4-688c-498a-86cc-ebcd34d3e042")]
            public virtual RepoItemInfo Button9Info
            {
                get
                {
                    return _button9Info;
                }
            }

            /// <summary>
            /// The Button19 item.
            /// </summary>
            [RepositoryItem("cf4aa2f9-fcde-45f2-9810-03e21e6e34be")]
            public virtual Ranorex.Button Button19
            {
                get
                {
                    return _button19Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button19 item info.
            /// </summary>
            [RepositoryItemInfo("cf4aa2f9-fcde-45f2-9810-03e21e6e34be")]
            public virtual RepoItemInfo Button19Info
            {
                get
                {
                    return _button19Info;
                }
            }

            /// <summary>
            /// The Button14 item.
            /// </summary>
            [RepositoryItem("f6fd56c8-41c4-400c-b0e3-ac072ff26271")]
            public virtual Ranorex.Button Button14
            {
                get
                {
                    return _button14Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button14 item info.
            /// </summary>
            [RepositoryItemInfo("f6fd56c8-41c4-400c-b0e3-ac072ff26271")]
            public virtual RepoItemInfo Button14Info
            {
                get
                {
                    return _button14Info;
                }
            }

            /// <summary>
            /// The Button24 item.
            /// </summary>
            [RepositoryItem("c5762a71-20c2-4281-9d0d-46d11e5ffbfc")]
            public virtual Ranorex.Button Button24
            {
                get
                {
                    return _button24Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button24 item info.
            /// </summary>
            [RepositoryItemInfo("c5762a71-20c2-4281-9d0d-46d11e5ffbfc")]
            public virtual RepoItemInfo Button24Info
            {
                get
                {
                    return _button24Info;
                }
            }

            /// <summary>
            /// The Button1 item.
            /// </summary>
            [RepositoryItem("6febac9f-4d34-49ec-8727-33326f734323")]
            public virtual Ranorex.Button Button1
            {
                get
                {
                    return _button1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button1 item info.
            /// </summary>
            [RepositoryItemInfo("6febac9f-4d34-49ec-8727-33326f734323")]
            public virtual RepoItemInfo Button1Info
            {
                get
                {
                    return _button1Info;
                }
            }

            /// <summary>
            /// The Button item.
            /// </summary>
            [RepositoryItem("6304ec8b-3f79-46f7-b4c1-48eb419aa8ea")]
            public virtual Ranorex.Button Button
            {
                get
                {
                    return _buttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button item info.
            /// </summary>
            [RepositoryItemInfo("6304ec8b-3f79-46f7-b4c1-48eb419aa8ea")]
            public virtual RepoItemInfo ButtonInfo
            {
                get
                {
                    return _buttonInfo;
                }
            }

            /// <summary>
            /// The Button2 item.
            /// </summary>
            [RepositoryItem("4fadc255-42ea-40ae-819b-1d3d1087a3e7")]
            public virtual Ranorex.Button Button2
            {
                get
                {
                    return _button2Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button2 item info.
            /// </summary>
            [RepositoryItemInfo("4fadc255-42ea-40ae-819b-1d3d1087a3e7")]
            public virtual RepoItemInfo Button2Info
            {
                get
                {
                    return _button2Info;
                }
            }

            /// <summary>
            /// The Button3 item.
            /// </summary>
            [RepositoryItem("5e937874-3836-4865-a269-3ad3ec507440")]
            public virtual Ranorex.Button Button3
            {
                get
                {
                    return _button3Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button3 item info.
            /// </summary>
            [RepositoryItemInfo("5e937874-3836-4865-a269-3ad3ec507440")]
            public virtual RepoItemInfo Button3Info
            {
                get
                {
                    return _button3Info;
                }
            }

            /// <summary>
            /// The Button4 item.
            /// </summary>
            [RepositoryItem("3aa107c4-141c-4664-96b0-5772c34b35d5")]
            public virtual Ranorex.Button Button4
            {
                get
                {
                    return _button4Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button4 item info.
            /// </summary>
            [RepositoryItemInfo("3aa107c4-141c-4664-96b0-5772c34b35d5")]
            public virtual RepoItemInfo Button4Info
            {
                get
                {
                    return _button4Info;
                }
            }

            /// <summary>
            /// The Button20 item.
            /// </summary>
            [RepositoryItem("890cfac9-911b-47bc-84ec-f8ea1e64ad39")]
            public virtual Ranorex.Button Button20
            {
                get
                {
                    return _button20Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button20 item info.
            /// </summary>
            [RepositoryItemInfo("890cfac9-911b-47bc-84ec-f8ea1e64ad39")]
            public virtual RepoItemInfo Button20Info
            {
                get
                {
                    return _button20Info;
                }
            }

            /// <summary>
            /// The Button21 item.
            /// </summary>
            [RepositoryItem("6b6ce2cf-0cf2-4d5c-898f-4879ed877881")]
            public virtual Ranorex.Button Button21
            {
                get
                {
                    return _button21Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button21 item info.
            /// </summary>
            [RepositoryItemInfo("6b6ce2cf-0cf2-4d5c-898f-4879ed877881")]
            public virtual RepoItemInfo Button21Info
            {
                get
                {
                    return _button21Info;
                }
            }

            /// <summary>
            /// The Button22 item.
            /// </summary>
            [RepositoryItem("25697f02-520c-4522-a51c-41379440970b")]
            public virtual Ranorex.Button Button22
            {
                get
                {
                    return _button22Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button22 item info.
            /// </summary>
            [RepositoryItemInfo("25697f02-520c-4522-a51c-41379440970b")]
            public virtual RepoItemInfo Button22Info
            {
                get
                {
                    return _button22Info;
                }
            }

            /// <summary>
            /// The Button15 item.
            /// </summary>
            [RepositoryItem("631289d4-c066-4e4d-a65c-a7d5516e8218")]
            public virtual Ranorex.Button Button15
            {
                get
                {
                    return _button15Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button15 item info.
            /// </summary>
            [RepositoryItemInfo("631289d4-c066-4e4d-a65c-a7d5516e8218")]
            public virtual RepoItemInfo Button15Info
            {
                get
                {
                    return _button15Info;
                }
            }

            /// <summary>
            /// The Button16 item.
            /// </summary>
            [RepositoryItem("61867b6d-8abc-44ba-908a-163bcb39828f")]
            public virtual Ranorex.Button Button16
            {
                get
                {
                    return _button16Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button16 item info.
            /// </summary>
            [RepositoryItemInfo("61867b6d-8abc-44ba-908a-163bcb39828f")]
            public virtual RepoItemInfo Button16Info
            {
                get
                {
                    return _button16Info;
                }
            }

            /// <summary>
            /// The Button17 item.
            /// </summary>
            [RepositoryItem("e65f7f1c-839d-417c-a252-9357fd6bb43d")]
            public virtual Ranorex.Button Button17
            {
                get
                {
                    return _button17Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button17 item info.
            /// </summary>
            [RepositoryItemInfo("e65f7f1c-839d-417c-a252-9357fd6bb43d")]
            public virtual RepoItemInfo Button17Info
            {
                get
                {
                    return _button17Info;
                }
            }

            /// <summary>
            /// The Button10 item.
            /// </summary>
            [RepositoryItem("73c30c9f-db70-435f-ac96-6bde3a108f51")]
            public virtual Ranorex.Button Button10
            {
                get
                {
                    return _button10Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button10 item info.
            /// </summary>
            [RepositoryItemInfo("73c30c9f-db70-435f-ac96-6bde3a108f51")]
            public virtual RepoItemInfo Button10Info
            {
                get
                {
                    return _button10Info;
                }
            }

            /// <summary>
            /// The Button11 item.
            /// </summary>
            [RepositoryItem("e40e36de-5984-46b0-b6e2-06e6a8bd7431")]
            public virtual Ranorex.Button Button11
            {
                get
                {
                    return _button11Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button11 item info.
            /// </summary>
            [RepositoryItemInfo("e40e36de-5984-46b0-b6e2-06e6a8bd7431")]
            public virtual RepoItemInfo Button11Info
            {
                get
                {
                    return _button11Info;
                }
            }

            /// <summary>
            /// The Button12 item.
            /// </summary>
            [RepositoryItem("e6f94270-8127-4d9c-a6a6-85d8c5677087")]
            public virtual Ranorex.Button Button12
            {
                get
                {
                    return _button12Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button12 item info.
            /// </summary>
            [RepositoryItemInfo("e6f94270-8127-4d9c-a6a6-85d8c5677087")]
            public virtual RepoItemInfo Button12Info
            {
                get
                {
                    return _button12Info;
                }
            }

            /// <summary>
            /// The Button8 item.
            /// </summary>
            [RepositoryItem("78b8cbdd-7c5a-4b48-8869-d7791b0c54a3")]
            public virtual Ranorex.Button Button8
            {
                get
                {
                    return _button8Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button8 item info.
            /// </summary>
            [RepositoryItemInfo("78b8cbdd-7c5a-4b48-8869-d7791b0c54a3")]
            public virtual RepoItemInfo Button8Info
            {
                get
                {
                    return _button8Info;
                }
            }

            /// <summary>
            /// The Button7 item.
            /// </summary>
            [RepositoryItem("66610eb6-4df1-4920-ad91-fe9018c531f0")]
            public virtual Ranorex.Button Button7
            {
                get
                {
                    return _button7Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button7 item info.
            /// </summary>
            [RepositoryItemInfo("66610eb6-4df1-4920-ad91-fe9018c531f0")]
            public virtual RepoItemInfo Button7Info
            {
                get
                {
                    return _button7Info;
                }
            }

            /// <summary>
            /// The Button6 item.
            /// </summary>
            [RepositoryItem("b8972015-19de-4077-b45b-d2a217c58665")]
            public virtual Ranorex.Button Button6
            {
                get
                {
                    return _button6Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button6 item info.
            /// </summary>
            [RepositoryItemInfo("b8972015-19de-4077-b45b-d2a217c58665")]
            public virtual RepoItemInfo Button6Info
            {
                get
                {
                    return _button6Info;
                }
            }

            /// <summary>
            /// The Button5 item.
            /// </summary>
            [RepositoryItem("b51e7166-a7da-4bfe-8113-3925104e9f14")]
            public virtual Ranorex.Button Button5
            {
                get
                {
                    return _button5Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button5 item info.
            /// </summary>
            [RepositoryItemInfo("b51e7166-a7da-4bfe-8113-3925104e9f14")]
            public virtual RepoItemInfo Button5Info
            {
                get
                {
                    return _button5Info;
                }
            }

            /// <summary>
            /// The Button26 item.
            /// </summary>
            [RepositoryItem("ca0505c8-914b-4540-9f9f-67dd584a15b2")]
            public virtual Ranorex.Button Button26
            {
                get
                {
                    return _button26Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button26 item info.
            /// </summary>
            [RepositoryItemInfo("ca0505c8-914b-4540-9f9f-67dd584a15b2")]
            public virtual RepoItemInfo Button26Info
            {
                get
                {
                    return _button26Info;
                }
            }

            /// <summary>
            /// The Button13 item.
            /// </summary>
            [RepositoryItem("b846f02e-bddd-408e-8dc4-e0d77683e5c9")]
            public virtual Ranorex.Button Button13
            {
                get
                {
                    return _button13Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button13 item info.
            /// </summary>
            [RepositoryItemInfo("b846f02e-bddd-408e-8dc4-e0d77683e5c9")]
            public virtual RepoItemInfo Button13Info
            {
                get
                {
                    return _button13Info;
                }
            }

            /// <summary>
            /// The Button18 item.
            /// </summary>
            [RepositoryItem("9ff8f4d5-4e26-45b3-94e5-0def007918fb")]
            public virtual Ranorex.Button Button18
            {
                get
                {
                    return _button18Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button18 item info.
            /// </summary>
            [RepositoryItemInfo("9ff8f4d5-4e26-45b3-94e5-0def007918fb")]
            public virtual RepoItemInfo Button18Info
            {
                get
                {
                    return _button18Info;
                }
            }

            /// <summary>
            /// The Button27 item.
            /// </summary>
            [RepositoryItem("804fc7f5-d4f6-4877-bb6d-7862dc8f42f0")]
            public virtual Ranorex.Button Button27
            {
                get
                {
                    return _button27Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button27 item info.
            /// </summary>
            [RepositoryItemInfo("804fc7f5-d4f6-4877-bb6d-7862dc8f42f0")]
            public virtual RepoItemInfo Button27Info
            {
                get
                {
                    return _button27Info;
                }
            }

            /// <summary>
            /// The Button23 item.
            /// </summary>
            [RepositoryItem("5bc3a93c-81c0-40d8-9db7-0aaa2485c60d")]
            public virtual Ranorex.Button Button23
            {
                get
                {
                    return _button23Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button23 item info.
            /// </summary>
            [RepositoryItemInfo("5bc3a93c-81c0-40d8-9db7-0aaa2485c60d")]
            public virtual RepoItemInfo Button23Info
            {
                get
                {
                    return _button23Info;
                }
            }
        }

    }
#pragma warning restore 0436
}