///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace dubeer
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The accountcreation_Plusdap recording.
    /// </summary>
    [TestModule("6debea54-f1ac-4017-81f1-41a241eaaa81", ModuleType.Recording, 1)]
    public partial class accountcreation__dap : ITestModule
    {
        /// <summary>
        /// Holds an instance of the dubeerRepository repository.
        /// </summary>
        public static dubeerRepository repo = dubeerRepository.Instance;

        static accountcreation__dap instance = new accountcreation__dap();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public accountcreation__dap()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static accountcreation__dap Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://tigers.dubber.net/login' with browser 'Safari' in normal mode.", new RecordItemIndex(0));
            Host.Local.OpenBrowser("https://tigers.dubber.net/login", "Safari", "", false, false, false, false, false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber.Daps' at 19;8.", repo.DubberMozillaFirefox.Dubber.DapsInfo, new RecordItemIndex(1));
            repo.DubberMozillaFirefox.Dubber.Daps.Click("19;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber1.EmailAddress' at 177;18.", repo.DubberMozillaFirefox.Dubber1.EmailAddressInfo, new RecordItemIndex(2));
            repo.DubberMozillaFirefox.Dubber1.EmailAddress.Click("177;18");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber1.Password' at 161;16.", repo.DubberMozillaFirefox.Dubber1.PasswordInfo, new RecordItemIndex(3));
            repo.DubberMozillaFirefox.Dubber1.Password.Click("161;16");
            Delay.Milliseconds(200);
            
            Mouse_Click_Login();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber.TextAddDap' at 16;0.", repo.DubberMozillaFirefox.Dubber.TextAddDapInfo, new RecordItemIndex(5));
            repo.DubberMozillaFirefox.Dubber.TextAddDap.Click("16;0");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber1.RequiredArea' at 205;12.", repo.DubberMozillaFirefox.Dubber1.RequiredAreaInfo, new RecordItemIndex(6));
            repo.DubberMozillaFirefox.Dubber1.RequiredArea.Click("205;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'Dropdown' at 535;29.", repo.Dropdown.SelfInfo, new RecordItemIndex(7));
            repo.Dropdown.Self.MoveTo("535;29");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dropdown' at 428;387.", repo.Dropdown.SelfInfo, new RecordItemIndex(8));
            repo.Dropdown.Self.Click("428;387");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber1.RequiredArea1' at 42;15.", repo.DubberMozillaFirefox.Dubber1.RequiredArea1Info, new RecordItemIndex(9));
            repo.DubberMozillaFirefox.Dubber1.RequiredArea1.Click("42;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'yyyy' with focus on 'DubberMozillaFirefox.Dubber1.RequiredArea1'.", repo.DubberMozillaFirefox.Dubber1.RequiredArea1Info, new RecordItemIndex(10));
            repo.DubberMozillaFirefox.Dubber1.RequiredArea1.PressKeys("yyyy");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.State' at 79;14.", repo.DubberMozillaFirefox.StateInfo, new RecordItemIndex(11));
            repo.DubberMozillaFirefox.State.Click("79;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'wsa' with focus on 'DubberMozillaFirefox.State'.", repo.DubberMozillaFirefox.StateInfo, new RecordItemIndex(12));
            repo.DubberMozillaFirefox.State.PressKeys("wsa");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.ComboBox' at 163;14.", repo.DubberMozillaFirefox.ComboBoxInfo, new RecordItemIndex(13));
            repo.DubberMozillaFirefox.ComboBox.Click("163;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dropdown' at 73;151.", repo.Dropdown.SelfInfo, new RecordItemIndex(14));
            repo.Dropdown.Self.Click("73;151");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber1.TextSaveChanges' at 35;7.", repo.DubberMozillaFirefox.Dubber1.TextSaveChangesInfo, new RecordItemIndex(15));
            repo.DubberMozillaFirefox.Dubber1.TextSaveChanges.Click("35;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber1.ComboBox1' at 35;10.", repo.DubberMozillaFirefox.Dubber1.ComboBox1Info, new RecordItemIndex(16));
            repo.DubberMozillaFirefox.Dubber1.ComboBox1.Click("35;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dropdown' at 14;62.", repo.Dropdown.SelfInfo, new RecordItemIndex(17));
            repo.Dropdown.Self.Click("14;62");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber1.Text' at 21;14.", repo.DubberMozillaFirefox.Dubber1.TextInfo, new RecordItemIndex(18));
            repo.DubberMozillaFirefox.Dubber1.Text.Click("21;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '76767675' with focus on 'DubberMozillaFirefox.Dubber1.Text'.", repo.DubberMozillaFirefox.Dubber1.TextInfo, new RecordItemIndex(19));
            repo.DubberMozillaFirefox.Dubber1.Text.PressKeys("76767675");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber1.ComboBox2' at 38;10.", repo.DubberMozillaFirefox.Dubber1.ComboBox2Info, new RecordItemIndex(20));
            repo.DubberMozillaFirefox.Dubber1.ComboBox2.Click("38;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dropdown' at 17;67.", repo.Dropdown.SelfInfo, new RecordItemIndex(21));
            repo.Dropdown.Self.Click("17;67");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber1.Text1' at 16;12.", repo.DubberMozillaFirefox.Dubber1.Text1Info, new RecordItemIndex(22));
            repo.DubberMozillaFirefox.Dubber1.Text1.Click("16;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '76767675' with focus on 'DubberMozillaFirefox.Dubber1.Text1'.", repo.DubberMozillaFirefox.Dubber1.Text1Info, new RecordItemIndex(23));
            repo.DubberMozillaFirefox.Dubber1.Text1.PressKeys("76767675");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber1.None3' at 655;167.", repo.DubberMozillaFirefox.Dubber1.None3Info, new RecordItemIndex(24));
            repo.DubberMozillaFirefox.Dubber1.None3.Click("655;167");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber1.None2' at 495;110.", repo.DubberMozillaFirefox.Dubber1.None2Info, new RecordItemIndex(25));
            repo.DubberMozillaFirefox.Dubber1.None2.Click("495;110");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber1.TextConfirm' at 25;5.", repo.DubberMozillaFirefox.Dubber1.TextConfirmInfo, new RecordItemIndex(26));
            repo.DubberMozillaFirefox.Dubber1.TextConfirm.Click("25;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber.Accounts' at 48;9.", repo.DubberMozillaFirefox.Dubber.AccountsInfo, new RecordItemIndex(27));
            repo.DubberMozillaFirefox.Dubber.Accounts.Click("48;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber1.TextAddAccount' at 56;6.", repo.DubberMozillaFirefox.Dubber1.TextAddAccountInfo, new RecordItemIndex(28));
            repo.DubberMozillaFirefox.Dubber1.TextAddAccount.Click("56;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber1.RequiredName' at 40;16.", repo.DubberMozillaFirefox.Dubber1.RequiredNameInfo, new RecordItemIndex(29));
            repo.DubberMozillaFirefox.Dubber1.RequiredName.Click("40;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'dfs' with focus on 'DubberMozillaFirefox.Dubber1.RequiredName'.", repo.DubberMozillaFirefox.Dubber1.RequiredNameInfo, new RecordItemIndex(30));
            repo.DubberMozillaFirefox.Dubber1.RequiredName.PressKeys("dfs");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber1.RequiredWebAddress' at 46;9.", repo.DubberMozillaFirefox.Dubber1.RequiredWebAddressInfo, new RecordItemIndex(31));
            repo.DubberMozillaFirefox.Dubber1.RequiredWebAddress.Click("46;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'tree' with focus on 'DubberMozillaFirefox.Dubber1.RequiredWebAddress'.", repo.DubberMozillaFirefox.Dubber1.RequiredWebAddressInfo, new RecordItemIndex(32));
            repo.DubberMozillaFirefox.Dubber1.RequiredWebAddress.PressKeys("tree");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber1.ExternalReference' at 129;7.", repo.DubberMozillaFirefox.Dubber1.ExternalReferenceInfo, new RecordItemIndex(33));
            repo.DubberMozillaFirefox.Dubber1.ExternalReference.Click("129;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'yhnng' with focus on 'DubberMozillaFirefox.Dubber1.ExternalReference'.", repo.DubberMozillaFirefox.Dubber1.ExternalReferenceInfo, new RecordItemIndex(34));
            repo.DubberMozillaFirefox.Dubber1.ExternalReference.PressKeys("yhnng");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber1.RequiredAccountTimeZone' at 103;14.", repo.DubberMozillaFirefox.Dubber1.RequiredAccountTimeZoneInfo, new RecordItemIndex(35));
            repo.DubberMozillaFirefox.Dubber1.RequiredAccountTimeZone.Click("103;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dropdown' at 124;341.", repo.Dropdown.SelfInfo, new RecordItemIndex(36));
            repo.Dropdown.Self.Click("124;341");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber1.RequiredAddress' at 103;9.", repo.DubberMozillaFirefox.Dubber1.RequiredAddressInfo, new RecordItemIndex(37));
            repo.DubberMozillaFirefox.Dubber1.RequiredAddress.Click("103;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'tr' with focus on 'DubberMozillaFirefox.Dubber1.RequiredAddress'.", repo.DubberMozillaFirefox.Dubber1.RequiredAddressInfo, new RecordItemIndex(38));
            repo.DubberMozillaFirefox.Dubber1.RequiredAddress.PressKeys("tr");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber1.Text' at 80;10.", repo.DubberMozillaFirefox.Dubber1.TextInfo, new RecordItemIndex(39));
            repo.DubberMozillaFirefox.Dubber1.Text.Click("80;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'khh' with focus on 'DubberMozillaFirefox.Dubber1.Text'.", repo.DubberMozillaFirefox.Dubber1.TextInfo, new RecordItemIndex(40));
            repo.DubberMozillaFirefox.Dubber1.Text.PressKeys("khh");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber1.ComboBox2' at 82;18.", repo.DubberMozillaFirefox.Dubber1.ComboBox2Info, new RecordItemIndex(41));
            repo.DubberMozillaFirefox.Dubber1.ComboBox2.Click("82;18");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dropdown' at 65;180.", repo.Dropdown.SelfInfo, new RecordItemIndex(42));
            repo.Dropdown.Self.Click("65;180");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber1.ComboBox2' at 185;10.", repo.DubberMozillaFirefox.Dubber1.ComboBox2Info, new RecordItemIndex(43));
            repo.DubberMozillaFirefox.Dubber1.ComboBox2.Click("185;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dropdown' at 51;37.", repo.Dropdown.SelfInfo, new RecordItemIndex(44));
            repo.Dropdown.Self.Click("51;37");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'DubberMozillaFirefox.None' at 1355;267.", repo.DubberMozillaFirefox.NoneInfo, new RecordItemIndex(45));
            repo.DubberMozillaFirefox.None.MoveTo("1355;267");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'DubberMozillaFirefox.None' at 1359;454.", repo.DubberMozillaFirefox.NoneInfo, new RecordItemIndex(46));
            repo.DubberMozillaFirefox.None.MoveTo("1359;454");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber1.Postcode' at 68;8.", repo.DubberMozillaFirefox.Dubber1.PostcodeInfo, new RecordItemIndex(47));
            repo.DubberMozillaFirefox.Dubber1.Postcode.Click("68;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1234' with focus on 'DubberMozillaFirefox.Dubber1.Postcode'.", repo.DubberMozillaFirefox.Dubber1.PostcodeInfo, new RecordItemIndex(48));
            repo.DubberMozillaFirefox.Dubber1.Postcode.PressKeys("1234");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber1.ComboBox' at 36;11.", repo.DubberMozillaFirefox.Dubber1.ComboBoxInfo, new RecordItemIndex(49));
            repo.DubberMozillaFirefox.Dubber1.ComboBox.Click("36;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dropdown' at 31;68.", repo.Dropdown.SelfInfo, new RecordItemIndex(50));
            repo.Dropdown.Self.Click("31;68");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber1.Text2' at 13;11.", repo.DubberMozillaFirefox.Dubber1.Text2Info, new RecordItemIndex(51));
            repo.DubberMozillaFirefox.Dubber1.Text2.Click("13;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '34343435' with focus on 'DubberMozillaFirefox.Dubber1.Text2'.", repo.DubberMozillaFirefox.Dubber1.Text2Info, new RecordItemIndex(52));
            repo.DubberMozillaFirefox.Dubber1.Text2.PressKeys("34343435");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber1.RequiredUsername' at 72;10.", repo.DubberMozillaFirefox.Dubber1.RequiredUsernameInfo, new RecordItemIndex(53));
            repo.DubberMozillaFirefox.Dubber1.RequiredUsername.Click("72;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'f' with focus on 'DubberMozillaFirefox.Dubber1.RequiredUsername'.", repo.DubberMozillaFirefox.Dubber1.RequiredUsernameInfo, new RecordItemIndex(54));
            repo.DubberMozillaFirefox.Dubber1.RequiredUsername.PressKeys("f");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{RShiftKey down}@{RShiftKey up}er.com' with focus on 'DubberMozillaFirefox.Dubber1.RequiredUsername'.", repo.DubberMozillaFirefox.Dubber1.RequiredUsernameInfo, new RecordItemIndex(55));
            repo.DubberMozillaFirefox.Dubber1.RequiredUsername.PressKeys("{RShiftKey down}@{RShiftKey up}er.com");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'DubberMozillaFirefox.None' at 1357;425.", repo.DubberMozillaFirefox.NoneInfo, new RecordItemIndex(56));
            repo.DubberMozillaFirefox.None.MoveTo("1357;425");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber1.RequiredVerifyUsername' at 18;11.", repo.DubberMozillaFirefox.Dubber1.RequiredVerifyUsernameInfo, new RecordItemIndex(57));
            repo.DubberMozillaFirefox.Dubber1.RequiredVerifyUsername.Click("18;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'f{RShiftKey down}@{RShiftKey up}er.com' with focus on 'DubberMozillaFirefox.Dubber1.RequiredVerifyUsername'.", repo.DubberMozillaFirefox.Dubber1.RequiredVerifyUsernameInfo, new RecordItemIndex(58));
            repo.DubberMozillaFirefox.Dubber1.RequiredVerifyUsername.PressKeys("f{RShiftKey down}@{RShiftKey up}er.com");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber1.RequiredName1' at 54;15.", repo.DubberMozillaFirefox.Dubber1.RequiredName1Info, new RecordItemIndex(59));
            repo.DubberMozillaFirefox.Dubber1.RequiredName1.Click("54;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'swa' with focus on 'DubberMozillaFirefox.Dubber1.RequiredName1'.", repo.DubberMozillaFirefox.Dubber1.RequiredName1Info, new RecordItemIndex(60));
            repo.DubberMozillaFirefox.Dubber1.RequiredName1.PressKeys("swa");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber1.LastName' at 20;16.", repo.DubberMozillaFirefox.Dubber1.LastNameInfo, new RecordItemIndex(61));
            repo.DubberMozillaFirefox.Dubber1.LastName.Click("20;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'sde' with focus on 'DubberMozillaFirefox.Dubber1.LastName'.", repo.DubberMozillaFirefox.Dubber1.LastNameInfo, new RecordItemIndex(62));
            repo.DubberMozillaFirefox.Dubber1.LastName.PressKeys("sde");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber.TextSaveChanges' at 42;8.", repo.DubberMozillaFirefox.Dubber.TextSaveChangesInfo, new RecordItemIndex(63));
            repo.DubberMozillaFirefox.Dubber.TextSaveChanges.Click("42;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber1.RequiredName' at 72;17.", repo.DubberMozillaFirefox.Dubber1.RequiredNameInfo, new RecordItemIndex(64));
            repo.DubberMozillaFirefox.Dubber1.RequiredName.Click("72;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'dsdasda' with focus on 'DubberMozillaFirefox.Dubber1.RequiredName'.", repo.DubberMozillaFirefox.Dubber1.RequiredNameInfo, new RecordItemIndex(65));
            repo.DubberMozillaFirefox.Dubber1.RequiredName.PressKeys("dsdasda");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'DubberMozillaFirefox.None' at 1357;266.", repo.DubberMozillaFirefox.NoneInfo, new RecordItemIndex(66));
            repo.DubberMozillaFirefox.None.MoveTo("1357;266");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'DubberMozillaFirefox.None' at 1362;639.", repo.DubberMozillaFirefox.NoneInfo, new RecordItemIndex(67));
            repo.DubberMozillaFirefox.None.MoveTo("1362;639");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber.TextSaveChanges' at 35;1.", repo.DubberMozillaFirefox.Dubber.TextSaveChangesInfo, new RecordItemIndex(68));
            repo.DubberMozillaFirefox.Dubber.TextSaveChanges.Click("35;1");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber1.RequiredInboundLocation' at 152;13.", repo.DubberMozillaFirefox.Dubber1.RequiredInboundLocationInfo, new RecordItemIndex(69));
            repo.DubberMozillaFirefox.Dubber1.RequiredInboundLocation.Click("152;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'Dropdown' at 271;30.", repo.Dropdown.SelfInfo, new RecordItemIndex(70));
            repo.Dropdown.Self.MoveTo("271;30");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'Dropdown' at 256;381.", repo.Dropdown.SelfInfo, new RecordItemIndex(71));
            repo.Dropdown.Self.MoveTo("256;381");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dropdown' at 181;390.", repo.Dropdown.SelfInfo, new RecordItemIndex(72));
            repo.Dropdown.Self.Click("181;390");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber1.DubberAccessPoint' at 150;14.", repo.DubberMozillaFirefox.Dubber1.DubberAccessPointInfo, new RecordItemIndex(73));
            repo.DubberMozillaFirefox.Dubber1.DubberAccessPoint.Click("150;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dropdown' at 117;23.", repo.Dropdown.SelfInfo, new RecordItemIndex(74));
            repo.Dropdown.Self.Click("117;23");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber1.ComboBox3' at 36;6.", repo.DubberMozillaFirefox.Dubber1.ComboBox3Info, new RecordItemIndex(75));
            repo.DubberMozillaFirefox.Dubber1.ComboBox3.Click("36;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dropdown' at 26;52.", repo.Dropdown.SelfInfo, new RecordItemIndex(76));
            repo.Dropdown.Self.Click("26;52");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber1.Text3' at 33;10.", repo.DubberMozillaFirefox.Dubber1.Text3Info, new RecordItemIndex(77));
            repo.DubberMozillaFirefox.Dubber1.Text3.Click("33;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber1.ComboBox3' at 42;12.", repo.DubberMozillaFirefox.Dubber1.ComboBox3Info, new RecordItemIndex(78));
            repo.DubberMozillaFirefox.Dubber1.ComboBox3.Click("42;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dropdown' at 28;71.", repo.Dropdown.SelfInfo, new RecordItemIndex(79));
            repo.Dropdown.Self.Click("28;71");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber1.Text3' at 7;19.", repo.DubberMozillaFirefox.Dubber1.Text3Info, new RecordItemIndex(80));
            repo.DubberMozillaFirefox.Dubber1.Text3.Click("7;19");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '67676867' with focus on 'DubberMozillaFirefox.Dubber1.Text3'.", repo.DubberMozillaFirefox.Dubber1.Text3Info, new RecordItemIndex(81));
            repo.DubberMozillaFirefox.Dubber1.Text3.PressKeys("67676867");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber1.RequiredLabel' at 65;22.", repo.DubberMozillaFirefox.Dubber1.RequiredLabelInfo, new RecordItemIndex(82));
            repo.DubberMozillaFirefox.Dubber1.RequiredLabel.Click("65;22");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'rtre' with focus on 'DubberMozillaFirefox.Dubber1.RequiredLabel'.", repo.DubberMozillaFirefox.Dubber1.RequiredLabelInfo, new RecordItemIndex(83));
            repo.DubberMozillaFirefox.Dubber1.RequiredLabel.PressKeys("rtre");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber1.ComboBox4' at 39;9.", repo.DubberMozillaFirefox.Dubber1.ComboBox4Info, new RecordItemIndex(84));
            repo.DubberMozillaFirefox.Dubber1.ComboBox4.Click("39;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dropdown' at 1;64.", repo.Dropdown.SelfInfo, new RecordItemIndex(85));
            repo.Dropdown.Self.Click("1;64");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dropdown' at 19;68.", repo.Dropdown.SelfInfo, new RecordItemIndex(86));
            repo.Dropdown.Self.Click("19;68");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber1.Text4' at 22;10.", repo.DubberMozillaFirefox.Dubber1.Text4Info, new RecordItemIndex(87));
            repo.DubberMozillaFirefox.Dubber1.Text4.Click("22;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '65646564' with focus on 'DubberMozillaFirefox.Dubber1.Text4'.", repo.DubberMozillaFirefox.Dubber1.Text4Info, new RecordItemIndex(88));
            repo.DubberMozillaFirefox.Dubber1.Text4.PressKeys("65646564");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber1.RequiredLabel1' at 32;20.", repo.DubberMozillaFirefox.Dubber1.RequiredLabel1Info, new RecordItemIndex(89));
            repo.DubberMozillaFirefox.Dubber1.RequiredLabel1.Click("32;20");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'lokj' with focus on 'DubberMozillaFirefox.Dubber1.RequiredLabel1'.", repo.DubberMozillaFirefox.Dubber1.RequiredLabel1Info, new RecordItemIndex(90));
            repo.DubberMozillaFirefox.Dubber1.RequiredLabel1.PressKeys("lokj");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber.TextSaveChanges1' at 12;0.", repo.DubberMozillaFirefox.Dubber.TextSaveChanges1Info, new RecordItemIndex(91));
            repo.DubberMozillaFirefox.Dubber.TextSaveChanges1.Click("12;0");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber.Inbound' at 13;2.", repo.DubberMozillaFirefox.Dubber.InboundInfo, new RecordItemIndex(92));
            repo.DubberMozillaFirefox.Dubber.Inbound.Click("13;2");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber.Rtre' at 17;10.", repo.DubberMozillaFirefox.Dubber.RtreInfo, new RecordItemIndex(93));
            repo.DubberMozillaFirefox.Dubber.Rtre.Click("17;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'DubberMozillaFirefox.None' at 1353;299.", repo.DubberMozillaFirefox.NoneInfo, new RecordItemIndex(94));
            repo.DubberMozillaFirefox.None.MoveTo("1353;299");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'DubberMozillaFirefox.None' at 1365;626.", repo.DubberMozillaFirefox.NoneInfo, new RecordItemIndex(95));
            repo.DubberMozillaFirefox.None.MoveTo("1365;626");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'DubberMozillaFirefox.Dubber1.None4' at 730;231.", repo.DubberMozillaFirefox.Dubber1.None4Info, new RecordItemIndex(96));
            repo.DubberMozillaFirefox.Dubber1.None4.MoveTo("730;231");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'DubberMozillaFirefox.Dubber1.None4' at 715;403.", repo.DubberMozillaFirefox.Dubber1.None4Info, new RecordItemIndex(97));
            repo.DubberMozillaFirefox.Dubber1.None4.MoveTo("715;403");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber1.TextDownloadCallflow' at 112;10.", repo.DubberMozillaFirefox.Dubber1.TextDownloadCallflowInfo, new RecordItemIndex(98));
            repo.DubberMozillaFirefox.Dubber1.TextDownloadCallflow.Click("112;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'DubberMozillaFirefox.None' at 1352;477.", repo.DubberMozillaFirefox.NoneInfo, new RecordItemIndex(99));
            repo.DubberMozillaFirefox.None.MoveTo("1352;477");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'DubberMozillaFirefox.None' at 1362;280.", repo.DubberMozillaFirefox.NoneInfo, new RecordItemIndex(100));
            repo.DubberMozillaFirefox.None.MoveTo("1362;280");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Downloads' at 14;21.", repo.DubberMozillaFirefox.DownloadsInfo, new RecordItemIndex(101));
            repo.DubberMozillaFirefox.Downloads.Click("14;21");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dropdown' at 374;55.", repo.Dropdown.SelfInfo, new RecordItemIndex(102));
            repo.Dropdown.Self.Click("374;55");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'Downloads.SystemItemNameDisplay' at 60;6.", repo.Downloads.SystemItemNameDisplayInfo, new RecordItemIndex(103));
            repo.Downloads.SystemItemNameDisplay.DoubleClick("60;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Downloads.Close' at 33;8.", repo.Downloads.CloseInfo, new RecordItemIndex(104));
            repo.Downloads.Close.Click("33;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber1.Browse' at 50;10.", repo.DubberMozillaFirefox.Dubber1.BrowseInfo, new RecordItemIndex(105));
            repo.DubberMozillaFirefox.Dubber1.Browse.Click("50;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FileUpload.Text1148' at 107;4.", repo.FileUpload.Text1148Info, new RecordItemIndex(106));
            repo.FileUpload.Text1148.Click("107;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'rt' with focus on 'FileUpload.Text1148'.", repo.FileUpload.Text1148Info, new RecordItemIndex(107));
            repo.FileUpload.Text1148.PressKeys("rt");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 're' with focus on 'FileUpload.Text1148'.", repo.FileUpload.Text1148Info, new RecordItemIndex(108));
            repo.FileUpload.Text1148.PressKeys("re");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '-' with focus on 'FileUpload.Text1148'.", repo.FileUpload.Text1148Info, new RecordItemIndex(109));
            repo.FileUpload.Text1148.PressKeys("-");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Capital}C{Capital}allflo' with focus on 'FileUpload.Text1148'.", repo.FileUpload.Text1148Info, new RecordItemIndex(110));
            repo.FileUpload.Text1148.PressKeys("{Capital}C{Capital}allflo");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'w.xml' with focus on 'FileUpload.Text1148'.", repo.FileUpload.Text1148Info, new RecordItemIndex(111));
            repo.FileUpload.Text1148.PressKeys("w.xml");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FileUpload.ButtonOpen' at 59;7.", repo.FileUpload.ButtonOpenInfo, new RecordItemIndex(112));
            repo.FileUpload.ButtonOpen.Click("59;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber1.TextUpload' at 47;11.", repo.DubberMozillaFirefox.Dubber1.TextUploadInfo, new RecordItemIndex(113));
            repo.DubberMozillaFirefox.Dubber1.TextUpload.Click("47;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'DubberMozillaFirefox.None' at 1358;330.", repo.DubberMozillaFirefox.NoneInfo, new RecordItemIndex(114));
            repo.DubberMozillaFirefox.None.MoveTo("1358;330");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'DubberMozillaFirefox.Dubber1.None4' at 735;227.", repo.DubberMozillaFirefox.Dubber1.None4Info, new RecordItemIndex(115));
            repo.DubberMozillaFirefox.Dubber1.None4.MoveTo("735;227");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'DubberMozillaFirefox.Dubber1.None4' at 743;219.", repo.DubberMozillaFirefox.Dubber1.None4Info, new RecordItemIndex(116));
            repo.DubberMozillaFirefox.Dubber1.None4.MoveTo("743;219");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'DubberMozillaFirefox.Dubber1.None1' at 704;590.", repo.DubberMozillaFirefox.Dubber1.None1Info, new RecordItemIndex(117));
            repo.DubberMozillaFirefox.Dubber1.None1.MoveTo("704;590");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber.TextSaveChanges2' at 62;7.", repo.DubberMozillaFirefox.Dubber.TextSaveChanges2Info, new RecordItemIndex(118));
            repo.DubberMozillaFirefox.Dubber.TextSaveChanges2.Click("62;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber.Link' at 35;9.", repo.DubberMozillaFirefox.Dubber.LinkInfo, new RecordItemIndex(119));
            repo.DubberMozillaFirefox.Dubber.Link.Click("35;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber.TextLogout' at 38;5.", repo.DubberMozillaFirefox.Dubber.TextLogoutInfo, new RecordItemIndex(120));
            repo.DubberMozillaFirefox.Dubber.TextLogout.Click("38;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.BrowserTabs' at 1363;0.", repo.DubberMozillaFirefox.BrowserTabsInfo, new RecordItemIndex(121));
            repo.DubberMozillaFirefox.BrowserTabs.Click("1363;0");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
