///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace dubeer
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The comparing recording.
    /// </summary>
    [TestModule("a87eacba-200d-429a-8847-4cd87152b325", ModuleType.Recording, 1)]
    public partial class comparing : ITestModule
    {
        /// <summary>
        /// Holds an instance of the dubeerRepository repository.
        /// </summary>
        public static dubeerRepository repo = dubeerRepository.Instance;

        static comparing instance = new comparing();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public comparing()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static comparing Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dubber.InboundNumberLabelInb' at 18;7.", repo.Dubber.InboundNumberLabelInbInfo, new RecordItemIndex(0));
            repo.Dubber.InboundNumberLabelInb.Click("18;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'Dubber' at 1359;308.", repo.Dubber.SelfInfo, new RecordItemIndex(1));
            repo.Dubber.Self.MoveTo("1359;308");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'Dubber' at 1365;612.", repo.Dubber.SelfInfo, new RecordItemIndex(2));
            repo.Dubber.Self.MoveTo("1365;612");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse None Move item 'Dubber' at 1362;609.", repo.Dubber.SelfInfo, new RecordItemIndex(3));
            repo.Dubber.Self.MoveTo("1362;609");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'Dubber.CallflowXmlWell' at 728;234.", repo.Dubber.CallflowXmlWellInfo, new RecordItemIndex(4));
            repo.Dubber.CallflowXmlWell.MoveTo("728;234");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'Dubber.CallflowXmlWell' at 733;384.", repo.Dubber.CallflowXmlWellInfo, new RecordItemIndex(5));
            repo.Dubber.CallflowXmlWell.MoveTo("733;384");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Mouse_Click_DownloadCallflow();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
