///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace dubeer
{
    public partial class dap_creation
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void Mouse_Click_TextInb()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber.TextInb' at 14;9.", repo.DubberMozillaFirefox.Dubber.TextInbInfo);
            repo.DubberMozillaFirefox.Dubber.TextInb.Click("14;9");
            Thread.Sleep(5000);
        }

        public void Mouse_Click_Link()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber.Link' at 34;18.", repo.DubberMozillaFirefox.Dubber.LinkInfo);
            repo.DubberMozillaFirefox.Dubber.Link.Click("34;18");
        }

        public void Mouse_Click_Logout()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber.Logout' at 92;5.", repo.DubberMozillaFirefox.Dubber.LogoutInfo);
            repo.DubberMozillaFirefox.Dubber.Logout.Click("92;5");
        }

    }
}