///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace dubeer
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The dap_creation recording.
    /// </summary>
    [TestModule("5d07c68b-e396-4e4b-b94c-ca44ed6065a5", ModuleType.Recording, 1)]
    public partial class dap_creation : ITestModule
    {
        /// <summary>
        /// Holds an instance of the dubeerRepository repository.
        /// </summary>
        public static dubeerRepository repo = dubeerRepository.Instance;

        static dap_creation instance = new dap_creation();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public dap_creation()
        {
            area = "fe";
            state = "senttt";
            start_end = "4444";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static dap_creation Instance
        {
            get { return instance; }
        }

#region Variables

        string _area;

        /// <summary>
        /// Gets or sets the value of variable area.
        /// </summary>
        [TestVariable("2e18f64f-ea1d-4161-9122-ffae9351b625")]
        public string area
        {
            get { return _area; }
            set { _area = value; }
        }

        string _state;

        /// <summary>
        /// Gets or sets the value of variable state.
        /// </summary>
        [TestVariable("b5f0ff0c-3ce7-49d3-b85a-e2c483e11ff7")]
        public string state
        {
            get { return _state; }
            set { _state = value; }
        }

        string _start_end;

        /// <summary>
        /// Gets or sets the value of variable start_end.
        /// </summary>
        [TestVariable("ee1162ee-b015-413c-b164-9e23996fe8e9")]
        public string start_end
        {
            get { return _start_end; }
            set { _start_end = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://tigers.dubber.net/login' with browser 'firefox' in normal mode.", new RecordItemIndex(0));
            Host.Local.OpenBrowser("https://tigers.dubber.net/login", "firefox", "", false, false, false, false, false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber1.EmailAddress' at 153;15.", repo.DubberMozillaFirefox.Dubber1.EmailAddressInfo, new RecordItemIndex(1));
            repo.DubberMozillaFirefox.Dubber1.EmailAddress.Click("153;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber1.Password' at 121;20.", repo.DubberMozillaFirefox.Dubber1.PasswordInfo, new RecordItemIndex(2));
            repo.DubberMozillaFirefox.Dubber1.Password.Click("121;20");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber1.Login' at 42;8.", repo.DubberMozillaFirefox.Dubber1.LoginInfo, new RecordItemIndex(3));
            repo.DubberMozillaFirefox.Dubber1.Login.Click("42;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber.Search' at 46;12.", repo.DubberMozillaFirefox.Dubber.SearchInfo, new RecordItemIndex(4));
            repo.DubberMozillaFirefox.Dubber.Search.Click("46;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'testcomplete2{Return}' with focus on 'DubberMozillaFirefox.Dubber.Search'.", repo.DubberMozillaFirefox.Dubber.SearchInfo, new RecordItemIndex(5));
            repo.DubberMozillaFirefox.Dubber.Search.PressKeys("testcomplete2{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber.Testcomplete2' at 70;13.", repo.DubberMozillaFirefox.Dubber.Testcomplete2Info, new RecordItemIndex(6));
            repo.DubberMozillaFirefox.Dubber.Testcomplete2.Click("70;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber.Inbound' at 27;14.", repo.DubberMozillaFirefox.Dubber.InboundInfo, new RecordItemIndex(7));
            repo.DubberMozillaFirefox.Dubber.Inbound.Click("27;14");
            Delay.Milliseconds(200);
            
            Mouse_Click_TextInb();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'DubberMozillaFirefox.None' at 1353;215.", repo.DubberMozillaFirefox.NoneInfo, new RecordItemIndex(9));
            repo.DubberMozillaFirefox.None.MoveTo("1353;215");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'DubberMozillaFirefox.None' at 1352;533.", repo.DubberMozillaFirefox.NoneInfo, new RecordItemIndex(10));
            repo.DubberMozillaFirefox.None.MoveTo("1352;533");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber1.TextDownloadCallflow' at 93;10.", repo.DubberMozillaFirefox.Dubber1.TextDownloadCallflowInfo, new RecordItemIndex(11));
            repo.DubberMozillaFirefox.Dubber1.TextDownloadCallflow.Click("93;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Downloads' at 18;16.", repo.DubberMozillaFirefox.DownloadsInfo, new RecordItemIndex(12));
            repo.DubberMozillaFirefox.Downloads.Click("18;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dropdown' at 378;51.", repo.Dropdown.SelfInfo, new RecordItemIndex(13));
            repo.Dropdown.Self.Click("378;51");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'DubberMozillaFirefox.None' at 1357;468.", repo.DubberMozillaFirefox.NoneInfo, new RecordItemIndex(14));
            repo.DubberMozillaFirefox.None.MoveTo("1357;468");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'DubberMozillaFirefox.None' at 1361;319.", repo.DubberMozillaFirefox.NoneInfo, new RecordItemIndex(15));
            repo.DubberMozillaFirefox.None.MoveTo("1361;319");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber1.Browse' at 49;5.", repo.DubberMozillaFirefox.Dubber1.BrowseInfo, new RecordItemIndex(16));
            repo.DubberMozillaFirefox.Dubber1.Browse.Click("49;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'FileUpload.SystemItemNameDisplay' at 52;4.", repo.FileUpload.SystemItemNameDisplayInfo, new RecordItemIndex(17));
            repo.FileUpload.SystemItemNameDisplay.DoubleClick("52;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber1.TextUpload' at 34;11.", repo.DubberMozillaFirefox.Dubber1.TextUploadInfo, new RecordItemIndex(18));
            repo.DubberMozillaFirefox.Dubber1.TextUpload.Click("34;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'DubberMozillaFirefox.None' at 1351;219.", repo.DubberMozillaFirefox.NoneInfo, new RecordItemIndex(19));
            repo.DubberMozillaFirefox.None.MoveTo("1351;219");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'DubberMozillaFirefox.Dubber1.None4' at 732;205.", repo.DubberMozillaFirefox.Dubber1.None4Info, new RecordItemIndex(20));
            repo.DubberMozillaFirefox.Dubber1.None4.MoveTo("732;205");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'DubberMozillaFirefox.Dubber1.None4' at 740;197.", repo.DubberMozillaFirefox.Dubber1.None4Info, new RecordItemIndex(21));
            repo.DubberMozillaFirefox.Dubber1.None4.MoveTo("740;197");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'DubberMozillaFirefox.Dubber1.None1' at 683;600.", repo.DubberMozillaFirefox.Dubber1.None1Info, new RecordItemIndex(22));
            repo.DubberMozillaFirefox.Dubber1.None1.MoveTo("683;600");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber.TextSaveChanges2' at 41;5.", repo.DubberMozillaFirefox.Dubber.TextSaveChanges2Info, new RecordItemIndex(23));
            repo.DubberMozillaFirefox.Dubber.TextSaveChanges2.Click("41;5");
            Delay.Milliseconds(200);
            
            Mouse_Click_Link();
            Delay.Milliseconds(0);
            
            Mouse_Click_Logout();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.BrowserTabs' at 1347;2.", repo.DubberMozillaFirefox.BrowserTabsInfo, new RecordItemIndex(26));
            repo.DubberMozillaFirefox.BrowserTabs.Click("1347;2");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
