///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace dubeer
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The downloading recording.
    /// </summary>
    [TestModule("7e19d9d2-e460-4504-9d63-0965b53ddc5e", ModuleType.Recording, 1)]
    public partial class Downloading : ITestModule
    {
        /// <summary>
        /// Holds an instance of the dubeerRepository repository.
        /// </summary>
        public static dubeerRepository repo = dubeerRepository.Instance;

        static Downloading instance = new Downloading();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Downloading()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Downloading Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://tigers.dubber.net/login' with browser 'chrome' in normal mode.", new RecordItemIndex(0));
            Host.Local.OpenBrowser("https://tigers.dubber.net/login", "chrome", "", false, false, false, false, false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dubber.UserEmail' at 183;9.", repo.Dubber.UserEmailInfo, new RecordItemIndex(1));
            repo.Dubber.UserEmail.Click("183;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dropdown' at 130;6.", repo.Dropdown.SelfInfo, new RecordItemIndex(2));
            repo.Dropdown.Self.Click("130;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dubber.UserPassword' at 126;18.", repo.Dubber.UserPasswordInfo, new RecordItemIndex(3));
            repo.Dubber.UserPassword.Click("126;18");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dubber.ContentBox' at 112;191.", repo.Dubber.ContentBoxInfo, new RecordItemIndex(4));
            repo.Dubber.ContentBox.Click("112;191");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dubber.SubmitButton' at 42;17.", repo.Dubber.SubmitButtonInfo, new RecordItemIndex(5));
            repo.Dubber.SubmitButton.Click("42;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dubber.SearchBox' at 47;15.", repo.Dubber.SearchBoxInfo, new RecordItemIndex(6));
            repo.Dubber.SearchBox.Click("47;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'testcomplete2{Return}' with focus on 'Dubber.SearchBox'.", repo.Dubber.SearchBoxInfo, new RecordItemIndex(7));
            repo.Dubber.SearchBox.PressKeys("testcomplete2{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dubber.CustomerAccountNameTestcomplete2' at 34;17.", repo.Dubber.CustomerAccountNameTestcomplete2Info, new RecordItemIndex(8));
            repo.Dubber.CustomerAccountNameTestcomplete2.Click("34;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dubber.AccountInboundTab' at 47;25.", repo.Dubber.AccountInboundTabInfo, new RecordItemIndex(9));
            repo.Dubber.AccountInboundTab.Click("47;25");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dubber.InboundNumberLabelInb' at 18;7.", repo.Dubber.InboundNumberLabelInbInfo, new RecordItemIndex(10));
            repo.Dubber.InboundNumberLabelInb.Click("18;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'Dubber' at 1359;308.", repo.Dubber.SelfInfo, new RecordItemIndex(11));
            repo.Dubber.Self.MoveTo("1359;308");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'Dubber' at 1365;612.", repo.Dubber.SelfInfo, new RecordItemIndex(12));
            repo.Dubber.Self.MoveTo("1365;612");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse None Move item 'Dubber' at 1362;609.", repo.Dubber.SelfInfo, new RecordItemIndex(13));
            repo.Dubber.Self.MoveTo("1362;609");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'Dubber.CallflowXmlWell' at 728;234.", repo.Dubber.CallflowXmlWellInfo, new RecordItemIndex(14));
            repo.Dubber.CallflowXmlWell.MoveTo("728;234");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Mouse_Click_DownloadCallflow();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
