///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace dubeer
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Login_logout_drag_check recording.
    /// </summary>
    [TestModule("8b557166-b059-4588-8d44-00c5cd9a79e7", ModuleType.Recording, 1)]
    public partial class Login_logout_drag_check : ITestModule
    {
        /// <summary>
        /// Holds an instance of the dubeerRepository repository.
        /// </summary>
        public static dubeerRepository repo = dubeerRepository.Instance;

        static Login_logout_drag_check instance = new Login_logout_drag_check();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Login_logout_drag_check()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Login_logout_drag_check Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://tigers.dubber.net/login' with browser 'chrome' in normal mode.", new RecordItemIndex(0));
            Host.Local.OpenBrowser("https://tigers.dubber.net/login", "chrome", "", false, false, false, false, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dubber.UserEmail' at 155;20.", repo.Dubber.UserEmailInfo, new RecordItemIndex(1));
            repo.Dubber.UserEmail.Click("155;20");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dropdown' at 145;9.", repo.Dropdown.SelfInfo, new RecordItemIndex(2));
            repo.Dropdown.Self.Click("145;9");
            
            Mouse_Click_UserPassword();
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dubber.ContentBox' at 158;190.", repo.Dubber.ContentBoxInfo, new RecordItemIndex(4));
            repo.Dubber.ContentBox.Click("158;190");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dubber.SubmitButton' at 77;3.", repo.Dubber.SubmitButtonInfo, new RecordItemIndex(5));
            repo.Dubber.SubmitButton.Click("77;3");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dubber.SearchBox' at 53;10.", repo.Dubber.SearchBoxInfo, new RecordItemIndex(6));
            repo.Dubber.SearchBox.Click("53;10");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 't' with focus on 'Dubber.SearchBox'.", repo.Dubber.SearchBoxInfo, new RecordItemIndex(7));
            repo.Dubber.SearchBox.PressKeys("t");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'es' with focus on 'Dubber.SearchBox'.", repo.Dubber.SearchBoxInfo, new RecordItemIndex(8));
            repo.Dubber.SearchBox.PressKeys("es");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'tcomplete2{Return}' with focus on 'Dubber.SearchBox'.", repo.Dubber.SearchBoxInfo, new RecordItemIndex(9));
            repo.Dubber.SearchBox.PressKeys("tcomplete2{Return}");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dubber.CustomerAccountNameTestcomplete2' at 27;15.", repo.Dubber.CustomerAccountNameTestcomplete2Info, new RecordItemIndex(10));
            repo.Dubber.CustomerAccountNameTestcomplete2.Click("27;15");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dubber.AccountInboundTab' at 47;14.", repo.Dubber.AccountInboundTabInfo, new RecordItemIndex(11));
            repo.Dubber.AccountInboundTab.Click("47;14");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dubber.InboundNumberLabelInb' at 14;11.", repo.Dubber.InboundNumberLabelInbInfo, new RecordItemIndex(12));
            repo.Dubber.InboundNumberLabelInb.Click("14;11");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'Dubber' at 1358;275.", repo.Dubber.SelfInfo, new RecordItemIndex(13));
            repo.Dubber.Self.MoveTo("1358;275");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'Dubber.CallflowXmlWell' at 732;191.", repo.Dubber.CallflowXmlWellInfo, new RecordItemIndex(14));
            repo.Dubber.CallflowXmlWell.MoveTo("732;191");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'Dubber.CallflowXmlWell' at 726;352.", repo.Dubber.CallflowXmlWellInfo, new RecordItemIndex(15));
            repo.Dubber.CallflowXmlWell.MoveTo("726;352");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dubber.InboundNumberSubmitButton' at 81;7.", repo.Dubber.InboundNumberSubmitButtonInfo, new RecordItemIndex(16));
            repo.Dubber.InboundNumberSubmitButton.Click("81;7");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dubber.ProfileDdt' at 44;27.", repo.Dubber.ProfileDdtInfo, new RecordItemIndex(17));
            repo.Dubber.ProfileDdt.Click("44;27");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dubber.Caret' at 4;1.", repo.Dubber.CaretInfo, new RecordItemIndex(18));
            repo.Dubber.Caret.Click("4;1");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dubber.DropDownLogout' at 106;2.", repo.Dubber.DropDownLogoutInfo, new RecordItemIndex(19));
            repo.Dubber.DropDownLogout.Click("106;2");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberGoogleChrome.Client' at 1353;3.", repo.DubberGoogleChrome.ClientInfo, new RecordItemIndex(20));
            repo.DubberGoogleChrome.Client.Click("1353;3");
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
