///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace dubeer
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The trail3 recording.
    /// </summary>
    [TestModule("d4d080aa-e688-476a-a3bb-2f947cb3e208", ModuleType.Recording, 1)]
    public partial class trail3 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the dubeerRepository repository.
        /// </summary>
        public static dubeerRepository repo = dubeerRepository.Instance;

        static trail3 instance = new trail3();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public trail3()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static trail3 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'Dubber' at 1354;456.", repo.Dubber.SelfInfo, new RecordItemIndex(0));
            repo.Dubber.Self.MoveTo("1354;456");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'Dubber' at 1349;321.", repo.Dubber.SelfInfo, new RecordItemIndex(1));
            repo.Dubber.Self.MoveTo("1349;321");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dubber.InboundNumberAdvancedXml' at 58;13.", repo.Dubber.InboundNumberAdvancedXmlInfo, new RecordItemIndex(2));
            repo.Dubber.InboundNumberAdvancedXml.Click("58;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'Open.SystemItemNameDisplay' at 145;10.", repo.Open.SystemItemNameDisplayInfo, new RecordItemIndex(3));
            repo.Open.SystemItemNameDisplay.DoubleClick("145;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dubber.UploadCallflowButton' at 58;7.", repo.Dubber.UploadCallflowButtonInfo, new RecordItemIndex(4));
            repo.Dubber.UploadCallflowButton.Click("58;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'Dubber' at 1353;282.", repo.Dubber.SelfInfo, new RecordItemIndex(5));
            repo.Dubber.Self.MoveTo("1353;282");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'Dubber.CallflowXmlWell' at 728;228.", repo.Dubber.CallflowXmlWellInfo, new RecordItemIndex(6));
            repo.Dubber.CallflowXmlWell.MoveTo("728;228");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'Dubber.CallflowXmlWell' at 728;372.", repo.Dubber.CallflowXmlWellInfo, new RecordItemIndex(7));
            repo.Dubber.CallflowXmlWell.MoveTo("728;372");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Mouse_Click_InboundNumberSubmitButton();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'Dubber.Caret' at 5;0.", repo.Dubber.CaretInfo, new RecordItemIndex(9));
            repo.Dubber.Caret.DoubleClick("5;0");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dubber.ProfileDdt' at 36;13.", repo.Dubber.ProfileDdtInfo, new RecordItemIndex(10));
            repo.Dubber.ProfileDdt.Click("36;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dubber.DropDownLogout' at 97;9.", repo.Dubber.DropDownLogoutInfo, new RecordItemIndex(11));
            repo.Dubber.DropDownLogout.Click("97;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberGoogleChrome.Client' at 1356;3.", repo.DubberGoogleChrome.ClientInfo, new RecordItemIndex(12));
            repo.DubberGoogleChrome.Client.Click("1356;3");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
