///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace dubeer
{
    public partial class Uploading_callflow
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void Mouse_Click_Upload()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber1.Upload' at 83;14.", repo.DubberMozillaFirefox.Dubber1.UploadInfo);
            repo.DubberMozillaFirefox.Dubber1.Upload.Click("83;14");
              Thread.Sleep(10000);
        }

        public void Mouse_Click_TextSaveChanges2()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber.TextSaveChanges2' at 51;6.", repo.DubberMozillaFirefox.Dubber.TextSaveChanges2Info);
            repo.DubberMozillaFirefox.Dubber.TextSaveChanges2.Click("51;6");
              Thread.Sleep(10000);
        }

        public void Mouse_Click_UploadCallflowButton()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dubber.UploadCallflowButton' at 24;7.", repo.Dubber.UploadCallflowButtonInfo);
            repo.Dubber.UploadCallflowButton.Click("24;7");
            Thread.Sleep(10000);
           
        }

        public void Mouse_Click_InboundNumberSubmitButton()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dubber.InboundNumberSubmitButton' at 88;8.", repo.Dubber.InboundNumberSubmitButtonInfo);
            repo.Dubber.InboundNumberSubmitButton.Click("88;8");
            Thread.Sleep(10000);
        }

        public void Mouse_Click_InboundNumberSubmitButton1()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dubber.InboundNumberSubmitButton' at 92;14.", repo.Dubber.InboundNumberSubmitButtonInfo);
            repo.Dubber.InboundNumberSubmitButton.Click("92;14");
            Thread.Sleep(10000);
        }

        public void Mouse_Click_DropDownLogout()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dubber.DropDownLogout' at 86;7.", repo.Dubber.DropDownLogoutInfo);
            repo.Dubber.DropDownLogout.Click("86;7");
        }

        public void Mouse_Click_ProfileDdt()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dubber.ProfileDdt' at 45;21.", repo.Dubber.ProfileDdtInfo);
            repo.Dubber.ProfileDdt.Click("45;21");
        }

    }
}