///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace dubeer
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The uploading_callflow recording.
    /// </summary>
    [TestModule("d0ac1124-20d6-47d8-96a2-438e2ffbe7fe", ModuleType.Recording, 1)]
    public partial class Uploading_callflow : ITestModule
    {
        /// <summary>
        /// Holds an instance of the dubeerRepository repository.
        /// </summary>
        public static dubeerRepository repo = dubeerRepository.Instance;

        static Uploading_callflow instance = new Uploading_callflow();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Uploading_callflow()
        {
            C__Users_Damodar_Shanbhag_Downloads_inb_Callflow_xml = "{Capital}C{Capital}{RShiftKey down}:{RShiftKey up}\\";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Uploading_callflow Instance
        {
            get { return instance; }
        }

#region Variables

        string _C__Users_Damodar_Shanbhag_Downloads_inb_Callflow_xml;

        /// <summary>
        /// Gets or sets the value of variable C__Users_Damodar_Shanbhag_Downloads_inb_Callflow_xml.
        /// </summary>
        [TestVariable("1a82730a-bfb6-40b9-a24f-c4b0e2513b89")]
        public string C__Users_Damodar_Shanbhag_Downloads_inb_Callflow_xml
        {
            get { return _C__Users_Damodar_Shanbhag_Downloads_inb_Callflow_xml; }
            set { _C__Users_Damodar_Shanbhag_Downloads_inb_Callflow_xml = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'Dubber' at 1353;427.", repo.Dubber.SelfInfo, new RecordItemIndex(0));
            repo.Dubber.Self.MoveTo("1353;427");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'Dubber' at 1361;266.", repo.Dubber.SelfInfo, new RecordItemIndex(1));
            repo.Dubber.Self.MoveTo("1361;266");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dubber.InboundNumberAdvancedXml' at 52;14.", repo.Dubber.InboundNumberAdvancedXmlInfo, new RecordItemIndex(2));
            repo.Dubber.InboundNumberAdvancedXml.Click("52;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Open.Text1148' at 144;6.", repo.Open.Text1148Info, new RecordItemIndex(3));
            repo.Open.Text1148.Click("144;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Capital}C{Capital}{RShiftKey down}:{RShiftKey up}\\users\\{Capital}D{Capital}amodar{Capital}{Space}S{Capital}hanbhag\\{Capital}D{Capital}ownloads\\ibn-callflow{Left 8}{Left}{Left}{Right}{Back}{Back}nb{Right 21}.xml' with focus on 'Open.Text1148'.", repo.Open.Text1148Info, new RecordItemIndex(4));
            repo.Open.Text1148.PressKeys("{Capital}C{Capital}{RShiftKey down}:{RShiftKey up}\\users\\{Capital}D{Capital}amodar{Capital}{Space}S{Capital}hanbhag\\{Capital}D{Capital}ownloads\\ibn-callflow{Left 8}{Left}{Left}{Right}{Back}{Back}nb{Right 21}.xml");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Open.ButtonOpen' at 43;9.", repo.Open.ButtonOpenInfo, new RecordItemIndex(5));
            repo.Open.ButtonOpen.Click("43;9");
            Delay.Milliseconds(200);
            
            Mouse_Click_UploadCallflowButton();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'Dubber' at 1359;177.", repo.Dubber.SelfInfo, new RecordItemIndex(7));
            repo.Dubber.Self.DoubleClick("1359;177");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'Dubber' at 1328;502.", repo.Dubber.SelfInfo, new RecordItemIndex(8));
            repo.Dubber.Self.MoveTo("1328;502");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'Dubber.CallflowXmlWell' at 731;232.", repo.Dubber.CallflowXmlWellInfo, new RecordItemIndex(9));
            repo.Dubber.CallflowXmlWell.MoveTo("731;232");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'Dubber.CallflowXmlWell' at 739;224.", repo.Dubber.CallflowXmlWellInfo, new RecordItemIndex(10));
            repo.Dubber.CallflowXmlWell.MoveTo("739;224");
            Delay.Milliseconds(200);
            
            Mouse_Click_InboundNumberSubmitButton1();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
