///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace dubber
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the dubberRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    [RepositoryFolder("679e61dd-5cc8-44ae-9478-e0b7f37f4fa9")]
    public partial class dubberRepository : RepoGenBaseFolder
    {
        static dubberRepository instance = new dubberRepository();
        dubberRepositoryFolders.DubberMozillaFirefoxAppFolder _dubbermozillafirefox;
        dubberRepositoryFolders.FileUploadAppFolder _fileupload;
        dubberRepositoryFolders.DubberAppFolder _dubber;
        dubberRepositoryFolders.DISPLAY1LowerRightAppFolder _display1lowerright;
        dubberRepositoryFolders.DownloadsAppFolder _downloads;
        dubberRepositoryFolders.InbCallflow3NotepadAppFolder _inbcallflow3notepad;
        dubberRepositoryFolders.NotepadAppFolder _notepad;
        dubberRepositoryFolders.DropdownAppFolder _dropdown;

        /// <summary>
        /// Gets the singleton class instance representing the dubberRepository element repository.
        /// </summary>
        [RepositoryFolder("679e61dd-5cc8-44ae-9478-e0b7f37f4fa9")]
        public static dubberRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public dubberRepository() 
            : base("dubberRepository", "/", null, 0, false, "679e61dd-5cc8-44ae-9478-e0b7f37f4fa9", ".\\RepositoryImages\\dubberRepository679e61dd.rximgres")
        {
            _dubbermozillafirefox = new dubberRepositoryFolders.DubberMozillaFirefoxAppFolder(this);
            _fileupload = new dubberRepositoryFolders.FileUploadAppFolder(this);
            _dubber = new dubberRepositoryFolders.DubberAppFolder(this);
            _display1lowerright = new dubberRepositoryFolders.DISPLAY1LowerRightAppFolder(this);
            _downloads = new dubberRepositoryFolders.DownloadsAppFolder(this);
            _inbcallflow3notepad = new dubberRepositoryFolders.InbCallflow3NotepadAppFolder(this);
            _notepad = new dubberRepositoryFolders.NotepadAppFolder(this);
            _dropdown = new dubberRepositoryFolders.DropdownAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("679e61dd-5cc8-44ae-9478-e0b7f37f4fa9")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The DubberMozillaFirefox folder.
        /// </summary>
        [RepositoryFolder("0c0b48ec-7d79-4404-983c-18f903001b94")]
        public virtual dubberRepositoryFolders.DubberMozillaFirefoxAppFolder DubberMozillaFirefox
        {
            get { return _dubbermozillafirefox; }
        }

        /// <summary>
        /// The FileUpload folder.
        /// </summary>
        [RepositoryFolder("e500a5f4-3def-49e0-9275-8ebd6547c47a")]
        public virtual dubberRepositoryFolders.FileUploadAppFolder FileUpload
        {
            get { return _fileupload; }
        }

        /// <summary>
        /// The Dubber folder.
        /// </summary>
        [RepositoryFolder("295341c3-99ff-4894-9892-319602a3a4a4")]
        public virtual dubberRepositoryFolders.DubberAppFolder Dubber
        {
            get { return _dubber; }
        }

        /// <summary>
        /// The DISPLAY1LowerRight folder.
        /// </summary>
        [RepositoryFolder("9972aef6-a7be-4246-a552-8033cd36ed9c")]
        public virtual dubberRepositoryFolders.DISPLAY1LowerRightAppFolder DISPLAY1LowerRight
        {
            get { return _display1lowerright; }
        }

        /// <summary>
        /// The Downloads folder.
        /// </summary>
        [RepositoryFolder("d6928b19-d5fc-4f9c-b0ea-cb4cf4474edc")]
        public virtual dubberRepositoryFolders.DownloadsAppFolder Downloads
        {
            get { return _downloads; }
        }

        /// <summary>
        /// The InbCallflow3Notepad folder.
        /// </summary>
        [RepositoryFolder("3561f37a-c6dc-4012-91de-92d708ef5cea")]
        public virtual dubberRepositoryFolders.InbCallflow3NotepadAppFolder InbCallflow3Notepad
        {
            get { return _inbcallflow3notepad; }
        }

        /// <summary>
        /// The Notepad folder.
        /// </summary>
        [RepositoryFolder("2fe476ff-6224-40d8-9f0f-0eda10964e68")]
        public virtual dubberRepositoryFolders.NotepadAppFolder Notepad
        {
            get { return _notepad; }
        }

        /// <summary>
        /// The Dropdown folder.
        /// </summary>
        [RepositoryFolder("33c7bbd1-8b21-4049-b3ba-b5eba1425d2b")]
        public virtual dubberRepositoryFolders.DropdownAppFolder Dropdown
        {
            get { return _dropdown; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    public partial class dubberRepositoryFolders
    {
        /// <summary>
        /// The DubberMozillaFirefoxAppFolder folder.
        /// </summary>
        [RepositoryFolder("0c0b48ec-7d79-4404-983c-18f903001b94")]
        public partial class DubberMozillaFirefoxAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new DubberMozillaFirefox  folder.
            /// </summary>
            public DubberMozillaFirefoxAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DubberMozillaFirefox", "/form[@title='Dubber - Mozilla Firefox']", parentFolder, 30000, null, true, "0c0b48ec-7d79-4404-983c-18f903001b94", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("0c0b48ec-7d79-4404-983c-18f903001b94")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("0c0b48ec-7d79-4404-983c-18f903001b94")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The FileUploadAppFolder folder.
        /// </summary>
        [RepositoryFolder("e500a5f4-3def-49e0-9275-8ebd6547c47a")]
        public partial class FileUploadAppFolder : RepoGenBaseFolder
        {
            dubberRepositoryFolders.ShellViewFolder _shellview;
            RepoItemInfo _systemitemnamedisplayInfo;
            RepoItemInfo _buttonopenInfo;
            RepoItemInfo _someindicatorInfo;
            RepoItemInfo _systemitemnamedisplay1Info;
            RepoItemInfo _localdiskcInfo;

            /// <summary>
            /// Creates a new FileUpload  folder.
            /// </summary>
            public FileUploadAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FileUpload", "/form[@title='File Upload']", parentFolder, 30000, null, true, "e500a5f4-3def-49e0-9275-8ebd6547c47a", "")
            {
                _shellview = new dubberRepositoryFolders.ShellViewFolder(this);
                _systemitemnamedisplayInfo = new RepoItemInfo(this, "SystemItemNameDisplay", "element[@class='DUIViewWndClassName']//container[@caption='ShellView']/?/?/listitem[@automationid='8']/text[@automationid='System.ItemNameDisplay']", 30000, null, "d241eb46-d806-4ae3-a969-ed878157dd5f");
                _buttonopenInfo = new RepoItemInfo(this, "ButtonOpen", "button[@text='&Open']", 30000, null, "8c6ff31f-c1db-4597-925a-4dd99c100e2d");
                _someindicatorInfo = new RepoItemInfo(this, "SomeIndicator", "element[@class='DUIViewWndClassName']//container[@caption='ShellView']/container[@class='DirectUIHWND']/element[@instance='1']/scrollbar[@style='Custom']/indicator", 30000, null, "d62426d5-f62f-4e1a-ac75-9c294345e600");
                _systemitemnamedisplay1Info = new RepoItemInfo(this, "SystemItemNameDisplay1", "element[@class='DUIViewWndClassName']//container[@caption='ShellView']/?/?/listitem[@automationid='11']/text[@automationid='System.ItemNameDisplay']", 30000, null, "19e5dfa4-a86f-4839-9a20-e942d9e48ef2");
                _localdiskcInfo = new RepoItemInfo(this, "LocalDiskC", "element[@class='DUIViewWndClassName']/container/element[1]/?/?/tree[@controlid='100']//treeitem[@text='Local Disk (C:)']", 30000, null, "f74595ad-02b8-49a1-9805-a8888a24cc17");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e500a5f4-3def-49e0-9275-8ebd6547c47a")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e500a5f4-3def-49e0-9275-8ebd6547c47a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SystemItemNameDisplay item.
            /// </summary>
            [RepositoryItem("d241eb46-d806-4ae3-a969-ed878157dd5f")]
            public virtual Ranorex.Text SystemItemNameDisplay
            {
                get
                {
                    return _systemitemnamedisplayInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SystemItemNameDisplay item info.
            /// </summary>
            [RepositoryItemInfo("d241eb46-d806-4ae3-a969-ed878157dd5f")]
            public virtual RepoItemInfo SystemItemNameDisplayInfo
            {
                get
                {
                    return _systemitemnamedisplayInfo;
                }
            }

            /// <summary>
            /// The ButtonOpen item.
            /// </summary>
            [RepositoryItem("8c6ff31f-c1db-4597-925a-4dd99c100e2d")]
            public virtual Ranorex.Button ButtonOpen
            {
                get
                {
                    return _buttonopenInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOpen item info.
            /// </summary>
            [RepositoryItemInfo("8c6ff31f-c1db-4597-925a-4dd99c100e2d")]
            public virtual RepoItemInfo ButtonOpenInfo
            {
                get
                {
                    return _buttonopenInfo;
                }
            }

            /// <summary>
            /// The SomeIndicator item.
            /// </summary>
            [RepositoryItem("d62426d5-f62f-4e1a-ac75-9c294345e600")]
            public virtual Ranorex.Indicator SomeIndicator
            {
                get
                {
                    return _someindicatorInfo.CreateAdapter<Ranorex.Indicator>(true);
                }
            }

            /// <summary>
            /// The SomeIndicator item info.
            /// </summary>
            [RepositoryItemInfo("d62426d5-f62f-4e1a-ac75-9c294345e600")]
            public virtual RepoItemInfo SomeIndicatorInfo
            {
                get
                {
                    return _someindicatorInfo;
                }
            }

            /// <summary>
            /// The SystemItemNameDisplay1 item.
            /// </summary>
            [RepositoryItem("19e5dfa4-a86f-4839-9a20-e942d9e48ef2")]
            public virtual Ranorex.Text SystemItemNameDisplay1
            {
                get
                {
                    return _systemitemnamedisplay1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SystemItemNameDisplay1 item info.
            /// </summary>
            [RepositoryItemInfo("19e5dfa4-a86f-4839-9a20-e942d9e48ef2")]
            public virtual RepoItemInfo SystemItemNameDisplay1Info
            {
                get
                {
                    return _systemitemnamedisplay1Info;
                }
            }

            /// <summary>
            /// The LocalDiskC item.
            /// </summary>
            [RepositoryItem("f74595ad-02b8-49a1-9805-a8888a24cc17")]
            public virtual Ranorex.TreeItem LocalDiskC
            {
                get
                {
                    return _localdiskcInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The LocalDiskC item info.
            /// </summary>
            [RepositoryItemInfo("f74595ad-02b8-49a1-9805-a8888a24cc17")]
            public virtual RepoItemInfo LocalDiskCInfo
            {
                get
                {
                    return _localdiskcInfo;
                }
            }

            /// <summary>
            /// The ShellView folder.
            /// </summary>
            [RepositoryFolder("314f38c6-be27-4658-8651-293bd5b8701c")]
            public virtual dubberRepositoryFolders.ShellViewFolder ShellView
            {
                get { return _shellview; }
            }
        }

        /// <summary>
        /// The ShellViewFolder folder.
        /// </summary>
        [RepositoryFolder("314f38c6-be27-4658-8651-293bd5b8701c")]
        public partial class ShellViewFolder : RepoGenBaseFolder
        {
            RepoItemInfo _systemitemnamedisplay3Info;
            RepoItemInfo _systemitemnamedisplay4Info;

            /// <summary>
            /// Creates a new ShellView  folder.
            /// </summary>
            public ShellViewFolder(RepoGenBaseFolder parentFolder) :
                    base("ShellView", "element[@class='DUIViewWndClassName']//container[@caption='ShellView']", parentFolder, 30000, null, false, "314f38c6-be27-4658-8651-293bd5b8701c", "")
            {
                _systemitemnamedisplay3Info = new RepoItemInfo(this, "SystemItemNameDisplay3", "?/?/listitem[@automationid='0']/text[@automationid='System.ItemNameDisplay']", 30000, null, "754c2164-34b7-4530-90db-78d34f89c5f5");
                _systemitemnamedisplay4Info = new RepoItemInfo(this, "SystemItemNameDisplay4", "?/?/listitem[@automationid='5']/text[@automationid='System.ItemNameDisplay']", 30000, null, "2772999f-7161-4ec8-a573-b24d8fe95238");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("314f38c6-be27-4658-8651-293bd5b8701c")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("314f38c6-be27-4658-8651-293bd5b8701c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SystemItemNameDisplay3 item.
            /// </summary>
            [RepositoryItem("754c2164-34b7-4530-90db-78d34f89c5f5")]
            public virtual Ranorex.Text SystemItemNameDisplay3
            {
                get
                {
                    return _systemitemnamedisplay3Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SystemItemNameDisplay3 item info.
            /// </summary>
            [RepositoryItemInfo("754c2164-34b7-4530-90db-78d34f89c5f5")]
            public virtual RepoItemInfo SystemItemNameDisplay3Info
            {
                get
                {
                    return _systemitemnamedisplay3Info;
                }
            }

            /// <summary>
            /// The SystemItemNameDisplay4 item.
            /// </summary>
            [RepositoryItem("2772999f-7161-4ec8-a573-b24d8fe95238")]
            public virtual Ranorex.Text SystemItemNameDisplay4
            {
                get
                {
                    return _systemitemnamedisplay4Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SystemItemNameDisplay4 item info.
            /// </summary>
            [RepositoryItemInfo("2772999f-7161-4ec8-a573-b24d8fe95238")]
            public virtual RepoItemInfo SystemItemNameDisplay4Info
            {
                get
                {
                    return _systemitemnamedisplay4Info;
                }
            }
        }

        /// <summary>
        /// The DubberAppFolder folder.
        /// </summary>
        [RepositoryFolder("295341c3-99ff-4894-9892-319602a3a4a4")]
        public partial class DubberAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _useremailInfo;
            RepoItemInfo _userpasswordInfo;
            RepoItemInfo _contentboxInfo;
            RepoItemInfo _submitbuttonInfo;
            RepoItemInfo _managedapsbuttonInfo;
            RepoItemInfo _newdapInfo;
            RepoItemInfo _dapareaidInfo;
            RepoItemInfo _modalbackdropfadeinInfo;
            RepoItemInfo _areadescriptionInfo;
            RepoItemInfo _areastateInfo;
            RepoItemInfo _areacountryInfo;
            RepoItemInfo _newareaokbuttonInfo;
            RepoItemInfo _dapstartnumberareacodeInfo;
            RepoItemInfo _dapstartnumberservicenumberInfo;
            RepoItemInfo _dapendnumberareacodeInfo;
            RepoItemInfo _dapendnumberservicenumberInfo;
            RepoItemInfo _dapsubmitbuttonInfo;
            RepoItemInfo _confirmdapcreationbuttonInfo;
            RepoItemInfo _profileddtInfo;
            RepoItemInfo _dropdownlogoutInfo;
            RepoItemInfo _containeradminInfo;
            RepoItemInfo _accounttabInfo;
            RepoItemInfo _newaccountInfo;
            RepoItemInfo _accountnameInfo;
            RepoItemInfo _accountdubberaddressInfo;
            RepoItemInfo _accountexternalreferenceInfo;
            RepoItemInfo _accounttimezoneInfo;
            RepoItemInfo _accountaddressattributesaddressInfo;
            RepoItemInfo _accountaddressattributessuburbInfo;
            RepoItemInfo _accountaddressattributescountryInfo;
            RepoItemInfo _accountaddressattributespostcodeInfo;
            RepoItemInfo _accountphoneareacodeInfo;
            RepoItemInfo _accountphoneservicenumberInfo;
            RepoItemInfo _accountaccountusersattributes0emailInfo;
            RepoItemInfo _accountaccountusersattributes0email1Info;
            RepoItemInfo _accountaccountusersattributes0firstInfo;
            RepoItemInfo _accountaccountusersattributes0lastInfo;
            RepoItemInfo _accountsubmitbuttonInfo;
            RepoItemInfo _accountaddressattributesstateInfo;
            RepoItemInfo _inboundnumberareaInfo;
            RepoItemInfo _inboundnumberdapidInfo;
            RepoItemInfo _inboundnumbernumberservicenumberInfo;
            RepoItemInfo _inboundnumberlabelInfo;
            RepoItemInfo _inboundnumbercapdubpointsattributesInfo;
            RepoItemInfo _inboundnumbercapdubpointsattributes1Info;
            RepoItemInfo _inboundnumbersubmitbuttonInfo;
            RepoItemInfo _caretInfo;

            /// <summary>
            /// Creates a new Dubber  folder.
            /// </summary>
            public DubberAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Dubber", "/dom[@domain='tigers.dubber.net']", parentFolder, 30000, null, false, "295341c3-99ff-4894-9892-319602a3a4a4", "")
            {
                _useremailInfo = new RepoItemInfo(this, "UserEmail", ".//input[#'user_email']", 30000, null, "6e78a8ff-da49-42c9-a85d-440991663d28");
                _userpasswordInfo = new RepoItemInfo(this, "UserPassword", ".//input[#'user_password']", 30000, null, "3c65f661-633b-43d1-8555-15e973055266");
                _contentboxInfo = new RepoItemInfo(this, "ContentBox", ".//div[#'main_body']/div[1]/div/div[2]", 30000, null, "1ca7f69e-73c4-49f7-a883-b5062e6b91d2");
                _submitbuttonInfo = new RepoItemInfo(this, "SubmitButton", ".//input[#'submit_button']", 30000, null, "26e98c01-64a5-4b1f-8264-7cc26ccd1bbf");
                _managedapsbuttonInfo = new RepoItemInfo(this, "ManageDapsButton", ".//a[#'manage_daps_button']", 30000, null, "df6c7239-70f1-4d4d-bca4-c237ee3ef11e");
                _newdapInfo = new RepoItemInfo(this, "NewDap", ".//a[#'new_dap']", 30000, null, "1b9c7dfd-ea23-464e-a58b-eb23cab8aeef");
                _dapareaidInfo = new RepoItemInfo(this, "DapAreaId", ".//select[#'dap_area_id']", 30000, null, "3b9ee07f-fdc6-4707-bb0e-93619b3c7ae3");
                _modalbackdropfadeinInfo = new RepoItemInfo(this, "ModalBackdropFadeIn", "body/div[6]", 30000, null, "620b4aed-64bf-472a-8bbc-9349e0f58df8");
                _areadescriptionInfo = new RepoItemInfo(this, "AreaDescription", ".//input[#'area_description']", 30000, null, "c3dd41cd-c077-4084-9ddd-029408eb30e6");
                _areastateInfo = new RepoItemInfo(this, "AreaState", ".//input[#'area_state']", 30000, null, "b1b582b0-ef88-478c-ba73-49e5c3125066");
                _areacountryInfo = new RepoItemInfo(this, "AreaCountry", ".//select[#'area_country']", 30000, null, "ff7bce66-d8ca-4012-b035-075d78716075");
                _newareaokbuttonInfo = new RepoItemInfo(this, "NewAreaOkButton", ".//button[#'new_area_ok_button']", 30000, null, "30c8c8a0-1736-43ce-b755-d315eba2f789");
                _dapstartnumberareacodeInfo = new RepoItemInfo(this, "DapStartNumberAreaCode", ".//select[#'dap_start_number_area_code']", 30000, null, "0773e6c1-12a9-4905-b9dd-a5a1b9c10a7e");
                _dapstartnumberservicenumberInfo = new RepoItemInfo(this, "DapStartNumberServiceNumber", ".//input[#'dap_start_number_service_number']", 30000, null, "72b432ec-4ab1-4875-8e42-9aeb31237672");
                _dapendnumberareacodeInfo = new RepoItemInfo(this, "DapEndNumberAreaCode", ".//select[#'dap_end_number_area_code']", 30000, null, "05947189-68df-4ed9-a288-970ebbe85066");
                _dapendnumberservicenumberInfo = new RepoItemInfo(this, "DapEndNumberServiceNumber", ".//input[#'dap_end_number_service_number']", 30000, null, "1ea2544c-220b-46e7-aec5-d528009fc5e4");
                _dapsubmitbuttonInfo = new RepoItemInfo(this, "DapSubmitButton", ".//button[#'dap_submit_button']", 30000, null, "574bb672-3e29-47b2-bb0e-b7e77b86a8dc");
                _confirmdapcreationbuttonInfo = new RepoItemInfo(this, "ConfirmDapCreationButton", ".//button[#'confirm_dap_creation_button']", 30000, null, "a0954b2b-0052-4d3d-9eaf-44bcb3354d7f");
                _profileddtInfo = new RepoItemInfo(this, "ProfileDdt", ".//a[#'profile-ddt']", 30000, null, "036b39c5-f342-4481-8e9c-a8e7cf15a497");
                _dropdownlogoutInfo = new RepoItemInfo(this, "DropDownLogout", ".//a[#'drop_down_logout']", 30000, null, "32598150-b4e1-42b2-845a-feff92e58c50");
                _containeradminInfo = new RepoItemInfo(this, "ContainerAdmin", "body/div[3]", 30000, null, "40c27e0b-e7d8-4844-ad0d-c4bd85604cd4");
                _accounttabInfo = new RepoItemInfo(this, "AccountTab", ".//a[#'account_tab']", 30000, null, "d0f108ec-4cc8-4162-be0d-e363a9d476e8");
                _newaccountInfo = new RepoItemInfo(this, "NewAccount", ".//a[#'new_account']", 30000, null, "3913aa06-6f2a-413b-9261-9b751d859170");
                _accountnameInfo = new RepoItemInfo(this, "AccountName", "body/div[3]/div[@id='main_body']//form[@id='new_account']/div[1]/?/?/div/input[@id='account_name']", 30000, null, "e4721a3f-137a-43c7-9bb7-9e955fd934cd");
                _accountdubberaddressInfo = new RepoItemInfo(this, "AccountDubberAddress", ".//input[#'account_dubber_address']", 30000, null, "4d61d999-ba23-4368-a6c9-ab688dae127f");
                _accountexternalreferenceInfo = new RepoItemInfo(this, "AccountExternalReference", ".//input[#'account_external_reference']", 30000, null, "d6772cd5-7203-46f8-9b77-670b9674bec7");
                _accounttimezoneInfo = new RepoItemInfo(this, "AccountTimeZone", ".//select[#'account_time_zone']", 30000, null, "d9268121-7036-48c5-a911-06fcc0f5f413");
                _accountaddressattributesaddressInfo = new RepoItemInfo(this, "AccountAddressAttributesAddress", ".//input[#'account_address_attributes_address']", 30000, null, "1dfbf7ea-fa99-4f20-a460-b3cbafe1de3c");
                _accountaddressattributessuburbInfo = new RepoItemInfo(this, "AccountAddressAttributesSuburb", ".//input[#'account_address_attributes_suburb']", 30000, null, "24dfc774-490e-4baa-bfc8-9c451349f113");
                _accountaddressattributescountryInfo = new RepoItemInfo(this, "AccountAddressAttributesCountry", ".//select[#'account_address_attributes_country']", 30000, null, "ced0c677-f83d-4933-ab79-7229e777d789");
                _accountaddressattributespostcodeInfo = new RepoItemInfo(this, "AccountAddressAttributesPostCode", ".//input[#'account_address_attributes_post_code']", 30000, null, "e2b758fd-2cfa-44e4-99b6-12064fbbeed8");
                _accountphoneareacodeInfo = new RepoItemInfo(this, "AccountPhoneAreaCode", ".//select[#'account_phone_area_code']", 30000, null, "31b4bd0d-55d2-41cd-8a55-bfaec47c9e27");
                _accountphoneservicenumberInfo = new RepoItemInfo(this, "AccountPhoneServiceNumber", ".//input[#'account_phone_service_number']", 30000, null, "f21cefc0-55b6-4009-8e44-8ee66134373d");
                _accountaccountusersattributes0emailInfo = new RepoItemInfo(this, "AccountAccountUsersAttributes0Email", ".//input[#'account_account_users_attributes_0_email']", 30000, null, "037bb8ad-be72-4d7e-aaac-bed9954f11a0");
                _accountaccountusersattributes0email1Info = new RepoItemInfo(this, "AccountAccountUsersAttributes0Email1", ".//input[#'account_account_users_attributes_0_email_confirmation']", 30000, null, "4a9c3e83-abc8-4de5-a7d6-1fcf3fcfef9a");
                _accountaccountusersattributes0firstInfo = new RepoItemInfo(this, "AccountAccountUsersAttributes0First", ".//input[#'account_account_users_attributes_0_first_name']", 30000, null, "485ed98a-6940-4be3-a4ae-a7cbf2a96558");
                _accountaccountusersattributes0lastInfo = new RepoItemInfo(this, "AccountAccountUsersAttributes0Last", ".//input[#'account_account_users_attributes_0_last_name']", 30000, null, "e2d072a4-2f99-4097-a848-b7ba86917c28");
                _accountsubmitbuttonInfo = new RepoItemInfo(this, "AccountSubmitButton", ".//button[#'account_submit_button']", 30000, null, "5e04eb44-a10a-4320-a85a-90201a746f6d");
                _accountaddressattributesstateInfo = new RepoItemInfo(this, "AccountAddressAttributesState", ".//select[#'account_address_attributes_state']", 30000, null, "4f088292-f818-44e4-b434-08001de66980");
                _inboundnumberareaInfo = new RepoItemInfo(this, "InboundNumberArea", ".//select[#'inbound_number_area']", 30000, null, "4b978ceb-65d1-4475-9443-d739f40392a4");
                _inboundnumberdapidInfo = new RepoItemInfo(this, "InboundNumberDapId", ".//select[#'inbound_number_dap_id']", 30000, null, "624fb984-9c89-4755-975a-c20350177fae");
                _inboundnumbernumberservicenumberInfo = new RepoItemInfo(this, "InboundNumberNumberServiceNumber", ".//input[#'inbound_number_number_service_number']", 30000, null, "ed73ca62-4017-4c4c-927e-756665833022");
                _inboundnumberlabelInfo = new RepoItemInfo(this, "InboundNumberLabel", ".//input[#'inbound_number_label']", 30000, null, "658b0e47-3867-46a0-b984-6f622045d63a");
                _inboundnumbercapdubpointsattributesInfo = new RepoItemInfo(this, "InboundNumberCapDubPointsAttributes", ".//input[#'inbound_number_cap_dub_points_attributes_0_number_service_number']", 30000, null, "e816da5c-31b4-49dd-bc51-53620364b75d");
                _inboundnumbercapdubpointsattributes1Info = new RepoItemInfo(this, "InboundNumberCapDubPointsAttributes1", ".//input[#'inbound_number_cap_dub_points_attributes_0_label']", 30000, null, "ba051188-c600-4fbc-aebb-5df32bdd7795");
                _inboundnumbersubmitbuttonInfo = new RepoItemInfo(this, "InboundNumberSubmitButton", ".//button[#'inbound_number_submit_button']", 30000, null, "ce45f769-7f8a-4b41-886f-dc2862502164");
                _caretInfo = new RepoItemInfo(this, "Caret", ".//a[#'profile-ddt']/span", 30000, null, "7d80543f-f2e3-441e-add6-e126844c30fd");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("295341c3-99ff-4894-9892-319602a3a4a4")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("295341c3-99ff-4894-9892-319602a3a4a4")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The UserEmail item.
            /// </summary>
            [RepositoryItem("6e78a8ff-da49-42c9-a85d-440991663d28")]
            public virtual Ranorex.InputTag UserEmail
            {
                get
                {
                    return _useremailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The UserEmail item info.
            /// </summary>
            [RepositoryItemInfo("6e78a8ff-da49-42c9-a85d-440991663d28")]
            public virtual RepoItemInfo UserEmailInfo
            {
                get
                {
                    return _useremailInfo;
                }
            }

            /// <summary>
            /// The UserPassword item.
            /// </summary>
            [RepositoryItem("3c65f661-633b-43d1-8555-15e973055266")]
            public virtual Ranorex.InputTag UserPassword
            {
                get
                {
                    return _userpasswordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The UserPassword item info.
            /// </summary>
            [RepositoryItemInfo("3c65f661-633b-43d1-8555-15e973055266")]
            public virtual RepoItemInfo UserPasswordInfo
            {
                get
                {
                    return _userpasswordInfo;
                }
            }

            /// <summary>
            /// The ContentBox item.
            /// </summary>
            [RepositoryItem("1ca7f69e-73c4-49f7-a883-b5062e6b91d2")]
            public virtual Ranorex.DivTag ContentBox
            {
                get
                {
                    return _contentboxInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ContentBox item info.
            /// </summary>
            [RepositoryItemInfo("1ca7f69e-73c4-49f7-a883-b5062e6b91d2")]
            public virtual RepoItemInfo ContentBoxInfo
            {
                get
                {
                    return _contentboxInfo;
                }
            }

            /// <summary>
            /// The SubmitButton item.
            /// </summary>
            [RepositoryItem("26e98c01-64a5-4b1f-8264-7cc26ccd1bbf")]
            public virtual Ranorex.InputTag SubmitButton
            {
                get
                {
                    return _submitbuttonInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The SubmitButton item info.
            /// </summary>
            [RepositoryItemInfo("26e98c01-64a5-4b1f-8264-7cc26ccd1bbf")]
            public virtual RepoItemInfo SubmitButtonInfo
            {
                get
                {
                    return _submitbuttonInfo;
                }
            }

            /// <summary>
            /// The ManageDapsButton item.
            /// </summary>
            [RepositoryItem("df6c7239-70f1-4d4d-bca4-c237ee3ef11e")]
            public virtual Ranorex.ATag ManageDapsButton
            {
                get
                {
                    return _managedapsbuttonInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ManageDapsButton item info.
            /// </summary>
            [RepositoryItemInfo("df6c7239-70f1-4d4d-bca4-c237ee3ef11e")]
            public virtual RepoItemInfo ManageDapsButtonInfo
            {
                get
                {
                    return _managedapsbuttonInfo;
                }
            }

            /// <summary>
            /// The NewDap item.
            /// </summary>
            [RepositoryItem("1b9c7dfd-ea23-464e-a58b-eb23cab8aeef")]
            public virtual Ranorex.ATag NewDap
            {
                get
                {
                    return _newdapInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The NewDap item info.
            /// </summary>
            [RepositoryItemInfo("1b9c7dfd-ea23-464e-a58b-eb23cab8aeef")]
            public virtual RepoItemInfo NewDapInfo
            {
                get
                {
                    return _newdapInfo;
                }
            }

            /// <summary>
            /// The DapAreaId item.
            /// </summary>
            [RepositoryItem("3b9ee07f-fdc6-4707-bb0e-93619b3c7ae3")]
            public virtual Ranorex.SelectTag DapAreaId
            {
                get
                {
                    return _dapareaidInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The DapAreaId item info.
            /// </summary>
            [RepositoryItemInfo("3b9ee07f-fdc6-4707-bb0e-93619b3c7ae3")]
            public virtual RepoItemInfo DapAreaIdInfo
            {
                get
                {
                    return _dapareaidInfo;
                }
            }

            /// <summary>
            /// The ModalBackdropFadeIn item.
            /// </summary>
            [RepositoryItem("620b4aed-64bf-472a-8bbc-9349e0f58df8")]
            public virtual Ranorex.DivTag ModalBackdropFadeIn
            {
                get
                {
                    return _modalbackdropfadeinInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ModalBackdropFadeIn item info.
            /// </summary>
            [RepositoryItemInfo("620b4aed-64bf-472a-8bbc-9349e0f58df8")]
            public virtual RepoItemInfo ModalBackdropFadeInInfo
            {
                get
                {
                    return _modalbackdropfadeinInfo;
                }
            }

            /// <summary>
            /// The AreaDescription item.
            /// </summary>
            [RepositoryItem("c3dd41cd-c077-4084-9ddd-029408eb30e6")]
            public virtual Ranorex.InputTag AreaDescription
            {
                get
                {
                    return _areadescriptionInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The AreaDescription item info.
            /// </summary>
            [RepositoryItemInfo("c3dd41cd-c077-4084-9ddd-029408eb30e6")]
            public virtual RepoItemInfo AreaDescriptionInfo
            {
                get
                {
                    return _areadescriptionInfo;
                }
            }

            /// <summary>
            /// The AreaState item.
            /// </summary>
            [RepositoryItem("b1b582b0-ef88-478c-ba73-49e5c3125066")]
            public virtual Ranorex.InputTag AreaState
            {
                get
                {
                    return _areastateInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The AreaState item info.
            /// </summary>
            [RepositoryItemInfo("b1b582b0-ef88-478c-ba73-49e5c3125066")]
            public virtual RepoItemInfo AreaStateInfo
            {
                get
                {
                    return _areastateInfo;
                }
            }

            /// <summary>
            /// The AreaCountry item.
            /// </summary>
            [RepositoryItem("ff7bce66-d8ca-4012-b035-075d78716075")]
            public virtual Ranorex.SelectTag AreaCountry
            {
                get
                {
                    return _areacountryInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The AreaCountry item info.
            /// </summary>
            [RepositoryItemInfo("ff7bce66-d8ca-4012-b035-075d78716075")]
            public virtual RepoItemInfo AreaCountryInfo
            {
                get
                {
                    return _areacountryInfo;
                }
            }

            /// <summary>
            /// The NewAreaOkButton item.
            /// </summary>
            [RepositoryItem("30c8c8a0-1736-43ce-b755-d315eba2f789")]
            public virtual Ranorex.ButtonTag NewAreaOkButton
            {
                get
                {
                    return _newareaokbuttonInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The NewAreaOkButton item info.
            /// </summary>
            [RepositoryItemInfo("30c8c8a0-1736-43ce-b755-d315eba2f789")]
            public virtual RepoItemInfo NewAreaOkButtonInfo
            {
                get
                {
                    return _newareaokbuttonInfo;
                }
            }

            /// <summary>
            /// The DapStartNumberAreaCode item.
            /// </summary>
            [RepositoryItem("0773e6c1-12a9-4905-b9dd-a5a1b9c10a7e")]
            public virtual Ranorex.SelectTag DapStartNumberAreaCode
            {
                get
                {
                    return _dapstartnumberareacodeInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The DapStartNumberAreaCode item info.
            /// </summary>
            [RepositoryItemInfo("0773e6c1-12a9-4905-b9dd-a5a1b9c10a7e")]
            public virtual RepoItemInfo DapStartNumberAreaCodeInfo
            {
                get
                {
                    return _dapstartnumberareacodeInfo;
                }
            }

            /// <summary>
            /// The DapStartNumberServiceNumber item.
            /// </summary>
            [RepositoryItem("72b432ec-4ab1-4875-8e42-9aeb31237672")]
            public virtual Ranorex.InputTag DapStartNumberServiceNumber
            {
                get
                {
                    return _dapstartnumberservicenumberInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The DapStartNumberServiceNumber item info.
            /// </summary>
            [RepositoryItemInfo("72b432ec-4ab1-4875-8e42-9aeb31237672")]
            public virtual RepoItemInfo DapStartNumberServiceNumberInfo
            {
                get
                {
                    return _dapstartnumberservicenumberInfo;
                }
            }

            /// <summary>
            /// The DapEndNumberAreaCode item.
            /// </summary>
            [RepositoryItem("05947189-68df-4ed9-a288-970ebbe85066")]
            public virtual Ranorex.SelectTag DapEndNumberAreaCode
            {
                get
                {
                    return _dapendnumberareacodeInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The DapEndNumberAreaCode item info.
            /// </summary>
            [RepositoryItemInfo("05947189-68df-4ed9-a288-970ebbe85066")]
            public virtual RepoItemInfo DapEndNumberAreaCodeInfo
            {
                get
                {
                    return _dapendnumberareacodeInfo;
                }
            }

            /// <summary>
            /// The DapEndNumberServiceNumber item.
            /// </summary>
            [RepositoryItem("1ea2544c-220b-46e7-aec5-d528009fc5e4")]
            public virtual Ranorex.InputTag DapEndNumberServiceNumber
            {
                get
                {
                    return _dapendnumberservicenumberInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The DapEndNumberServiceNumber item info.
            /// </summary>
            [RepositoryItemInfo("1ea2544c-220b-46e7-aec5-d528009fc5e4")]
            public virtual RepoItemInfo DapEndNumberServiceNumberInfo
            {
                get
                {
                    return _dapendnumberservicenumberInfo;
                }
            }

            /// <summary>
            /// The DapSubmitButton item.
            /// </summary>
            [RepositoryItem("574bb672-3e29-47b2-bb0e-b7e77b86a8dc")]
            public virtual Ranorex.ButtonTag DapSubmitButton
            {
                get
                {
                    return _dapsubmitbuttonInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The DapSubmitButton item info.
            /// </summary>
            [RepositoryItemInfo("574bb672-3e29-47b2-bb0e-b7e77b86a8dc")]
            public virtual RepoItemInfo DapSubmitButtonInfo
            {
                get
                {
                    return _dapsubmitbuttonInfo;
                }
            }

            /// <summary>
            /// The ConfirmDapCreationButton item.
            /// </summary>
            [RepositoryItem("a0954b2b-0052-4d3d-9eaf-44bcb3354d7f")]
            public virtual Ranorex.ButtonTag ConfirmDapCreationButton
            {
                get
                {
                    return _confirmdapcreationbuttonInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ConfirmDapCreationButton item info.
            /// </summary>
            [RepositoryItemInfo("a0954b2b-0052-4d3d-9eaf-44bcb3354d7f")]
            public virtual RepoItemInfo ConfirmDapCreationButtonInfo
            {
                get
                {
                    return _confirmdapcreationbuttonInfo;
                }
            }

            /// <summary>
            /// The ProfileDdt item.
            /// </summary>
            [RepositoryItem("036b39c5-f342-4481-8e9c-a8e7cf15a497")]
            public virtual Ranorex.ATag ProfileDdt
            {
                get
                {
                    return _profileddtInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ProfileDdt item info.
            /// </summary>
            [RepositoryItemInfo("036b39c5-f342-4481-8e9c-a8e7cf15a497")]
            public virtual RepoItemInfo ProfileDdtInfo
            {
                get
                {
                    return _profileddtInfo;
                }
            }

            /// <summary>
            /// The DropDownLogout item.
            /// </summary>
            [RepositoryItem("32598150-b4e1-42b2-845a-feff92e58c50")]
            public virtual Ranorex.ATag DropDownLogout
            {
                get
                {
                    return _dropdownlogoutInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The DropDownLogout item info.
            /// </summary>
            [RepositoryItemInfo("32598150-b4e1-42b2-845a-feff92e58c50")]
            public virtual RepoItemInfo DropDownLogoutInfo
            {
                get
                {
                    return _dropdownlogoutInfo;
                }
            }

            /// <summary>
            /// The ContainerAdmin item.
            /// </summary>
            [RepositoryItem("40c27e0b-e7d8-4844-ad0d-c4bd85604cd4")]
            public virtual Ranorex.DivTag ContainerAdmin
            {
                get
                {
                    return _containeradminInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ContainerAdmin item info.
            /// </summary>
            [RepositoryItemInfo("40c27e0b-e7d8-4844-ad0d-c4bd85604cd4")]
            public virtual RepoItemInfo ContainerAdminInfo
            {
                get
                {
                    return _containeradminInfo;
                }
            }

            /// <summary>
            /// The AccountTab item.
            /// </summary>
            [RepositoryItem("d0f108ec-4cc8-4162-be0d-e363a9d476e8")]
            public virtual Ranorex.ATag AccountTab
            {
                get
                {
                    return _accounttabInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The AccountTab item info.
            /// </summary>
            [RepositoryItemInfo("d0f108ec-4cc8-4162-be0d-e363a9d476e8")]
            public virtual RepoItemInfo AccountTabInfo
            {
                get
                {
                    return _accounttabInfo;
                }
            }

            /// <summary>
            /// The NewAccount item.
            /// </summary>
            [RepositoryItem("3913aa06-6f2a-413b-9261-9b751d859170")]
            public virtual Ranorex.ATag NewAccount
            {
                get
                {
                    return _newaccountInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The NewAccount item info.
            /// </summary>
            [RepositoryItemInfo("3913aa06-6f2a-413b-9261-9b751d859170")]
            public virtual RepoItemInfo NewAccountInfo
            {
                get
                {
                    return _newaccountInfo;
                }
            }

            /// <summary>
            /// The AccountName item.
            /// </summary>
            [RepositoryItem("e4721a3f-137a-43c7-9bb7-9e955fd934cd")]
            public virtual Ranorex.InputTag AccountName
            {
                get
                {
                    return _accountnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The AccountName item info.
            /// </summary>
            [RepositoryItemInfo("e4721a3f-137a-43c7-9bb7-9e955fd934cd")]
            public virtual RepoItemInfo AccountNameInfo
            {
                get
                {
                    return _accountnameInfo;
                }
            }

            /// <summary>
            /// The AccountDubberAddress item.
            /// </summary>
            [RepositoryItem("4d61d999-ba23-4368-a6c9-ab688dae127f")]
            public virtual Ranorex.InputTag AccountDubberAddress
            {
                get
                {
                    return _accountdubberaddressInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The AccountDubberAddress item info.
            /// </summary>
            [RepositoryItemInfo("4d61d999-ba23-4368-a6c9-ab688dae127f")]
            public virtual RepoItemInfo AccountDubberAddressInfo
            {
                get
                {
                    return _accountdubberaddressInfo;
                }
            }

            /// <summary>
            /// The AccountExternalReference item.
            /// </summary>
            [RepositoryItem("d6772cd5-7203-46f8-9b77-670b9674bec7")]
            public virtual Ranorex.InputTag AccountExternalReference
            {
                get
                {
                    return _accountexternalreferenceInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The AccountExternalReference item info.
            /// </summary>
            [RepositoryItemInfo("d6772cd5-7203-46f8-9b77-670b9674bec7")]
            public virtual RepoItemInfo AccountExternalReferenceInfo
            {
                get
                {
                    return _accountexternalreferenceInfo;
                }
            }

            /// <summary>
            /// The AccountTimeZone item.
            /// </summary>
            [RepositoryItem("d9268121-7036-48c5-a911-06fcc0f5f413")]
            public virtual Ranorex.SelectTag AccountTimeZone
            {
                get
                {
                    return _accounttimezoneInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The AccountTimeZone item info.
            /// </summary>
            [RepositoryItemInfo("d9268121-7036-48c5-a911-06fcc0f5f413")]
            public virtual RepoItemInfo AccountTimeZoneInfo
            {
                get
                {
                    return _accounttimezoneInfo;
                }
            }

            /// <summary>
            /// The AccountAddressAttributesAddress item.
            /// </summary>
            [RepositoryItem("1dfbf7ea-fa99-4f20-a460-b3cbafe1de3c")]
            public virtual Ranorex.InputTag AccountAddressAttributesAddress
            {
                get
                {
                    return _accountaddressattributesaddressInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The AccountAddressAttributesAddress item info.
            /// </summary>
            [RepositoryItemInfo("1dfbf7ea-fa99-4f20-a460-b3cbafe1de3c")]
            public virtual RepoItemInfo AccountAddressAttributesAddressInfo
            {
                get
                {
                    return _accountaddressattributesaddressInfo;
                }
            }

            /// <summary>
            /// The AccountAddressAttributesSuburb item.
            /// </summary>
            [RepositoryItem("24dfc774-490e-4baa-bfc8-9c451349f113")]
            public virtual Ranorex.InputTag AccountAddressAttributesSuburb
            {
                get
                {
                    return _accountaddressattributessuburbInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The AccountAddressAttributesSuburb item info.
            /// </summary>
            [RepositoryItemInfo("24dfc774-490e-4baa-bfc8-9c451349f113")]
            public virtual RepoItemInfo AccountAddressAttributesSuburbInfo
            {
                get
                {
                    return _accountaddressattributessuburbInfo;
                }
            }

            /// <summary>
            /// The AccountAddressAttributesCountry item.
            /// </summary>
            [RepositoryItem("ced0c677-f83d-4933-ab79-7229e777d789")]
            public virtual Ranorex.SelectTag AccountAddressAttributesCountry
            {
                get
                {
                    return _accountaddressattributescountryInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The AccountAddressAttributesCountry item info.
            /// </summary>
            [RepositoryItemInfo("ced0c677-f83d-4933-ab79-7229e777d789")]
            public virtual RepoItemInfo AccountAddressAttributesCountryInfo
            {
                get
                {
                    return _accountaddressattributescountryInfo;
                }
            }

            /// <summary>
            /// The AccountAddressAttributesPostCode item.
            /// </summary>
            [RepositoryItem("e2b758fd-2cfa-44e4-99b6-12064fbbeed8")]
            public virtual Ranorex.InputTag AccountAddressAttributesPostCode
            {
                get
                {
                    return _accountaddressattributespostcodeInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The AccountAddressAttributesPostCode item info.
            /// </summary>
            [RepositoryItemInfo("e2b758fd-2cfa-44e4-99b6-12064fbbeed8")]
            public virtual RepoItemInfo AccountAddressAttributesPostCodeInfo
            {
                get
                {
                    return _accountaddressattributespostcodeInfo;
                }
            }

            /// <summary>
            /// The AccountPhoneAreaCode item.
            /// </summary>
            [RepositoryItem("31b4bd0d-55d2-41cd-8a55-bfaec47c9e27")]
            public virtual Ranorex.SelectTag AccountPhoneAreaCode
            {
                get
                {
                    return _accountphoneareacodeInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The AccountPhoneAreaCode item info.
            /// </summary>
            [RepositoryItemInfo("31b4bd0d-55d2-41cd-8a55-bfaec47c9e27")]
            public virtual RepoItemInfo AccountPhoneAreaCodeInfo
            {
                get
                {
                    return _accountphoneareacodeInfo;
                }
            }

            /// <summary>
            /// The AccountPhoneServiceNumber item.
            /// </summary>
            [RepositoryItem("f21cefc0-55b6-4009-8e44-8ee66134373d")]
            public virtual Ranorex.InputTag AccountPhoneServiceNumber
            {
                get
                {
                    return _accountphoneservicenumberInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The AccountPhoneServiceNumber item info.
            /// </summary>
            [RepositoryItemInfo("f21cefc0-55b6-4009-8e44-8ee66134373d")]
            public virtual RepoItemInfo AccountPhoneServiceNumberInfo
            {
                get
                {
                    return _accountphoneservicenumberInfo;
                }
            }

            /// <summary>
            /// The AccountAccountUsersAttributes0Email item.
            /// </summary>
            [RepositoryItem("037bb8ad-be72-4d7e-aaac-bed9954f11a0")]
            public virtual Ranorex.InputTag AccountAccountUsersAttributes0Email
            {
                get
                {
                    return _accountaccountusersattributes0emailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The AccountAccountUsersAttributes0Email item info.
            /// </summary>
            [RepositoryItemInfo("037bb8ad-be72-4d7e-aaac-bed9954f11a0")]
            public virtual RepoItemInfo AccountAccountUsersAttributes0EmailInfo
            {
                get
                {
                    return _accountaccountusersattributes0emailInfo;
                }
            }

            /// <summary>
            /// The AccountAccountUsersAttributes0Email1 item.
            /// </summary>
            [RepositoryItem("4a9c3e83-abc8-4de5-a7d6-1fcf3fcfef9a")]
            public virtual Ranorex.InputTag AccountAccountUsersAttributes0Email1
            {
                get
                {
                    return _accountaccountusersattributes0email1Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The AccountAccountUsersAttributes0Email1 item info.
            /// </summary>
            [RepositoryItemInfo("4a9c3e83-abc8-4de5-a7d6-1fcf3fcfef9a")]
            public virtual RepoItemInfo AccountAccountUsersAttributes0Email1Info
            {
                get
                {
                    return _accountaccountusersattributes0email1Info;
                }
            }

            /// <summary>
            /// The AccountAccountUsersAttributes0First item.
            /// </summary>
            [RepositoryItem("485ed98a-6940-4be3-a4ae-a7cbf2a96558")]
            public virtual Ranorex.InputTag AccountAccountUsersAttributes0First
            {
                get
                {
                    return _accountaccountusersattributes0firstInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The AccountAccountUsersAttributes0First item info.
            /// </summary>
            [RepositoryItemInfo("485ed98a-6940-4be3-a4ae-a7cbf2a96558")]
            public virtual RepoItemInfo AccountAccountUsersAttributes0FirstInfo
            {
                get
                {
                    return _accountaccountusersattributes0firstInfo;
                }
            }

            /// <summary>
            /// The AccountAccountUsersAttributes0Last item.
            /// </summary>
            [RepositoryItem("e2d072a4-2f99-4097-a848-b7ba86917c28")]
            public virtual Ranorex.InputTag AccountAccountUsersAttributes0Last
            {
                get
                {
                    return _accountaccountusersattributes0lastInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The AccountAccountUsersAttributes0Last item info.
            /// </summary>
            [RepositoryItemInfo("e2d072a4-2f99-4097-a848-b7ba86917c28")]
            public virtual RepoItemInfo AccountAccountUsersAttributes0LastInfo
            {
                get
                {
                    return _accountaccountusersattributes0lastInfo;
                }
            }

            /// <summary>
            /// The AccountSubmitButton item.
            /// </summary>
            [RepositoryItem("5e04eb44-a10a-4320-a85a-90201a746f6d")]
            public virtual Ranorex.ButtonTag AccountSubmitButton
            {
                get
                {
                    return _accountsubmitbuttonInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The AccountSubmitButton item info.
            /// </summary>
            [RepositoryItemInfo("5e04eb44-a10a-4320-a85a-90201a746f6d")]
            public virtual RepoItemInfo AccountSubmitButtonInfo
            {
                get
                {
                    return _accountsubmitbuttonInfo;
                }
            }

            /// <summary>
            /// The AccountAddressAttributesState item.
            /// </summary>
            [RepositoryItem("4f088292-f818-44e4-b434-08001de66980")]
            public virtual Ranorex.SelectTag AccountAddressAttributesState
            {
                get
                {
                    return _accountaddressattributesstateInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The AccountAddressAttributesState item info.
            /// </summary>
            [RepositoryItemInfo("4f088292-f818-44e4-b434-08001de66980")]
            public virtual RepoItemInfo AccountAddressAttributesStateInfo
            {
                get
                {
                    return _accountaddressattributesstateInfo;
                }
            }

            /// <summary>
            /// The InboundNumberArea item.
            /// </summary>
            [RepositoryItem("4b978ceb-65d1-4475-9443-d739f40392a4")]
            public virtual Ranorex.SelectTag InboundNumberArea
            {
                get
                {
                    return _inboundnumberareaInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The InboundNumberArea item info.
            /// </summary>
            [RepositoryItemInfo("4b978ceb-65d1-4475-9443-d739f40392a4")]
            public virtual RepoItemInfo InboundNumberAreaInfo
            {
                get
                {
                    return _inboundnumberareaInfo;
                }
            }

            /// <summary>
            /// The InboundNumberDapId item.
            /// </summary>
            [RepositoryItem("624fb984-9c89-4755-975a-c20350177fae")]
            public virtual Ranorex.SelectTag InboundNumberDapId
            {
                get
                {
                    return _inboundnumberdapidInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The InboundNumberDapId item info.
            /// </summary>
            [RepositoryItemInfo("624fb984-9c89-4755-975a-c20350177fae")]
            public virtual RepoItemInfo InboundNumberDapIdInfo
            {
                get
                {
                    return _inboundnumberdapidInfo;
                }
            }

            /// <summary>
            /// The InboundNumberNumberServiceNumber item.
            /// </summary>
            [RepositoryItem("ed73ca62-4017-4c4c-927e-756665833022")]
            public virtual Ranorex.InputTag InboundNumberNumberServiceNumber
            {
                get
                {
                    return _inboundnumbernumberservicenumberInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The InboundNumberNumberServiceNumber item info.
            /// </summary>
            [RepositoryItemInfo("ed73ca62-4017-4c4c-927e-756665833022")]
            public virtual RepoItemInfo InboundNumberNumberServiceNumberInfo
            {
                get
                {
                    return _inboundnumbernumberservicenumberInfo;
                }
            }

            /// <summary>
            /// The InboundNumberLabel item.
            /// </summary>
            [RepositoryItem("658b0e47-3867-46a0-b984-6f622045d63a")]
            public virtual Ranorex.InputTag InboundNumberLabel
            {
                get
                {
                    return _inboundnumberlabelInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The InboundNumberLabel item info.
            /// </summary>
            [RepositoryItemInfo("658b0e47-3867-46a0-b984-6f622045d63a")]
            public virtual RepoItemInfo InboundNumberLabelInfo
            {
                get
                {
                    return _inboundnumberlabelInfo;
                }
            }

            /// <summary>
            /// The InboundNumberCapDubPointsAttributes item.
            /// </summary>
            [RepositoryItem("e816da5c-31b4-49dd-bc51-53620364b75d")]
            public virtual Ranorex.InputTag InboundNumberCapDubPointsAttributes
            {
                get
                {
                    return _inboundnumbercapdubpointsattributesInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The InboundNumberCapDubPointsAttributes item info.
            /// </summary>
            [RepositoryItemInfo("e816da5c-31b4-49dd-bc51-53620364b75d")]
            public virtual RepoItemInfo InboundNumberCapDubPointsAttributesInfo
            {
                get
                {
                    return _inboundnumbercapdubpointsattributesInfo;
                }
            }

            /// <summary>
            /// The InboundNumberCapDubPointsAttributes1 item.
            /// </summary>
            [RepositoryItem("ba051188-c600-4fbc-aebb-5df32bdd7795")]
            public virtual Ranorex.InputTag InboundNumberCapDubPointsAttributes1
            {
                get
                {
                    return _inboundnumbercapdubpointsattributes1Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The InboundNumberCapDubPointsAttributes1 item info.
            /// </summary>
            [RepositoryItemInfo("ba051188-c600-4fbc-aebb-5df32bdd7795")]
            public virtual RepoItemInfo InboundNumberCapDubPointsAttributes1Info
            {
                get
                {
                    return _inboundnumbercapdubpointsattributes1Info;
                }
            }

            /// <summary>
            /// The InboundNumberSubmitButton item.
            /// </summary>
            [RepositoryItem("ce45f769-7f8a-4b41-886f-dc2862502164")]
            public virtual Ranorex.ButtonTag InboundNumberSubmitButton
            {
                get
                {
                    return _inboundnumbersubmitbuttonInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The InboundNumberSubmitButton item info.
            /// </summary>
            [RepositoryItemInfo("ce45f769-7f8a-4b41-886f-dc2862502164")]
            public virtual RepoItemInfo InboundNumberSubmitButtonInfo
            {
                get
                {
                    return _inboundnumbersubmitbuttonInfo;
                }
            }

            /// <summary>
            /// The Caret item.
            /// </summary>
            [RepositoryItem("7d80543f-f2e3-441e-add6-e126844c30fd")]
            public virtual Ranorex.SpanTag Caret
            {
                get
                {
                    return _caretInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Caret item info.
            /// </summary>
            [RepositoryItemInfo("7d80543f-f2e3-441e-add6-e126844c30fd")]
            public virtual RepoItemInfo CaretInfo
            {
                get
                {
                    return _caretInfo;
                }
            }
        }

        /// <summary>
        /// The DISPLAY1LowerRightAppFolder folder.
        /// </summary>
        [RepositoryFolder("9972aef6-a7be-4246-a552-8033cd36ed9c")]
        public partial class DISPLAY1LowerRightAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new DISPLAY1LowerRight  folder.
            /// </summary>
            public DISPLAY1LowerRightAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DISPLAY1LowerRight", "/grip[@name='DISPLAY1 LowerRight']", parentFolder, 30000, null, true, "9972aef6-a7be-4246-a552-8033cd36ed9c", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9972aef6-a7be-4246-a552-8033cd36ed9c")]
            public virtual Ranorex.Grip Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Grip>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9972aef6-a7be-4246-a552-8033cd36ed9c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The DownloadsAppFolder folder.
        /// </summary>
        [RepositoryFolder("d6928b19-d5fc-4f9c-b0ea-cb4cf4474edc")]
        public partial class DownloadsAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _systemitemnamedisplayInfo;
            RepoItemInfo _editInfo;
            RepoItemInfo _itemsviewInfo;

            /// <summary>
            /// Creates a new Downloads  folder.
            /// </summary>
            public DownloadsAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Downloads", "/form[@title='Downloads']", parentFolder, 30000, null, true, "d6928b19-d5fc-4f9c-b0ea-cb4cf4474edc", "")
            {
                _systemitemnamedisplayInfo = new RepoItemInfo(this, "SystemItemNameDisplay", "element[@class='ShellTabWindowClass']//container[@caption='ShellView']/?/?/listitem[@automationid='5']/text[@automationid='System.ItemNameDisplay']", 30000, null, "6a9fecb2-63a7-4136-95c0-ee9daad0fbb6");
                _editInfo = new RepoItemInfo(this, "Edit", "element[@class='ShellTabWindowClass']//container[@caption='ShellView']/?/?/element[@instance='0']/text[@class='Edit']", 30000, null, "9ae0d6d0-148d-48a0-b3fa-fe68a0d229b2");
                _itemsviewInfo = new RepoItemInfo(this, "ItemsView", "element[@class='ShellTabWindowClass']//element[@instance='1']/container[@caption='ShellView']/?/?/list[@accessiblename='Items View']", 30000, null, "9f7099fd-7cbf-433f-bde9-6b76c3a631da");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d6928b19-d5fc-4f9c-b0ea-cb4cf4474edc")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d6928b19-d5fc-4f9c-b0ea-cb4cf4474edc")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SystemItemNameDisplay item.
            /// </summary>
            [RepositoryItem("6a9fecb2-63a7-4136-95c0-ee9daad0fbb6")]
            public virtual Ranorex.Text SystemItemNameDisplay
            {
                get
                {
                    return _systemitemnamedisplayInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SystemItemNameDisplay item info.
            /// </summary>
            [RepositoryItemInfo("6a9fecb2-63a7-4136-95c0-ee9daad0fbb6")]
            public virtual RepoItemInfo SystemItemNameDisplayInfo
            {
                get
                {
                    return _systemitemnamedisplayInfo;
                }
            }

            /// <summary>
            /// The Edit item.
            /// </summary>
            [RepositoryItem("9ae0d6d0-148d-48a0-b3fa-fe68a0d229b2")]
            public virtual Ranorex.Text Edit
            {
                get
                {
                    return _editInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Edit item info.
            /// </summary>
            [RepositoryItemInfo("9ae0d6d0-148d-48a0-b3fa-fe68a0d229b2")]
            public virtual RepoItemInfo EditInfo
            {
                get
                {
                    return _editInfo;
                }
            }

            /// <summary>
            /// The ItemsView item.
            /// </summary>
            [RepositoryItem("9f7099fd-7cbf-433f-bde9-6b76c3a631da")]
            public virtual Ranorex.List ItemsView
            {
                get
                {
                    return _itemsviewInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The ItemsView item info.
            /// </summary>
            [RepositoryItemInfo("9f7099fd-7cbf-433f-bde9-6b76c3a631da")]
            public virtual RepoItemInfo ItemsViewInfo
            {
                get
                {
                    return _itemsviewInfo;
                }
            }
        }

        /// <summary>
        /// The InbCallflow3NotepadAppFolder folder.
        /// </summary>
        [RepositoryFolder("3561f37a-c6dc-4012-91de-92d708ef5cea")]
        public partial class InbCallflow3NotepadAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new InbCallflow3Notepad  folder.
            /// </summary>
            public InbCallflow3NotepadAppFolder(RepoGenBaseFolder parentFolder) :
                    base("InbCallflow3Notepad", "/form[@title='inb-Callflow(3) - Notepad']", parentFolder, 30000, null, true, "3561f37a-c6dc-4012-91de-92d708ef5cea", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3561f37a-c6dc-4012-91de-92d708ef5cea")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3561f37a-c6dc-4012-91de-92d708ef5cea")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The NotepadAppFolder folder.
        /// </summary>
        [RepositoryFolder("2fe476ff-6224-40d8-9f0f-0eda10964e68")]
        public partial class NotepadAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new Notepad  folder.
            /// </summary>
            public NotepadAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Notepad", "/contextmenu[@processname='notepad']", parentFolder, 30000, null, true, "2fe476ff-6224-40d8-9f0f-0eda10964e68", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2fe476ff-6224-40d8-9f0f-0eda10964e68")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2fe476ff-6224-40d8-9f0f-0eda10964e68")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The DropdownAppFolder folder.
        /// </summary>
        [RepositoryFolder("33c7bbd1-8b21-4049-b3ba-b5eba1425d2b")]
        public partial class DropdownAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new Dropdown  folder.
            /// </summary>
            public DropdownAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Dropdown", "/container[@caption='dropdown']", parentFolder, 30000, null, true, "33c7bbd1-8b21-4049-b3ba-b5eba1425d2b", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("33c7bbd1-8b21-4049-b3ba-b5eba1425d2b")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("33c7bbd1-8b21-4049-b3ba-b5eba1425d2b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}