///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace dubber
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the dubberrepo element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    [RepositoryFolder("dddd0643-c8d0-451b-9916-cdf49139cdd5")]
    public partial class dubberrepo : RepoGenBaseFolder
    {
        static dubberrepo instance = new dubberrepo();
        dubberrepoFolders.DubberAppFolder _dubber;
        dubberrepoFolders.DropdownAppFolder _dropdown;
        dubberrepoFolders.DubberGoogleChromeAppFolder _dubbergooglechrome;
        dubberrepoFolders.DubberMozillaFirefoxAppFolder _dubbermozillafirefox;

        /// <summary>
        /// Gets the singleton class instance representing the dubberrepo element repository.
        /// </summary>
        [RepositoryFolder("dddd0643-c8d0-451b-9916-cdf49139cdd5")]
        public static dubberrepo Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public dubberrepo() 
            : base("dubberrepo", "/", null, 0, false, "dddd0643-c8d0-451b-9916-cdf49139cdd5", ".\\RepositoryImages\\dubberrepodddd0643.rximgres")
        {
            _dubber = new dubberrepoFolders.DubberAppFolder(this);
            _dropdown = new dubberrepoFolders.DropdownAppFolder(this);
            _dubbergooglechrome = new dubberrepoFolders.DubberGoogleChromeAppFolder(this);
            _dubbermozillafirefox = new dubberrepoFolders.DubberMozillaFirefoxAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("dddd0643-c8d0-451b-9916-cdf49139cdd5")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Dubber folder.
        /// </summary>
        [RepositoryFolder("1e2d1a6e-67e0-4618-aa94-425e38fd2401")]
        public virtual dubberrepoFolders.DubberAppFolder Dubber
        {
            get { return _dubber; }
        }

        /// <summary>
        /// The Dropdown folder.
        /// </summary>
        [RepositoryFolder("3d5dbb8d-18fd-443f-9f45-e2f60f588bf0")]
        public virtual dubberrepoFolders.DropdownAppFolder Dropdown
        {
            get { return _dropdown; }
        }

        /// <summary>
        /// The DubberGoogleChrome folder.
        /// </summary>
        [RepositoryFolder("74855ecc-d7bf-49ff-b90a-acd1bd6d4fa7")]
        public virtual dubberrepoFolders.DubberGoogleChromeAppFolder DubberGoogleChrome
        {
            get { return _dubbergooglechrome; }
        }

        /// <summary>
        /// The DubberMozillaFirefox folder.
        /// </summary>
        [RepositoryFolder("e4317e8e-ed4d-4517-bb69-4fa3e9cf3c26")]
        public virtual dubberrepoFolders.DubberMozillaFirefoxAppFolder DubberMozillaFirefox
        {
            get { return _dubbermozillafirefox; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    public partial class dubberrepoFolders
    {
        /// <summary>
        /// The DubberAppFolder folder.
        /// </summary>
        [RepositoryFolder("1e2d1a6e-67e0-4618-aa94-425e38fd2401")]
        public partial class DubberAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _userpasswordInfo;
            RepoItemInfo _useremailInfo;
            RepoItemInfo _contentboxInfo;
            RepoItemInfo _submitbuttonInfo;
            RepoItemInfo _managedapsbuttonInfo;
            RepoItemInfo _newdapInfo;
            RepoItemInfo _dapareaidInfo;
            RepoItemInfo _modalbackdropfadeinInfo;
            RepoItemInfo _areadescriptionInfo;
            RepoItemInfo _areastateInfo;
            RepoItemInfo _areacountryInfo;
            RepoItemInfo _newareaokbuttonInfo;
            RepoItemInfo _dapstartnumberareacodeInfo;
            RepoItemInfo _dapstartnumberservicenumberInfo;
            RepoItemInfo _dapendnumberareacodeInfo;
            RepoItemInfo _dapendnumberservicenumberInfo;
            RepoItemInfo _dapsubmitbuttonInfo;
            RepoItemInfo _confirmdapcreationbuttonInfo;
            RepoItemInfo _profileddtInfo;
            RepoItemInfo _dropdownlogoutInfo;

            /// <summary>
            /// Creates a new Dubber  folder.
            /// </summary>
            public DubberAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Dubber", "/dom[@domain='tigers.dubber.net']", parentFolder, 30000, null, false, "1e2d1a6e-67e0-4618-aa94-425e38fd2401", "")
            {
                _userpasswordInfo = new RepoItemInfo(this, "UserPassword", ".//input[#'user_password']", 30000, null, "09274fb3-3bac-4216-806b-0421adaf1d74");
                _useremailInfo = new RepoItemInfo(this, "UserEmail", ".//input[#'user_email']", 30000, null, "7d2acc5a-7e91-4627-af56-de4c3be058d6");
                _contentboxInfo = new RepoItemInfo(this, "ContentBox", ".//div[#'main_body']/div[1]/div/div[2]", 30000, null, "ff30482e-4d10-4f79-84d7-257779387293");
                _submitbuttonInfo = new RepoItemInfo(this, "SubmitButton", ".//input[#'submit_button']", 30000, null, "b7bcb5bf-4ab8-4492-b827-3ae47cab7a81");
                _managedapsbuttonInfo = new RepoItemInfo(this, "ManageDapsButton", ".//a[#'manage_daps_button']", 30000, null, "cf08cc1a-f5ba-4f99-811d-becdc7e4340e");
                _newdapInfo = new RepoItemInfo(this, "NewDap", ".//a[#'new_dap']", 30000, null, "f4bfe14d-cc5f-4082-bae4-ff926892688d");
                _dapareaidInfo = new RepoItemInfo(this, "DapAreaId", ".//select[#'dap_area_id']", 30000, null, "e88238dd-4fef-46b7-8cbe-5052a97aeb68");
                _modalbackdropfadeinInfo = new RepoItemInfo(this, "ModalBackdropFadeIn", "body/div[6]", 30000, null, "d6de6280-2f66-4950-9f90-cd1209901521");
                _areadescriptionInfo = new RepoItemInfo(this, "AreaDescription", ".//input[#'area_description']", 30000, null, "c4ca659e-744f-4b4c-bc45-ba026b11bd41");
                _areastateInfo = new RepoItemInfo(this, "AreaState", ".//input[#'area_state']", 30000, null, "1ff40021-5d58-41ca-9bab-3a4e62e9658c");
                _areacountryInfo = new RepoItemInfo(this, "AreaCountry", ".//select[#'area_country']", 30000, null, "cfba52f7-f914-4a9b-a8de-16f24b6e0f29");
                _newareaokbuttonInfo = new RepoItemInfo(this, "NewAreaOkButton", ".//button[#'new_area_ok_button']", 30000, null, "2eba40d0-8a87-4526-b43d-3b446ed41b05");
                _dapstartnumberareacodeInfo = new RepoItemInfo(this, "DapStartNumberAreaCode", ".//select[#'dap_start_number_area_code']", 30000, null, "3e7d8f9b-80f1-496c-aba6-be0334a3f0b9");
                _dapstartnumberservicenumberInfo = new RepoItemInfo(this, "DapStartNumberServiceNumber", ".//input[#'dap_start_number_service_number']", 30000, null, "b530c0de-87eb-42c2-83a4-9a6f3ce1fbeb");
                _dapendnumberareacodeInfo = new RepoItemInfo(this, "DapEndNumberAreaCode", ".//select[#'dap_end_number_area_code']", 30000, null, "63a490ee-1a70-4efd-9b92-2ee7444e285c");
                _dapendnumberservicenumberInfo = new RepoItemInfo(this, "DapEndNumberServiceNumber", ".//input[#'dap_end_number_service_number']", 30000, null, "2870da23-c8d8-41fe-a08b-ae2b133bcb65");
                _dapsubmitbuttonInfo = new RepoItemInfo(this, "DapSubmitButton", ".//button[#'dap_submit_button']", 30000, null, "5e7cf7df-c4d9-4643-a062-af6b934827da");
                _confirmdapcreationbuttonInfo = new RepoItemInfo(this, "ConfirmDapCreationButton", ".//button[#'confirm_dap_creation_button']", 30000, null, "bd372775-a873-4fc0-b59a-604273934984");
                _profileddtInfo = new RepoItemInfo(this, "ProfileDdt", ".//a[#'profile-ddt']", 30000, null, "d38ea138-8e52-4c09-b07c-052c42b6d72d");
                _dropdownlogoutInfo = new RepoItemInfo(this, "DropDownLogout", ".//a[#'drop_down_logout']", 30000, null, "1f6e4afa-0eb7-4689-b883-4f114936a726");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1e2d1a6e-67e0-4618-aa94-425e38fd2401")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1e2d1a6e-67e0-4618-aa94-425e38fd2401")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The UserPassword item.
            /// </summary>
            [RepositoryItem("09274fb3-3bac-4216-806b-0421adaf1d74")]
            public virtual Ranorex.InputTag UserPassword
            {
                get
                {
                    return _userpasswordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The UserPassword item info.
            /// </summary>
            [RepositoryItemInfo("09274fb3-3bac-4216-806b-0421adaf1d74")]
            public virtual RepoItemInfo UserPasswordInfo
            {
                get
                {
                    return _userpasswordInfo;
                }
            }

            /// <summary>
            /// The UserEmail item.
            /// </summary>
            [RepositoryItem("7d2acc5a-7e91-4627-af56-de4c3be058d6")]
            public virtual Ranorex.InputTag UserEmail
            {
                get
                {
                    return _useremailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The UserEmail item info.
            /// </summary>
            [RepositoryItemInfo("7d2acc5a-7e91-4627-af56-de4c3be058d6")]
            public virtual RepoItemInfo UserEmailInfo
            {
                get
                {
                    return _useremailInfo;
                }
            }

            /// <summary>
            /// The ContentBox item.
            /// </summary>
            [RepositoryItem("ff30482e-4d10-4f79-84d7-257779387293")]
            public virtual Ranorex.DivTag ContentBox
            {
                get
                {
                    return _contentboxInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ContentBox item info.
            /// </summary>
            [RepositoryItemInfo("ff30482e-4d10-4f79-84d7-257779387293")]
            public virtual RepoItemInfo ContentBoxInfo
            {
                get
                {
                    return _contentboxInfo;
                }
            }

            /// <summary>
            /// The SubmitButton item.
            /// </summary>
            [RepositoryItem("b7bcb5bf-4ab8-4492-b827-3ae47cab7a81")]
            public virtual Ranorex.InputTag SubmitButton
            {
                get
                {
                    return _submitbuttonInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The SubmitButton item info.
            /// </summary>
            [RepositoryItemInfo("b7bcb5bf-4ab8-4492-b827-3ae47cab7a81")]
            public virtual RepoItemInfo SubmitButtonInfo
            {
                get
                {
                    return _submitbuttonInfo;
                }
            }

            /// <summary>
            /// The ManageDapsButton item.
            /// </summary>
            [RepositoryItem("cf08cc1a-f5ba-4f99-811d-becdc7e4340e")]
            public virtual Ranorex.ATag ManageDapsButton
            {
                get
                {
                    return _managedapsbuttonInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ManageDapsButton item info.
            /// </summary>
            [RepositoryItemInfo("cf08cc1a-f5ba-4f99-811d-becdc7e4340e")]
            public virtual RepoItemInfo ManageDapsButtonInfo
            {
                get
                {
                    return _managedapsbuttonInfo;
                }
            }

            /// <summary>
            /// The NewDap item.
            /// </summary>
            [RepositoryItem("f4bfe14d-cc5f-4082-bae4-ff926892688d")]
            public virtual Ranorex.ATag NewDap
            {
                get
                {
                    return _newdapInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The NewDap item info.
            /// </summary>
            [RepositoryItemInfo("f4bfe14d-cc5f-4082-bae4-ff926892688d")]
            public virtual RepoItemInfo NewDapInfo
            {
                get
                {
                    return _newdapInfo;
                }
            }

            /// <summary>
            /// The DapAreaId item.
            /// </summary>
            [RepositoryItem("e88238dd-4fef-46b7-8cbe-5052a97aeb68")]
            public virtual Ranorex.SelectTag DapAreaId
            {
                get
                {
                    return _dapareaidInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The DapAreaId item info.
            /// </summary>
            [RepositoryItemInfo("e88238dd-4fef-46b7-8cbe-5052a97aeb68")]
            public virtual RepoItemInfo DapAreaIdInfo
            {
                get
                {
                    return _dapareaidInfo;
                }
            }

            /// <summary>
            /// The ModalBackdropFadeIn item.
            /// </summary>
            [RepositoryItem("d6de6280-2f66-4950-9f90-cd1209901521")]
            public virtual Ranorex.DivTag ModalBackdropFadeIn
            {
                get
                {
                    return _modalbackdropfadeinInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ModalBackdropFadeIn item info.
            /// </summary>
            [RepositoryItemInfo("d6de6280-2f66-4950-9f90-cd1209901521")]
            public virtual RepoItemInfo ModalBackdropFadeInInfo
            {
                get
                {
                    return _modalbackdropfadeinInfo;
                }
            }

            /// <summary>
            /// The AreaDescription item.
            /// </summary>
            [RepositoryItem("c4ca659e-744f-4b4c-bc45-ba026b11bd41")]
            public virtual Ranorex.InputTag AreaDescription
            {
                get
                {
                    return _areadescriptionInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The AreaDescription item info.
            /// </summary>
            [RepositoryItemInfo("c4ca659e-744f-4b4c-bc45-ba026b11bd41")]
            public virtual RepoItemInfo AreaDescriptionInfo
            {
                get
                {
                    return _areadescriptionInfo;
                }
            }

            /// <summary>
            /// The AreaState item.
            /// </summary>
            [RepositoryItem("1ff40021-5d58-41ca-9bab-3a4e62e9658c")]
            public virtual Ranorex.InputTag AreaState
            {
                get
                {
                    return _areastateInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The AreaState item info.
            /// </summary>
            [RepositoryItemInfo("1ff40021-5d58-41ca-9bab-3a4e62e9658c")]
            public virtual RepoItemInfo AreaStateInfo
            {
                get
                {
                    return _areastateInfo;
                }
            }

            /// <summary>
            /// The AreaCountry item.
            /// </summary>
            [RepositoryItem("cfba52f7-f914-4a9b-a8de-16f24b6e0f29")]
            public virtual Ranorex.SelectTag AreaCountry
            {
                get
                {
                    return _areacountryInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The AreaCountry item info.
            /// </summary>
            [RepositoryItemInfo("cfba52f7-f914-4a9b-a8de-16f24b6e0f29")]
            public virtual RepoItemInfo AreaCountryInfo
            {
                get
                {
                    return _areacountryInfo;
                }
            }

            /// <summary>
            /// The NewAreaOkButton item.
            /// </summary>
            [RepositoryItem("2eba40d0-8a87-4526-b43d-3b446ed41b05")]
            public virtual Ranorex.ButtonTag NewAreaOkButton
            {
                get
                {
                    return _newareaokbuttonInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The NewAreaOkButton item info.
            /// </summary>
            [RepositoryItemInfo("2eba40d0-8a87-4526-b43d-3b446ed41b05")]
            public virtual RepoItemInfo NewAreaOkButtonInfo
            {
                get
                {
                    return _newareaokbuttonInfo;
                }
            }

            /// <summary>
            /// The DapStartNumberAreaCode item.
            /// </summary>
            [RepositoryItem("3e7d8f9b-80f1-496c-aba6-be0334a3f0b9")]
            public virtual Ranorex.SelectTag DapStartNumberAreaCode
            {
                get
                {
                    return _dapstartnumberareacodeInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The DapStartNumberAreaCode item info.
            /// </summary>
            [RepositoryItemInfo("3e7d8f9b-80f1-496c-aba6-be0334a3f0b9")]
            public virtual RepoItemInfo DapStartNumberAreaCodeInfo
            {
                get
                {
                    return _dapstartnumberareacodeInfo;
                }
            }

            /// <summary>
            /// The DapStartNumberServiceNumber item.
            /// </summary>
            [RepositoryItem("b530c0de-87eb-42c2-83a4-9a6f3ce1fbeb")]
            public virtual Ranorex.InputTag DapStartNumberServiceNumber
            {
                get
                {
                    return _dapstartnumberservicenumberInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The DapStartNumberServiceNumber item info.
            /// </summary>
            [RepositoryItemInfo("b530c0de-87eb-42c2-83a4-9a6f3ce1fbeb")]
            public virtual RepoItemInfo DapStartNumberServiceNumberInfo
            {
                get
                {
                    return _dapstartnumberservicenumberInfo;
                }
            }

            /// <summary>
            /// The DapEndNumberAreaCode item.
            /// </summary>
            [RepositoryItem("63a490ee-1a70-4efd-9b92-2ee7444e285c")]
            public virtual Ranorex.SelectTag DapEndNumberAreaCode
            {
                get
                {
                    return _dapendnumberareacodeInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The DapEndNumberAreaCode item info.
            /// </summary>
            [RepositoryItemInfo("63a490ee-1a70-4efd-9b92-2ee7444e285c")]
            public virtual RepoItemInfo DapEndNumberAreaCodeInfo
            {
                get
                {
                    return _dapendnumberareacodeInfo;
                }
            }

            /// <summary>
            /// The DapEndNumberServiceNumber item.
            /// </summary>
            [RepositoryItem("2870da23-c8d8-41fe-a08b-ae2b133bcb65")]
            public virtual Ranorex.InputTag DapEndNumberServiceNumber
            {
                get
                {
                    return _dapendnumberservicenumberInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The DapEndNumberServiceNumber item info.
            /// </summary>
            [RepositoryItemInfo("2870da23-c8d8-41fe-a08b-ae2b133bcb65")]
            public virtual RepoItemInfo DapEndNumberServiceNumberInfo
            {
                get
                {
                    return _dapendnumberservicenumberInfo;
                }
            }

            /// <summary>
            /// The DapSubmitButton item.
            /// </summary>
            [RepositoryItem("5e7cf7df-c4d9-4643-a062-af6b934827da")]
            public virtual Ranorex.ButtonTag DapSubmitButton
            {
                get
                {
                    return _dapsubmitbuttonInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The DapSubmitButton item info.
            /// </summary>
            [RepositoryItemInfo("5e7cf7df-c4d9-4643-a062-af6b934827da")]
            public virtual RepoItemInfo DapSubmitButtonInfo
            {
                get
                {
                    return _dapsubmitbuttonInfo;
                }
            }

            /// <summary>
            /// The ConfirmDapCreationButton item.
            /// </summary>
            [RepositoryItem("bd372775-a873-4fc0-b59a-604273934984")]
            public virtual Ranorex.ButtonTag ConfirmDapCreationButton
            {
                get
                {
                    return _confirmdapcreationbuttonInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ConfirmDapCreationButton item info.
            /// </summary>
            [RepositoryItemInfo("bd372775-a873-4fc0-b59a-604273934984")]
            public virtual RepoItemInfo ConfirmDapCreationButtonInfo
            {
                get
                {
                    return _confirmdapcreationbuttonInfo;
                }
            }

            /// <summary>
            /// The ProfileDdt item.
            /// </summary>
            [RepositoryItem("d38ea138-8e52-4c09-b07c-052c42b6d72d")]
            public virtual Ranorex.ATag ProfileDdt
            {
                get
                {
                    return _profileddtInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ProfileDdt item info.
            /// </summary>
            [RepositoryItemInfo("d38ea138-8e52-4c09-b07c-052c42b6d72d")]
            public virtual RepoItemInfo ProfileDdtInfo
            {
                get
                {
                    return _profileddtInfo;
                }
            }

            /// <summary>
            /// The DropDownLogout item.
            /// </summary>
            [RepositoryItem("1f6e4afa-0eb7-4689-b883-4f114936a726")]
            public virtual Ranorex.ATag DropDownLogout
            {
                get
                {
                    return _dropdownlogoutInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The DropDownLogout item info.
            /// </summary>
            [RepositoryItemInfo("1f6e4afa-0eb7-4689-b883-4f114936a726")]
            public virtual RepoItemInfo DropDownLogoutInfo
            {
                get
                {
                    return _dropdownlogoutInfo;
                }
            }
        }

        /// <summary>
        /// The DropdownAppFolder folder.
        /// </summary>
        [RepositoryFolder("3d5dbb8d-18fd-443f-9f45-e2f60f588bf0")]
        public partial class DropdownAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new Dropdown  folder.
            /// </summary>
            public DropdownAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Dropdown", "/container[@caption='dropdown']", parentFolder, 30000, null, true, "3d5dbb8d-18fd-443f-9f45-e2f60f588bf0", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3d5dbb8d-18fd-443f-9f45-e2f60f588bf0")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3d5dbb8d-18fd-443f-9f45-e2f60f588bf0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The DubberGoogleChromeAppFolder folder.
        /// </summary>
        [RepositoryFolder("74855ecc-d7bf-49ff-b90a-acd1bd6d4fa7")]
        public partial class DubberGoogleChromeAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _clientInfo;

            /// <summary>
            /// Creates a new DubberGoogleChrome  folder.
            /// </summary>
            public DubberGoogleChromeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DubberGoogleChrome", "/form[@title='Dubber - Google Chrome']", parentFolder, 30000, null, true, "74855ecc-d7bf-49ff-b90a-acd1bd6d4fa7", "")
            {
                _clientInfo = new RepoItemInfo(this, "Client", "container[@accessiblename='Google Chrome']/container[2]/container[2]", 30000, null, "c07d0a2f-0cac-4b0c-8ba9-013e7c29b580");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("74855ecc-d7bf-49ff-b90a-acd1bd6d4fa7")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("74855ecc-d7bf-49ff-b90a-acd1bd6d4fa7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Client item.
            /// </summary>
            [RepositoryItem("c07d0a2f-0cac-4b0c-8ba9-013e7c29b580")]
            public virtual Ranorex.Container Client
            {
                get
                {
                    return _clientInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Client item info.
            /// </summary>
            [RepositoryItemInfo("c07d0a2f-0cac-4b0c-8ba9-013e7c29b580")]
            public virtual RepoItemInfo ClientInfo
            {
                get
                {
                    return _clientInfo;
                }
            }
        }

        /// <summary>
        /// The DubberMozillaFirefoxAppFolder folder.
        /// </summary>
        [RepositoryFolder("e4317e8e-ed4d-4517-bb69-4fa3e9cf3c26")]
        public partial class DubberMozillaFirefoxAppFolder : RepoGenBaseFolder
        {
            dubberrepoFolders.GroupingFolder _grouping;
            dubberrepoFolders.Dubber1Folder _dubber1;
            RepoItemInfo _browsertabsInfo;

            /// <summary>
            /// Creates a new DubberMozillaFirefox  folder.
            /// </summary>
            public DubberMozillaFirefoxAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DubberMozillaFirefox", "/form[@title='Dubber - Mozilla Firefox']", parentFolder, 30000, null, true, "e4317e8e-ed4d-4517-bb69-4fa3e9cf3c26", "")
            {
                _grouping = new dubberrepoFolders.GroupingFolder(this);
                _dubber1 = new dubberrepoFolders.Dubber1Folder(this);
                _browsertabsInfo = new RepoItemInfo(this, "BrowserTabs", "toolbar[@accessiblename='Browser tabs']", 30000, null, "ada6f489-50e8-478e-b5a1-f516b1207796");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e4317e8e-ed4d-4517-bb69-4fa3e9cf3c26")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e4317e8e-ed4d-4517-bb69-4fa3e9cf3c26")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The BrowserTabs item.
            /// </summary>
            [RepositoryItem("ada6f489-50e8-478e-b5a1-f516b1207796")]
            public virtual Ranorex.ToolBar BrowserTabs
            {
                get
                {
                    return _browsertabsInfo.CreateAdapter<Ranorex.ToolBar>(true);
                }
            }

            /// <summary>
            /// The BrowserTabs item info.
            /// </summary>
            [RepositoryItemInfo("ada6f489-50e8-478e-b5a1-f516b1207796")]
            public virtual RepoItemInfo BrowserTabsInfo
            {
                get
                {
                    return _browsertabsInfo;
                }
            }

            /// <summary>
            /// The Grouping folder.
            /// </summary>
            [RepositoryFolder("ef7d1c09-b9f2-497d-8e32-da12150bef1c")]
            public virtual dubberrepoFolders.GroupingFolder Grouping
            {
                get { return _grouping; }
            }

            /// <summary>
            /// The Dubber1 folder.
            /// </summary>
            [RepositoryFolder("c560f460-7627-4505-88d4-870c5a736acb")]
            public virtual dubberrepoFolders.Dubber1Folder Dubber1
            {
                get { return _dubber1; }
            }
        }

        /// <summary>
        /// The GroupingFolder folder.
        /// </summary>
        [RepositoryFolder("ef7d1c09-b9f2-497d-8e32-da12150bef1c")]
        public partial class GroupingFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new Grouping  folder.
            /// </summary>
            public GroupingFolder(RepoGenBaseFolder parentFolder) :
                    base("Grouping", "container[@accessiblerole='Grouping']", parentFolder, 30000, null, false, "ef7d1c09-b9f2-497d-8e32-da12150bef1c", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ef7d1c09-b9f2-497d-8e32-da12150bef1c")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ef7d1c09-b9f2-497d-8e32-da12150bef1c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The Dubber1Folder folder.
        /// </summary>
        [RepositoryFolder("c560f460-7627-4505-88d4-870c5a736acb")]
        public partial class Dubber1Folder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new Dubber1  folder.
            /// </summary>
            public Dubber1Folder(RepoGenBaseFolder parentFolder) :
                    base("Dubber1", "container[@accessiblerole='Grouping']//container[@accessiblename='Dubber']", parentFolder, 30000, null, false, "c560f460-7627-4505-88d4-870c5a736acb", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c560f460-7627-4505-88d4-870c5a736acb")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c560f460-7627-4505-88d4-870c5a736acb")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}