///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace dubber
{
    public partial class Recording1
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void Recording1_Open_Browser()
        {
            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://tigers.dubber.net/login' with browser 'chrome' in normal mode.");
            Host.Local.OpenBrowser("https://tigers.dubber.net/login", "chrome", "", false, false, false, false, false);
        }

        public void Set_Value_AreaCountry()
        {
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute TagValue to 'Albania' on item 'Dubber.AreaCountry'.", repo.Dubber.AreaCountryInfo);
            repo.Dubber.AreaCountry.Element.SetAttributeValue("TagValue", "Albania");
        }

    }
}