///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace dubber
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("c1a07f67-5eeb-4e0f-8d73-97d58c6e00e4", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the dubberRepository repository.
        /// </summary>
        public static dubberRepository repo = dubberRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://tigers.dubber.net/login' with browser 'chrome' in normal mode.", new RecordItemIndex(0));
            Host.Local.OpenBrowser("https://tigers.dubber.net/login", "chrome", "", false, false, false, false, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dubber.UserEmail' at 206;27.", repo.Dubber.UserEmailInfo, new RecordItemIndex(1));
            repo.Dubber.UserEmail.Click("206;27");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dropdown' at 189;14.", repo.Dropdown.SelfInfo, new RecordItemIndex(2));
            repo.Dropdown.Self.Click("189;14");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dubber.UserPassword' at 168;22.", repo.Dubber.UserPasswordInfo, new RecordItemIndex(3));
            repo.Dubber.UserPassword.Click("168;22");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dubber.ContentBox' at 203;188.", repo.Dubber.ContentBoxInfo, new RecordItemIndex(4));
            repo.Dubber.ContentBox.Click("203;188");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dubber.SubmitButton' at 38;11.", repo.Dubber.SubmitButtonInfo, new RecordItemIndex(5));
            repo.Dubber.SubmitButton.Click("38;11");
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
