///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace callflow_batch
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the callflow_batchRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    [RepositoryFolder("ec5a97ad-befd-4162-a6e3-0020d48b4cd4")]
    public partial class callflow_batchRepository : RepoGenBaseFolder
    {
        static callflow_batchRepository instance = new callflow_batchRepository();
        callflow_batchRepositoryFolders.DubberMozillaFirefoxAppFolder _dubbermozillafirefox;
        callflow_batchRepositoryFolders.ExplorerAppFolder _explorer;
        callflow_batchRepositoryFolders.GlcndAppFolder _glcnd;
        callflow_batchRepositoryFolders.FileUploadAppFolder _fileupload;

        /// <summary>
        /// Gets the singleton class instance representing the callflow_batchRepository element repository.
        /// </summary>
        [RepositoryFolder("ec5a97ad-befd-4162-a6e3-0020d48b4cd4")]
        public static callflow_batchRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public callflow_batchRepository() 
            : base("callflow_batchRepository", "/", null, 0, false, "ec5a97ad-befd-4162-a6e3-0020d48b4cd4", ".\\RepositoryImages\\callflow_batchRepositoryec5a97ad.rximgres")
        {
            _dubbermozillafirefox = new callflow_batchRepositoryFolders.DubberMozillaFirefoxAppFolder(this);
            _explorer = new callflow_batchRepositoryFolders.ExplorerAppFolder(this);
            _glcnd = new callflow_batchRepositoryFolders.GlcndAppFolder(this);
            _fileupload = new callflow_batchRepositoryFolders.FileUploadAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("ec5a97ad-befd-4162-a6e3-0020d48b4cd4")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The DubberMozillaFirefox folder.
        /// </summary>
        [RepositoryFolder("ee1a7a2d-b218-48b3-b636-8e89ab0ab493")]
        public virtual callflow_batchRepositoryFolders.DubberMozillaFirefoxAppFolder DubberMozillaFirefox
        {
            get { return _dubbermozillafirefox; }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("d37d891c-547f-4a1c-8537-fd3cb126004b")]
        public virtual callflow_batchRepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }

        /// <summary>
        /// The Glcnd folder.
        /// </summary>
        [RepositoryFolder("b3d759a4-1d2a-4550-8285-f6d81a35adec")]
        public virtual callflow_batchRepositoryFolders.GlcndAppFolder Glcnd
        {
            get { return _glcnd; }
        }

        /// <summary>
        /// The FileUpload folder.
        /// </summary>
        [RepositoryFolder("455441af-63e1-48d8-804f-949879b78c64")]
        public virtual callflow_batchRepositoryFolders.FileUploadAppFolder FileUpload
        {
            get { return _fileupload; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    public partial class callflow_batchRepositoryFolders
    {
        /// <summary>
        /// The DubberMozillaFirefoxAppFolder folder.
        /// </summary>
        [RepositoryFolder("ee1a7a2d-b218-48b3-b636-8e89ab0ab493")]
        public partial class DubberMozillaFirefoxAppFolder : RepoGenBaseFolder
        {
            callflow_batchRepositoryFolders.DubberFolder _dubber;
            callflow_batchRepositoryFolders.GroupingFolder _grouping;

            /// <summary>
            /// Creates a new DubberMozillaFirefox  folder.
            /// </summary>
            public DubberMozillaFirefoxAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DubberMozillaFirefox", "/form[@title='Dubber - Mozilla Firefox']", parentFolder, 30000, null, true, "ee1a7a2d-b218-48b3-b636-8e89ab0ab493", "")
            {
                _dubber = new callflow_batchRepositoryFolders.DubberFolder(this);
                _grouping = new callflow_batchRepositoryFolders.GroupingFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ee1a7a2d-b218-48b3-b636-8e89ab0ab493")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ee1a7a2d-b218-48b3-b636-8e89ab0ab493")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Dubber folder.
            /// </summary>
            [RepositoryFolder("a55c8ec0-6caf-48a0-8979-141d1008afe4")]
            public virtual callflow_batchRepositoryFolders.DubberFolder Dubber
            {
                get { return _dubber; }
            }

            /// <summary>
            /// The Grouping folder.
            /// </summary>
            [RepositoryFolder("a85ea9f5-8d48-4579-99ae-6e18ba7f9c7b")]
            public virtual callflow_batchRepositoryFolders.GroupingFolder Grouping
            {
                get { return _grouping; }
            }
        }

        /// <summary>
        /// The DubberFolder folder.
        /// </summary>
        [RepositoryFolder("a55c8ec0-6caf-48a0-8979-141d1008afe4")]
        public partial class DubberFolder : RepoGenBaseFolder
        {
            RepoItemInfo _inboundInfo;
            RepoItemInfo _searchInfo;
            RepoItemInfo _textinbInfo;
            RepoItemInfo _testcomplete2Info;
            RepoItemInfo _dubberInfo;
            RepoItemInfo _browseInfo;
            RepoItemInfo _textuploadInfo;
            RepoItemInfo _noneInfo;
            RepoItemInfo _savechangesInfo;

            /// <summary>
            /// Creates a new Dubber  folder.
            /// </summary>
            public DubberFolder(RepoGenBaseFolder parentFolder) :
                    base("Dubber", "container[@accessiblerole='Grouping']//container[@accessiblename='Dubber']", parentFolder, 30000, null, false, "a55c8ec0-6caf-48a0-8979-141d1008afe4", "")
            {
                _inboundInfo = new RepoItemInfo(this, "Inbound", ".//list[@accessiblerole='List']/listitem[@accessiblename='Inbound']/link[@accessiblename='Inbound']/text[@accessiblename='Inbound']", 30000, null, "6b9f6e42-83f4-4695-9d89-c1c09d0f1601");
                _searchInfo = new RepoItemInfo(this, "Search", "element[3]/element[2]//text[@accessiblename='Search']", 30000, null, "c551d871-a194-4127-963b-24a409c2be88");
                _textinbInfo = new RepoItemInfo(this, "TextInb", "element[3]/element[4]//table[@accessiblerole='Table']/row[@accessiblename~'^A\\ inb\\ 61486549565\\ 6121234']/cell[2]/link[@accessiblename='inb']/text[@accessiblename='inb']", 30000, null, "d020c097-9349-42e0-a216-0a99e6fed50d");
                _testcomplete2Info = new RepoItemInfo(this, "Testcomplete2", "element[3]/element[4]//table[@accessiblerole='Table']/row[@accessiblename~'^A\\ testcomplete2Dubber\\ sss']/cell[2]/link[@accessiblename='testcomplete2']/text[@accessiblename='testcomplete2']", 30000, null, "6cd74c4b-b462-41e4-a5ac-367cb6803a4e");
                _dubberInfo = new RepoItemInfo(this, "Dubber", "", 30000, null, "5a953a3e-eeee-4674-8e40-cc0a7e52a051");
                _browseInfo = new RepoItemInfo(this, "Browse", "element[3]/element[4]/element/element[@accessiblerole='None']/element[@accessiblerole='None']/element[@accessiblerole='None']/element[@accessiblerole='None']/element[6]/?/?/element[@accessiblename='Advance callflow']/button[@accessiblename='Browse…']", 30000, null, "0d472c13-a218-4202-abf8-05136f40e43d");
                _textuploadInfo = new RepoItemInfo(this, "TextUpload", "element[3]/element[4]/element/element[@accessiblerole='None']/element[@accessiblerole='None']/element[@accessiblerole='None']/element[@accessiblerole='None']/element[6]/?/?/button[@accessiblename='Upload']/text[@accessiblename=' Upload ']", 30000, null, "1e021b4c-618c-48aa-8abc-0ada6d7431a5");
                _noneInfo = new RepoItemInfo(this, "None", "element[3]/element[4]/element/element[@accessiblerole='None']/element[@accessiblerole='None']", 30000, null, "7ac407a8-c175-49c7-a6c4-e13ffd1918d7");
                _savechangesInfo = new RepoItemInfo(this, "SaveChanges", "element[3]/element[4]/element/element[@accessiblerole='None']/element[@accessiblerole='None']/element[@accessiblerole='None']/element[@accessiblerole='None']/element[9]/button[@accessiblename='Save Changes']", 30000, null, "158e231d-9493-4674-81ee-4af4e652bd22");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a55c8ec0-6caf-48a0-8979-141d1008afe4")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a55c8ec0-6caf-48a0-8979-141d1008afe4")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Inbound item.
            /// </summary>
            [RepositoryItem("6b9f6e42-83f4-4695-9d89-c1c09d0f1601")]
            public virtual Ranorex.Text Inbound
            {
                get
                {
                    return _inboundInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Inbound item info.
            /// </summary>
            [RepositoryItemInfo("6b9f6e42-83f4-4695-9d89-c1c09d0f1601")]
            public virtual RepoItemInfo InboundInfo
            {
                get
                {
                    return _inboundInfo;
                }
            }

            /// <summary>
            /// The Search item.
            /// </summary>
            [RepositoryItem("c551d871-a194-4127-963b-24a409c2be88")]
            public virtual Ranorex.Text Search
            {
                get
                {
                    return _searchInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Search item info.
            /// </summary>
            [RepositoryItemInfo("c551d871-a194-4127-963b-24a409c2be88")]
            public virtual RepoItemInfo SearchInfo
            {
                get
                {
                    return _searchInfo;
                }
            }

            /// <summary>
            /// The TextInb item.
            /// </summary>
            [RepositoryItem("d020c097-9349-42e0-a216-0a99e6fed50d")]
            public virtual Ranorex.Text TextInb
            {
                get
                {
                    return _textinbInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TextInb item info.
            /// </summary>
            [RepositoryItemInfo("d020c097-9349-42e0-a216-0a99e6fed50d")]
            public virtual RepoItemInfo TextInbInfo
            {
                get
                {
                    return _textinbInfo;
                }
            }

            /// <summary>
            /// The Testcomplete2 item.
            /// </summary>
            [RepositoryItem("6cd74c4b-b462-41e4-a5ac-367cb6803a4e")]
            public virtual Ranorex.Text Testcomplete2
            {
                get
                {
                    return _testcomplete2Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Testcomplete2 item info.
            /// </summary>
            [RepositoryItemInfo("6cd74c4b-b462-41e4-a5ac-367cb6803a4e")]
            public virtual RepoItemInfo Testcomplete2Info
            {
                get
                {
                    return _testcomplete2Info;
                }
            }

            /// <summary>
            /// The Dubber item.
            /// </summary>
            [RepositoryItem("5a953a3e-eeee-4674-8e40-cc0a7e52a051")]
            public virtual Ranorex.Container Dubber
            {
                get
                {
                    return _dubberInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Dubber item info.
            /// </summary>
            [RepositoryItemInfo("5a953a3e-eeee-4674-8e40-cc0a7e52a051")]
            public virtual RepoItemInfo DubberInfo
            {
                get
                {
                    return _dubberInfo;
                }
            }

            /// <summary>
            /// The Browse item.
            /// </summary>
            [RepositoryItem("0d472c13-a218-4202-abf8-05136f40e43d")]
            public virtual Ranorex.Button Browse
            {
                get
                {
                    return _browseInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Browse item info.
            /// </summary>
            [RepositoryItemInfo("0d472c13-a218-4202-abf8-05136f40e43d")]
            public virtual RepoItemInfo BrowseInfo
            {
                get
                {
                    return _browseInfo;
                }
            }

            /// <summary>
            /// The TextUpload item.
            /// </summary>
            [RepositoryItem("1e021b4c-618c-48aa-8abc-0ada6d7431a5")]
            public virtual Ranorex.Text TextUpload
            {
                get
                {
                    return _textuploadInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TextUpload item info.
            /// </summary>
            [RepositoryItemInfo("1e021b4c-618c-48aa-8abc-0ada6d7431a5")]
            public virtual RepoItemInfo TextUploadInfo
            {
                get
                {
                    return _textuploadInfo;
                }
            }

            /// <summary>
            /// The None item.
            /// </summary>
            [RepositoryItem("7ac407a8-c175-49c7-a6c4-e13ffd1918d7")]
            public virtual Ranorex.Unknown None
            {
                get
                {
                    return _noneInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The None item info.
            /// </summary>
            [RepositoryItemInfo("7ac407a8-c175-49c7-a6c4-e13ffd1918d7")]
            public virtual RepoItemInfo NoneInfo
            {
                get
                {
                    return _noneInfo;
                }
            }

            /// <summary>
            /// The SaveChanges item.
            /// </summary>
            [RepositoryItem("158e231d-9493-4674-81ee-4af4e652bd22")]
            public virtual Ranorex.Button SaveChanges
            {
                get
                {
                    return _savechangesInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The SaveChanges item info.
            /// </summary>
            [RepositoryItemInfo("158e231d-9493-4674-81ee-4af4e652bd22")]
            public virtual RepoItemInfo SaveChangesInfo
            {
                get
                {
                    return _savechangesInfo;
                }
            }
        }

        /// <summary>
        /// The GroupingFolder folder.
        /// </summary>
        [RepositoryFolder("a85ea9f5-8d48-4579-99ae-6e18ba7f9c7b")]
        public partial class GroupingFolder : RepoGenBaseFolder
        {
            RepoItemInfo _noneInfo;
            RepoItemInfo _emailaddressInfo;
            RepoItemInfo _passwordInfo;
            RepoItemInfo _loginInfo;
            RepoItemInfo _textdownloadcallflowInfo;
            RepoItemInfo _none1Info;

            /// <summary>
            /// Creates a new Grouping  folder.
            /// </summary>
            public GroupingFolder(RepoGenBaseFolder parentFolder) :
                    base("Grouping", "container[@accessiblerole='Grouping']", parentFolder, 30000, null, false, "a85ea9f5-8d48-4579-99ae-6e18ba7f9c7b", "")
            {
                _noneInfo = new RepoItemInfo(this, "None", "?/?/element[@accessiblerole='None']", 30000, null, "59cd1f2a-f084-4426-ac9c-76e5b0071040");
                _emailaddressInfo = new RepoItemInfo(this, "EmailAddress", "container[@accessiblerole='PropertyPage']/?/?/container[@accessiblename='Dubber']/element[2]/element[2]/element[1]/element/element[2]/element[@accessiblerole='None']/element[@accessiblerole='None']/element[@accessiblerole='None']/element[1]/?/?/text[@accessiblename='Email Address']", 30000, null, "73854d51-1c03-4ff4-8610-143535b7be01");
                _passwordInfo = new RepoItemInfo(this, "Password", "container[@accessiblerole='PropertyPage']/?/?/container[@accessiblename='Dubber']/element[2]/element[2]/element[1]/element/element[2]/element[@accessiblerole='None']/element[@accessiblerole='None']/element[@accessiblerole='None']/element[2]/?/?/text[@accessiblename='Password']", 30000, null, "b5a83bb6-1dcd-4314-a534-45c715a2a42f");
                _loginInfo = new RepoItemInfo(this, "Login", "container[@accessiblerole='PropertyPage']/?/?/container[@accessiblename='Dubber']/element[2]/element[2]/element[1]/element/element[2]/element[@accessiblerole='None']/element[@accessiblerole='None']/element[@accessiblerole='None']/element[3]/button[@accessiblename='Login']", 30000, null, "32bcddb6-f201-44e4-b7b0-34fa9feb65e3");
                _textdownloadcallflowInfo = new RepoItemInfo(this, "TextDownloadCallflow", "container[@accessiblerole='PropertyPage']/?/?/container[@accessiblename='Dubber']/element[3]/element[4]//link[@accessiblename='Download Callflow']/text[@accessiblename=' Download Callflow ']", 30000, null, "0feae00d-60ac-404d-a182-8bd920bed2f8");
                _none1Info = new RepoItemInfo(this, "None1", "container[@accessiblerole='PropertyPage']/?/?/container[@accessiblename='Dubber']/element[3]/element[4]/element/element[@accessiblerole='None']/element[@accessiblerole='None']/element[@accessiblerole='None']/element[@accessiblerole='None']/element[8]", 30000, null, "6ddb88c9-bab2-4a22-b7dd-b46f07a34ca8");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a85ea9f5-8d48-4579-99ae-6e18ba7f9c7b")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a85ea9f5-8d48-4579-99ae-6e18ba7f9c7b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The None item.
            /// </summary>
            [RepositoryItem("59cd1f2a-f084-4426-ac9c-76e5b0071040")]
            public virtual Ranorex.Unknown None
            {
                get
                {
                    return _noneInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The None item info.
            /// </summary>
            [RepositoryItemInfo("59cd1f2a-f084-4426-ac9c-76e5b0071040")]
            public virtual RepoItemInfo NoneInfo
            {
                get
                {
                    return _noneInfo;
                }
            }

            /// <summary>
            /// The EmailAddress item.
            /// </summary>
            [RepositoryItem("73854d51-1c03-4ff4-8610-143535b7be01")]
            public virtual Ranorex.Text EmailAddress
            {
                get
                {
                    return _emailaddressInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EmailAddress item info.
            /// </summary>
            [RepositoryItemInfo("73854d51-1c03-4ff4-8610-143535b7be01")]
            public virtual RepoItemInfo EmailAddressInfo
            {
                get
                {
                    return _emailaddressInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("b5a83bb6-1dcd-4314-a534-45c715a2a42f")]
            public virtual Ranorex.Text Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("b5a83bb6-1dcd-4314-a534-45c715a2a42f")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The Login item.
            /// </summary>
            [RepositoryItem("32bcddb6-f201-44e4-b7b0-34fa9feb65e3")]
            public virtual Ranorex.Button Login
            {
                get
                {
                    return _loginInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Login item info.
            /// </summary>
            [RepositoryItemInfo("32bcddb6-f201-44e4-b7b0-34fa9feb65e3")]
            public virtual RepoItemInfo LoginInfo
            {
                get
                {
                    return _loginInfo;
                }
            }

            /// <summary>
            /// The TextDownloadCallflow item.
            /// </summary>
            [RepositoryItem("0feae00d-60ac-404d-a182-8bd920bed2f8")]
            public virtual Ranorex.Text TextDownloadCallflow
            {
                get
                {
                    return _textdownloadcallflowInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TextDownloadCallflow item info.
            /// </summary>
            [RepositoryItemInfo("0feae00d-60ac-404d-a182-8bd920bed2f8")]
            public virtual RepoItemInfo TextDownloadCallflowInfo
            {
                get
                {
                    return _textdownloadcallflowInfo;
                }
            }

            /// <summary>
            /// The None1 item.
            /// </summary>
            [RepositoryItem("6ddb88c9-bab2-4a22-b7dd-b46f07a34ca8")]
            public virtual Ranorex.Unknown None1
            {
                get
                {
                    return _none1Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The None1 item info.
            /// </summary>
            [RepositoryItemInfo("6ddb88c9-bab2-4a22-b7dd-b46f07a34ca8")]
            public virtual RepoItemInfo None1Info
            {
                get
                {
                    return _none1Info;
                }
            }
        }

        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("d37d891c-547f-4a1c-8537-fd3cb126004b")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/form[@title='']", parentFolder, 30000, null, true, "d37d891c-547f-4a1c-8537-fd3cb126004b", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d37d891c-547f-4a1c-8537-fd3cb126004b")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d37d891c-547f-4a1c-8537-fd3cb126004b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The GlcndAppFolder folder.
        /// </summary>
        [RepositoryFolder("b3d759a4-1d2a-4550-8285-f6d81a35adec")]
        public partial class GlcndAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new Glcnd  folder.
            /// </summary>
            public GlcndAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Glcnd", "/form[@processname='glcnd']", parentFolder, 30000, null, true, "b3d759a4-1d2a-4550-8285-f6d81a35adec", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b3d759a4-1d2a-4550-8285-f6d81a35adec")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b3d759a4-1d2a-4550-8285-f6d81a35adec")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The FileUploadAppFolder folder.
        /// </summary>
        [RepositoryFolder("455441af-63e1-48d8-804f-949879b78c64")]
        public partial class FileUploadAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _text1148Info;
            RepoItemInfo _combobox1148Info;
            RepoItemInfo _buttonopenInfo;

            /// <summary>
            /// Creates a new FileUpload  folder.
            /// </summary>
            public FileUploadAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FileUpload", "/form[@title='File Upload']", parentFolder, 30000, null, true, "455441af-63e1-48d8-804f-949879b78c64", "")
            {
                _text1148Info = new RepoItemInfo(this, "Text1148", "?/?/text[@controlid='1148']", 30000, null, "ea3a0c65-3764-4f96-a179-3da825947971");
                _combobox1148Info = new RepoItemInfo(this, "ComboBox1148", "combobox[@controlid='1148']", 30000, null, "aabc4f81-3cca-44c6-bf89-f04878b65f85");
                _buttonopenInfo = new RepoItemInfo(this, "ButtonOpen", "button[@text='&Open']", 30000, null, "8ebed321-41fd-4798-b697-395ad2c6e7cb");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("455441af-63e1-48d8-804f-949879b78c64")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("455441af-63e1-48d8-804f-949879b78c64")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Text1148 item.
            /// </summary>
            [RepositoryItem("ea3a0c65-3764-4f96-a179-3da825947971")]
            public virtual Ranorex.Text Text1148
            {
                get
                {
                    return _text1148Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text1148 item info.
            /// </summary>
            [RepositoryItemInfo("ea3a0c65-3764-4f96-a179-3da825947971")]
            public virtual RepoItemInfo Text1148Info
            {
                get
                {
                    return _text1148Info;
                }
            }

            /// <summary>
            /// The ComboBox1148 item.
            /// </summary>
            [RepositoryItem("aabc4f81-3cca-44c6-bf89-f04878b65f85")]
            public virtual Ranorex.ComboBox ComboBox1148
            {
                get
                {
                    return _combobox1148Info.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The ComboBox1148 item info.
            /// </summary>
            [RepositoryItemInfo("aabc4f81-3cca-44c6-bf89-f04878b65f85")]
            public virtual RepoItemInfo ComboBox1148Info
            {
                get
                {
                    return _combobox1148Info;
                }
            }

            /// <summary>
            /// The ButtonOpen item.
            /// </summary>
            [RepositoryItem("8ebed321-41fd-4798-b697-395ad2c6e7cb")]
            public virtual Ranorex.Button ButtonOpen
            {
                get
                {
                    return _buttonopenInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOpen item info.
            /// </summary>
            [RepositoryItemInfo("8ebed321-41fd-4798-b697-395ad2c6e7cb")]
            public virtual RepoItemInfo ButtonOpenInfo
            {
                get
                {
                    return _buttonopenInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}