///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace callflow_batch
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Downloading_callflow recording.
    /// </summary>
    [TestModule("1b419ff6-c519-4de8-accc-f71ff7bd9824", ModuleType.Recording, 1)]
    public partial class Downloading_callflow : ITestModule
    {
        /// <summary>
        /// Holds an instance of the callflow_batchRepository repository.
        /// </summary>
        public static callflow_batchRepository repo = callflow_batchRepository.Instance;

        static Downloading_callflow instance = new Downloading_callflow();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Downloading_callflow()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Downloading_callflow Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'DubberMozillaFirefox.Grouping.None1' at 729;223.", repo.DubberMozillaFirefox.Grouping.None1Info, new RecordItemIndex(0));
            repo.DubberMozillaFirefox.Grouping.None1.MoveTo("729;223");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://tigers.dubber.net/login' with browser 'firefox' in normal mode.", new RecordItemIndex(1));
            Host.Local.OpenBrowser("https://tigers.dubber.net/login", "firefox", "", false, false, false, false, false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Grouping.EmailAddress' at 168;13.", repo.DubberMozillaFirefox.Grouping.EmailAddressInfo, new RecordItemIndex(2));
            repo.DubberMozillaFirefox.Grouping.EmailAddress.Click("168;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Grouping.Password' at 131;17.", repo.DubberMozillaFirefox.Grouping.PasswordInfo, new RecordItemIndex(3));
            repo.DubberMozillaFirefox.Grouping.Password.Click("131;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Grouping.Login' at 19;18.", repo.DubberMozillaFirefox.Grouping.LoginInfo, new RecordItemIndex(4));
            repo.DubberMozillaFirefox.Grouping.Login.Click("19;18");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Grouping.Login' at 65;16.", repo.DubberMozillaFirefox.Grouping.LoginInfo, new RecordItemIndex(5));
            repo.DubberMozillaFirefox.Grouping.Login.Click("65;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber.Search' at 27;6.", repo.DubberMozillaFirefox.Dubber.SearchInfo, new RecordItemIndex(6));
            repo.DubberMozillaFirefox.Dubber.Search.Click("27;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'test' with focus on 'DubberMozillaFirefox.Dubber.Search'.", repo.DubberMozillaFirefox.Dubber.SearchInfo, new RecordItemIndex(7));
            repo.DubberMozillaFirefox.Dubber.Search.PressKeys("test");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'complete2{Return}' with focus on 'DubberMozillaFirefox.Dubber.Search'.", repo.DubberMozillaFirefox.Dubber.SearchInfo, new RecordItemIndex(8));
            repo.DubberMozillaFirefox.Dubber.Search.PressKeys("complete2{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber.Testcomplete2' at 61;10.", repo.DubberMozillaFirefox.Dubber.Testcomplete2Info, new RecordItemIndex(9));
            repo.DubberMozillaFirefox.Dubber.Testcomplete2.Click("61;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber.Inbound' at 21;11.", repo.DubberMozillaFirefox.Dubber.InboundInfo, new RecordItemIndex(10));
            repo.DubberMozillaFirefox.Dubber.Inbound.Click("21;11");
            Delay.Milliseconds(200);
            
            Mouse_Click_TextInb1();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse None Move item 'DubberMozillaFirefox.Grouping.None' at 1356;335.", repo.DubberMozillaFirefox.Grouping.NoneInfo, new RecordItemIndex(12));
            repo.DubberMozillaFirefox.Grouping.None.MoveTo("1356;335");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'DubberMozillaFirefox.Grouping.None' at 1356;334.", repo.DubberMozillaFirefox.Grouping.NoneInfo, new RecordItemIndex(13));
            repo.DubberMozillaFirefox.Grouping.None.MoveTo("1356;334");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'DubberMozillaFirefox.Grouping.None' at 1356;334.", repo.DubberMozillaFirefox.Grouping.NoneInfo, new RecordItemIndex(14));
            repo.DubberMozillaFirefox.Grouping.None.MoveTo("1356;334");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse None Move item 'DubberMozillaFirefox.Grouping.None' at 1356;344.", repo.DubberMozillaFirefox.Grouping.NoneInfo, new RecordItemIndex(15));
            repo.DubberMozillaFirefox.Grouping.None.MoveTo("1356;344");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'DubberMozillaFirefox.Grouping.None' at 1356;344.", repo.DubberMozillaFirefox.Grouping.NoneInfo, new RecordItemIndex(16));
            repo.DubberMozillaFirefox.Grouping.None.MoveTo("1356;344");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'DubberMozillaFirefox.Grouping.None' at 1349;411.", repo.DubberMozillaFirefox.Grouping.NoneInfo, new RecordItemIndex(17));
            repo.DubberMozillaFirefox.Grouping.None.MoveTo("1349;411");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse None Move item 'DubberMozillaFirefox.Grouping.None' at 1349;411.", repo.DubberMozillaFirefox.Grouping.NoneInfo, new RecordItemIndex(18));
            repo.DubberMozillaFirefox.Grouping.None.MoveTo("1349;411");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'DubberMozillaFirefox.Grouping.None' at 1355;401.", repo.DubberMozillaFirefox.Grouping.NoneInfo, new RecordItemIndex(19));
            repo.DubberMozillaFirefox.Grouping.None.MoveTo("1355;401");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse None Move item 'Glcnd' at 1352;524.", repo.Glcnd.SelfInfo, new RecordItemIndex(20));
            repo.Glcnd.Self.MoveTo("1352;524");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'DubberMozillaFirefox.Grouping.None' at 1358;346.", repo.DubberMozillaFirefox.Grouping.NoneInfo, new RecordItemIndex(21));
            repo.DubberMozillaFirefox.Grouping.None.MoveTo("1358;346");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse None Move item 'DubberMozillaFirefox.Grouping.None' at 1361;456.", repo.DubberMozillaFirefox.Grouping.NoneInfo, new RecordItemIndex(22));
            repo.DubberMozillaFirefox.Grouping.None.MoveTo("1361;456");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'DubberMozillaFirefox.Grouping.None1' at 729;295.", repo.DubberMozillaFirefox.Grouping.None1Info, new RecordItemIndex(23));
            repo.DubberMozillaFirefox.Grouping.None1.MoveTo("729;295");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse None Move item 'DubberMozillaFirefox.Grouping.None1' at 729;295.", repo.DubberMozillaFirefox.Grouping.None1Info, new RecordItemIndex(24));
            repo.DubberMozillaFirefox.Grouping.None1.MoveTo("729;295");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse None Move item 'DubberMozillaFirefox.Grouping.None1' at 732;240.", repo.DubberMozillaFirefox.Grouping.None1Info, new RecordItemIndex(25));
            repo.DubberMozillaFirefox.Grouping.None1.MoveTo("732;240");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'DubberMozillaFirefox.Grouping.None1' at 732;240.", repo.DubberMozillaFirefox.Grouping.None1Info, new RecordItemIndex(26));
            repo.DubberMozillaFirefox.Grouping.None1.MoveTo("732;240");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'DubberMozillaFirefox.Grouping.None1' at 724;352.", repo.DubberMozillaFirefox.Grouping.None1Info, new RecordItemIndex(27));
            repo.DubberMozillaFirefox.Grouping.None1.MoveTo("724;352");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse None Move item 'DubberMozillaFirefox.Grouping.None1' at 724;352.", repo.DubberMozillaFirefox.Grouping.None1Info, new RecordItemIndex(28));
            repo.DubberMozillaFirefox.Grouping.None1.MoveTo("724;352");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse None Move item 'DubberMozillaFirefox.Grouping.TextDownloadCallflow' at 90;0.", repo.DubberMozillaFirefox.Grouping.TextDownloadCallflowInfo, new RecordItemIndex(29));
            repo.DubberMozillaFirefox.Grouping.TextDownloadCallflow.MoveTo("90;0");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Grouping.TextDownloadCallflow' at 90;0.", repo.DubberMozillaFirefox.Grouping.TextDownloadCallflowInfo, new RecordItemIndex(30));
            repo.DubberMozillaFirefox.Grouping.TextDownloadCallflow.Click("90;0");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
