///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace callflow_batch
{
    public partial class Downloading_callflow
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void Mouse_Click_TextInb()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber.TextInb' at 15;8.", repo.DubberMozillaFirefox.Dubber.TextInbInfo);
            repo.DubberMozillaFirefox.Dubber.TextInb.Click("15;8");
            Thread.Sleep(5000);
        }

        public void Mouse_Click_TextInb1()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber.TextInb' at 11;5.", repo.DubberMozillaFirefox.Dubber.TextInbInfo);
            repo.DubberMozillaFirefox.Dubber.TextInb.Click("11;5");
            Thread.Sleep(10000);
        }

    }
}