///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace callflow_batch
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The uploading_c recording.
    /// </summary>
    [TestModule("0f0fefb7-05e1-4b5f-9958-792cb67a3dfd", ModuleType.Recording, 1)]
    public partial class uploading_c : ITestModule
    {
        /// <summary>
        /// Holds an instance of the callflow_batchRepository repository.
        /// </summary>
        public static callflow_batchRepository repo = callflow_batchRepository.Instance;

        static uploading_c instance = new uploading_c();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public uploading_c()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static uploading_c Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse None Move item 'DubberMozillaFirefox.Grouping.None' at 1365;419.", repo.DubberMozillaFirefox.Grouping.NoneInfo, new RecordItemIndex(0));
            repo.DubberMozillaFirefox.Grouping.None.MoveTo("1365;419");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'DubberMozillaFirefox.Grouping.None' at 1358;409.", repo.DubberMozillaFirefox.Grouping.NoneInfo, new RecordItemIndex(1));
            repo.DubberMozillaFirefox.Grouping.None.MoveTo("1358;409");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse None Move item 'DubberMozillaFirefox.Grouping.None' at 1358;394.", repo.DubberMozillaFirefox.Grouping.NoneInfo, new RecordItemIndex(2));
            repo.DubberMozillaFirefox.Grouping.None.MoveTo("1358;394");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse None Move item 'DubberMozillaFirefox.Grouping.None' at 1362;365.", repo.DubberMozillaFirefox.Grouping.NoneInfo, new RecordItemIndex(3));
            repo.DubberMozillaFirefox.Grouping.None.MoveTo("1362;365");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse None Move item 'DubberMozillaFirefox.Grouping.None' at 1362;335.", repo.DubberMozillaFirefox.Grouping.NoneInfo, new RecordItemIndex(4));
            repo.DubberMozillaFirefox.Grouping.None.MoveTo("1362;335");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse None Move item 'DubberMozillaFirefox.Grouping.None' at 1358;307.", repo.DubberMozillaFirefox.Grouping.NoneInfo, new RecordItemIndex(5));
            repo.DubberMozillaFirefox.Grouping.None.MoveTo("1358;307");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse None Move item 'DubberMozillaFirefox.Grouping.None' at 1351;280.", repo.DubberMozillaFirefox.Grouping.NoneInfo, new RecordItemIndex(6));
            repo.DubberMozillaFirefox.Grouping.None.MoveTo("1351;280");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse None Move item 'DubberMozillaFirefox.Dubber.Dubber' at 1348;252.", repo.DubberMozillaFirefox.Dubber.DubberInfo, new RecordItemIndex(7));
            repo.DubberMozillaFirefox.Dubber.Dubber.MoveTo("1348;252");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse None Move item 'DubberMozillaFirefox.Dubber.Dubber' at 1348;232.", repo.DubberMozillaFirefox.Dubber.DubberInfo, new RecordItemIndex(8));
            repo.DubberMozillaFirefox.Dubber.Dubber.MoveTo("1348;232");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse None Move item 'DubberMozillaFirefox.Dubber.Dubber' at 1348;224.", repo.DubberMozillaFirefox.Dubber.DubberInfo, new RecordItemIndex(9));
            repo.DubberMozillaFirefox.Dubber.Dubber.MoveTo("1348;224");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse None Move item 'DubberMozillaFirefox.Grouping.None' at 1356;193.", repo.DubberMozillaFirefox.Grouping.NoneInfo, new RecordItemIndex(10));
            repo.DubberMozillaFirefox.Grouping.None.MoveTo("1356;193");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse None Move item 'DubberMozillaFirefox.Grouping.None' at 1365;111.", repo.DubberMozillaFirefox.Grouping.NoneInfo, new RecordItemIndex(11));
            repo.DubberMozillaFirefox.Grouping.None.MoveTo("1365;111");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'DubberMozillaFirefox.Grouping.None' at 1365;111.", repo.DubberMozillaFirefox.Grouping.NoneInfo, new RecordItemIndex(12));
            repo.DubberMozillaFirefox.Grouping.None.MoveTo("1365;111");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber.Browse' at 53;11.", repo.DubberMozillaFirefox.Dubber.BrowseInfo, new RecordItemIndex(13));
            repo.DubberMozillaFirefox.Dubber.Browse.Click("53;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FileUpload.Text1148' at 54;5.", repo.FileUpload.Text1148Info, new RecordItemIndex(14));
            repo.FileUpload.Text1148.Click("54;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'nb' with focus on 'FileUpload.Text1148'.", repo.FileUpload.Text1148Info, new RecordItemIndex(15));
            repo.FileUpload.Text1148.PressKeys("nb");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '={Back}{Back}{Back}{Back}nb' with focus on 'FileUpload.Text1148'.", repo.FileUpload.Text1148Info, new RecordItemIndex(16));
            repo.FileUpload.Text1148.PressKeys("={Back}{Back}{Back}{Back}nb");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FileUpload.ComboBox1148' at 84;4.", repo.FileUpload.ComboBox1148Info, new RecordItemIndex(17));
            repo.FileUpload.ComboBox1148.Click("84;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'inb=call{Back}{Back}{Back}{Back}{Back}-call' with focus on 'FileUpload.Text1148'.", repo.FileUpload.Text1148Info, new RecordItemIndex(18));
            repo.FileUpload.Text1148.PressKeys("inb=call{Back}{Back}{Back}{Back}{Back}-call");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'flow.xml' with focus on 'FileUpload.Text1148'.", repo.FileUpload.Text1148Info, new RecordItemIndex(19));
            repo.FileUpload.Text1148.PressKeys("flow.xml");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FileUpload.ButtonOpen' at 66;8.", repo.FileUpload.ButtonOpenInfo, new RecordItemIndex(20));
            repo.FileUpload.ButtonOpen.Click("66;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber.TextUpload' at 25;10.", repo.DubberMozillaFirefox.Dubber.TextUploadInfo, new RecordItemIndex(21));
            repo.DubberMozillaFirefox.Dubber.TextUpload.Click("25;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'm'.", new RecordItemIndex(22));
            Keyboard.Press("m");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'DubberMozillaFirefox.Grouping.None' at 1358;313.", repo.DubberMozillaFirefox.Grouping.NoneInfo, new RecordItemIndex(23));
            repo.DubberMozillaFirefox.Grouping.None.MoveTo("1358;313");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'DubberMozillaFirefox.Grouping.None' at 1359;329.", repo.DubberMozillaFirefox.Grouping.NoneInfo, new RecordItemIndex(24));
            repo.DubberMozillaFirefox.Grouping.None.MoveTo("1359;329");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'DubberMozillaFirefox.Grouping.None' at 1360;341.", repo.DubberMozillaFirefox.Grouping.NoneInfo, new RecordItemIndex(25));
            repo.DubberMozillaFirefox.Grouping.None.MoveTo("1360;341");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse None Move item 'DubberMozillaFirefox.Grouping.None' at 1360;358.", repo.DubberMozillaFirefox.Grouping.NoneInfo, new RecordItemIndex(26));
            repo.DubberMozillaFirefox.Grouping.None.MoveTo("1360;358");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse None Move item 'DubberMozillaFirefox.Grouping.None' at 1360;406.", repo.DubberMozillaFirefox.Grouping.NoneInfo, new RecordItemIndex(27));
            repo.DubberMozillaFirefox.Grouping.None.MoveTo("1360;406");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse None Move item 'DubberMozillaFirefox.Grouping.None' at 1351;443.", repo.DubberMozillaFirefox.Grouping.NoneInfo, new RecordItemIndex(28));
            repo.DubberMozillaFirefox.Grouping.None.MoveTo("1351;443");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse None Move item 'Glcnd' at 1346;587.", repo.Glcnd.SelfInfo, new RecordItemIndex(29));
            repo.Glcnd.Self.MoveTo("1346;587");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse None Move item 'Glcnd' at 1346;651.", repo.Glcnd.SelfInfo, new RecordItemIndex(30));
            repo.Glcnd.Self.MoveTo("1346;651");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse None Move item 'Glcnd' at 1322;699.", repo.Glcnd.SelfInfo, new RecordItemIndex(31));
            repo.Glcnd.Self.MoveTo("1322;699");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'DubberMozillaFirefox.Grouping.None1' at 730;220.", repo.DubberMozillaFirefox.Grouping.None1Info, new RecordItemIndex(32));
            repo.DubberMozillaFirefox.Grouping.None1.MoveTo("730;220");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse None Move item 'DubberMozillaFirefox.Dubber.None' at 754;764.", repo.DubberMozillaFirefox.Dubber.NoneInfo, new RecordItemIndex(33));
            repo.DubberMozillaFirefox.Dubber.None.MoveTo("754;764");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse None Move item 'DubberMozillaFirefox.Dubber.None' at 755;787.", repo.DubberMozillaFirefox.Dubber.NoneInfo, new RecordItemIndex(34));
            repo.DubberMozillaFirefox.Dubber.None.MoveTo("755;787");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse None Move item 'DubberMozillaFirefox.Grouping.None1' at 737;315.", repo.DubberMozillaFirefox.Grouping.None1Info, new RecordItemIndex(35));
            repo.DubberMozillaFirefox.Grouping.None1.MoveTo("737;315");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse None Move item 'DubberMozillaFirefox.Grouping.None1' at 729;381.", repo.DubberMozillaFirefox.Grouping.None1Info, new RecordItemIndex(36));
            repo.DubberMozillaFirefox.Grouping.None1.MoveTo("729;381");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'DubberMozillaFirefox.Grouping.None1' at 729;382.", repo.DubberMozillaFirefox.Grouping.None1Info, new RecordItemIndex(37));
            repo.DubberMozillaFirefox.Grouping.None1.MoveTo("729;382");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber.SaveChanges' at 81;4.", repo.DubberMozillaFirefox.Dubber.SaveChangesInfo, new RecordItemIndex(38));
            repo.DubberMozillaFirefox.Dubber.SaveChanges.Click("81;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Dubber.TextInb' at 15;8.", repo.DubberMozillaFirefox.Dubber.TextInbInfo, new RecordItemIndex(39));
            repo.DubberMozillaFirefox.Dubber.TextInb.Click("15;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse None Move item 'DubberMozillaFirefox.Grouping.None' at 1357;303.", repo.DubberMozillaFirefox.Grouping.NoneInfo, new RecordItemIndex(40));
            repo.DubberMozillaFirefox.Grouping.None.MoveTo("1357;303");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'DubberMozillaFirefox.Grouping.None' at 1357;303.", repo.DubberMozillaFirefox.Grouping.NoneInfo, new RecordItemIndex(41));
            repo.DubberMozillaFirefox.Grouping.None.MoveTo("1357;303");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse None Move item 'DubberMozillaFirefox.Grouping.None' at 1359;339.", repo.DubberMozillaFirefox.Grouping.NoneInfo, new RecordItemIndex(42));
            repo.DubberMozillaFirefox.Grouping.None.MoveTo("1359;339");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse None Move item 'DubberMozillaFirefox.Grouping.None' at 1357;429.", repo.DubberMozillaFirefox.Grouping.NoneInfo, new RecordItemIndex(43));
            repo.DubberMozillaFirefox.Grouping.None.MoveTo("1357;429");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse None Move item 'DubberMozillaFirefox.Grouping.None' at 1361;528.", repo.DubberMozillaFirefox.Grouping.NoneInfo, new RecordItemIndex(44));
            repo.DubberMozillaFirefox.Grouping.None.MoveTo("1361;528");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'DubberMozillaFirefox.Grouping.None1' at 731;224.", repo.DubberMozillaFirefox.Grouping.None1Info, new RecordItemIndex(45));
            repo.DubberMozillaFirefox.Grouping.None1.MoveTo("731;224");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse None Move item 'DubberMozillaFirefox.Grouping.None1' at 731;224.", repo.DubberMozillaFirefox.Grouping.None1Info, new RecordItemIndex(46));
            repo.DubberMozillaFirefox.Grouping.None1.MoveTo("731;224");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse None Move item 'DubberMozillaFirefox.Grouping.None1' at 731;237.", repo.DubberMozillaFirefox.Grouping.None1Info, new RecordItemIndex(47));
            repo.DubberMozillaFirefox.Grouping.None1.MoveTo("731;237");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse None Move item 'DubberMozillaFirefox.Grouping.None1' at 736;304.", repo.DubberMozillaFirefox.Grouping.None1Info, new RecordItemIndex(48));
            repo.DubberMozillaFirefox.Grouping.None1.MoveTo("736;304");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse None Move item 'DubberMozillaFirefox.Dubber.None' at 754;879.", repo.DubberMozillaFirefox.Dubber.NoneInfo, new RecordItemIndex(49));
            repo.DubberMozillaFirefox.Dubber.None.MoveTo("754;879");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'DubberMozillaFirefox.Grouping.None1' at 736;399.", repo.DubberMozillaFirefox.Grouping.None1Info, new RecordItemIndex(50));
            repo.DubberMozillaFirefox.Grouping.None1.MoveTo("736;399");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DubberMozillaFirefox.Grouping.TextDownloadCallflow' at 66;1.", repo.DubberMozillaFirefox.Grouping.TextDownloadCallflowInfo, new RecordItemIndex(51));
            repo.DubberMozillaFirefox.Grouping.TextDownloadCallflow.Click("66;1");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
